### ISSUE TITLE
Local file dump for uid table for faster restarts

### ISSUE THREAD

**Issue by jsbali** [OpenTSDB/opentsdb#1007]
We have a big enough cluster which ingests 2.2M datapoints/sec. Also we have many uids created to the 
tune of 16Mil total and uid-name cache mapping hashmap size is around 6M.
So whenever a restart of opentsdb occurs performance takes a hit when cache is getting warmed.

One way  to solve this problem is have a local dump which can be read at startup which will greatly reduce 
startup and stabilising times. This will help for already created ids and the news ones or those not in the 
cache can be lazily warmed in the way we do it now.

Ways to generate a file can be 
1. Have Tsdb regularly dump its local contents to file say every 5 mins.
2. Expose an api which responds with that content which can then be dumped to file outside of tsdb process. 

Please suggest as to how can we achieve this.

**Comment by manolama** [comment]
It's actually something that we have in-house as well that I need to bubble up. I'll try squeezing it into 2.4 (even though I don't like adding features post RC).

**Comment by jsbali** [comment]
Appreciate it Chris
