### ISSUE TITLE
Querying metric produces wrong label on graph

### ISSUE THREAD

**Issue by bka9** [OpenTSDB/opentsdb#1016]
This is not consistent, but I have found that there are several metrics that I query and the resulting graph seems to be labeling it with a different metric.

![screen shot 2017-07-07 at 11 00 04 am](https://user-images.githubusercontent.com/560648/27968508-8a5087d4-6304-11e7-965c-a893f90c07da.png)

Any ideas as to what would cause this?

**Comment by manolama** [comment]
That's usually a UID corruption issue. Can you try restarting your read TSD and issue the same query again? Also try running the UID fsck utility to check for conflicts.

**Comment by BaconFries** [comment]
I had the same issue with opentsdb-2.4.0RC1. I tried the fsck, metasync, metapruge, dropcaches, and restarting; nothing worked.  I then downgraded to opentsdb-2.3 and the issue resolved itself.

**Comment by IDerr** [comment]
@manolama you can close this (bug with 2.4)

**Comment by IDerr** [comment]
Hi @bka9
if your question has been answered can you close this issue please ?

Thanks
