### ISSUE TITLE
Documentation on Streaming Quantiles and Digests in 2.4

### ISSUE THREAD

**Issue by bearrito** [OpenTSDB/opentsdb#1025]
I'm very interested in the use of Streaming Quantiles!

Is there any documentation on the usage? Maybe I just missed it?

**Comment by bearrito** [comment]
I now see this - http://opentsdb.net/docs/build/html/api_http/histogram.html?highlight=histogram

To clarify I'm more interested in how to gain access to the features mentioned in https://www.slideshare.net/HBaseCon/opentsdb-hbasecon2017.  In particular, the  usage of datasketch library. I currently use this from Storm and would love to use it in a more native fashion.

**Comment by manolama** [comment]
I'll finish up the docs, make sure they're good but the plugin mentioned in HBaseCon can be found at https://github.com/OpenTSDB/opentsdb-datasketches. I don't have a release yet so you just have to run the ``mvn package`` and copy it to your plugin directory. The readme has some details on how to create the sketches/histos. Then if you're using the JAVA API, you would call ``TSDB.addHistogramPoint()`` to write the values. Hope that helps :)

**Comment by bearrito** [comment]
I think I have a deeper question, which I'll ask on the usergroup.

Thanks for the response!
