### ISSUE TITLE
RC Candidate for 2.4 at mvnrepository

### ISSUE THREAD

**Issue by bearrito** [OpenTSDB/opentsdb#1026]
Is there a plan to release 2.4 at https://mvnrepository.com/artifact/net.opentsdb/opentsdb?

**Comment by manolama** [comment]
Oh yeah, sorry. I think I posted the snapshots but not the RC. Lemme get that out.

**Comment by manolama** [comment]
Pushed, should be up there in an hour or two, thanks!
