### ISSUE TITLE
[2.3.0 Tag] Build issue for BigTable backend

### ISSUE THREAD

**Issue by maciejasembler** [OpenTSDB/opentsdb#1029]
Hello,

I recently switched building RPM for OpenTSDB with BigTable from master to 2.3.0 tag due to other issues.

What I noticed is that after building OpenTSDB will not start:

`Caused by: java.io.IOException: java.lang.ClassNotFoundException: com.google.cloud.bigtable.hbase1_2.BigtableConnection
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:230)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at org.hbase.async.HBaseClient.<init>(HBaseClient.java:283)
        ... 4 more
`
The solution was to bump asyncbigtable jar from 0.2.1-20160228.235952-3 to 0.3.0

Can you guys fix include mk properly ? For now I use a simple hack to replace asyncbigtable from 0.2.1 to 0.3.0 (with deps)

**Comment by manolama** [comment]
Hi sorry for the trouble, was this when you built the RPM and installed it that it didn't pull in the proper asyncbigtable jar?

**Comment by maciejasembler** [comment]
Actually I have found the root cause, I was referencing to hbase1_2 libraries in my OpenTSDB config file, whereas 2.3.0 tag has 1.0 included (master has 1.2 included)

hbase.client.connection.impl=com.google.cloud.bigtable.hbase1_2.BigtableConnection

This actually was after successful compilation I tried to run OpenTSDB with this directive.

You may want to bump the jar, anyways feel free to close the ticket.

**Comment by manolama** [comment]
Cool, thanks!
