### ISSUE TITLE
2.4.0 start fail

### ISSUE THREAD

**Issue by jinlongwang** [OpenTSDB/opentsdb#1040]
i had update to 2.4.0 by rpm install. but can not start opentsdb when i used `/etc/init.d/opentsdb start`
![image](https://user-images.githubusercontent.com/2275120/29022828-84331aea-7b9d-11e7-8b6d-72599765e81f.png)

and the java environment is correct
![image](https://user-images.githubusercontent.com/2275120/29022916-ee1bbc32-7b9d-11e7-9497-2df6348ffafb.png)

**Comment by manolama** [comment]
what happens if you run ``which java``?

**Comment by jinlongwang** [comment]
![image](https://user-images.githubusercontent.com/2275120/29053064-7825f7e4-7c20-11e7-94ed-2d559b9b1848.png)

it's weird because when i used `/etc/init.d/opentsdb start` the tsdb is started failed.  

but when i used `nohup /usr/bin/tsdb tsd --config=/etc/opentsdb/opentsdb.conf 1>> /var/log/opentsdb/opentsdb-dn-2-75.hadoop.sjz-opentsdb.out 2>> /var/log/opentsdb/opentsdb-dn-2-75.hadoop.sjz-opentsdb.err &` opentsdb is started!

**Comment by manolama** [comment]
Yeah there's something wrong with that init script. Do you have the opentsdb user as well?

**Comment by IDerr** [comment]
Any news @jinlongwang ?

**Comment by jinlongwang** [comment]
i edit `/usr/bin/tsdb`. line 106 `JAVA=${JAVA-'java'}`  to java absolute path `JAVA=${JAVA-'/usr/lib/java/bin/java'}` and this problem was solved.

**Comment by IDerr** [comment]
ok cool, that means that /usr/lib was not in your path ? You should add a symlink from /usr/lib/java/bin/java to /usr/bin/java

If it's good, can you close your issue ?

**Comment by jinlongwang** [comment]
OK!
