### ISSUE TITLE
UID length documentation error?

### ISSUE THREAD

**Issue by johnwhumphreys** [OpenTSDB/opentsdb#1044]
This from the writing data page:

> If you desperately need more than 16 million values, you can increase the number of bytes that OpenTSDB uses to encode UIDs from 3 bytes up to a maximum of 8 bytes. This change would require modifying the value in source code, recompiling, deploying your customized code to all TSDs which will access this data, and maintaining this customization across all future patches and releases.

Seems to contradict this from the documentation page.

> tsd.storage.uid.width.metric (2.2) | Integer | Optional | The width, in bytes, of metric UIDs. WARNING Do not change after writing data to HBase or you will corrupt your tables and not be able to query any more.
> -- | -- | -- | --

Unless I'm miss-understanding how the configuration item is use.

**Comment by manolama** [comment]
Ah good catch. Since it is now a config param we can update the docs. I'll do that now.

**Comment by manolama** [comment]
Updated the docs in b0aba634aaee1bb8b1276ffc01544e526ea0ce48, thanks!
