### ISSUE TITLE
Create a calcite adapter 

### ISSUE THREAD

**Issue by IDerr** [OpenTSDB/opentsdb#1045]
Hi everyone,
I was wondering if it would be great to create a calcite adapter for OpenTSDB to provide SQL.
It doesn't seem really complicated (check druid adapter), but I think it would be a great improvement over the query model.

Thanks a lot.
refs:
https://github.com/apache/calcite/tree/master/druid/src/main/java/org/apache/calcite/adapter/druid
https://calcite.apache.org/

**Comment by manolama** [comment]
I still don't like SQL for time series data but I'm all for it and we have a number of users who would like to see it.
