### ISSUE TITLE
Java IDE friendlier

### ISSUE THREAD

**Issue by t15k** [OpenTSDB/opentsdb#1052]
Hi OpenTSDB.

A quick question. Would you be open to a pull request, reordering the layout of the src files in the a Maven standard layout, to make it more out-the-box Java IDE friendly. Perhaps also allowing Maven or Graddle builds?

**Comment by manolama** [comment]
Hiya, we are moving to straight maven in 3.0 with the standard layout.

For now you can run ``build.sh pom.xml`` to generate a POM file, then import it as a maven project.

**Comment by t15k** [comment]
Thanks that made it a lot easier to setup. Sounds great with it becoming the standard in 3.0.
I guess you'd like 2.4 out there first. And it seems there like there's a few cards on the todo list to get there. Any way I can help out? Is expected that all the feature requests will go in there?

**Comment by IDerr** [comment]
Hi @t15k
if your question has been answered can you close this issue please ?

Thanks

**Comment by t15k** [comment]
Of course.
