### ISSUE TITLE
How to do health checking (kubernetes deployment) when running in "write only" mode ?

### ISSUE THREAD

**Issue by fabito** [OpenTSDB/opentsdb#1059]
I'm deploying OpenTSDB in a Kubernetes cluster and need to define liveness and readiness probes.
In WO mode only `/api/put` (telnet and http) is enabled.
Any ideas on how could I use it for health checking ? 
Maybe sending the same data point for a "healthcheck" metric over and over?

**Comment by manolama** [comment]
Fixed in 2.4: 84b77c567e6bd6fd2c8a572e10ed5d1513961b94
