### ISSUE TITLE
Use pac4j for auth

### ISSUE THREAD

**Issue by IDerr** [OpenTSDB/opentsdb#1060]
Hi,
I don't know if it is possible to reuse some classes of pac4j : https://github.com/pac4j/pac4j
for the authentication + authorization : https://github.com/OpenTSDB/opentsdb/issues/501

Thanks for your work

IDerr

**Comment by johann8384** [comment]
Well, there are a few things that need to happen here. 1, the authorization framework doesn't really exist yet, but what I'm planning to do is add the support for RPC endpoints and other functionality to require a role or permission, and then for that required role or permission to be passed back to the authentication plugin to determine if the current user meets that requirement. So you'd need to write a pac4j authentication plugin once that is complete.

I'm working with Apache Shiro on other projects and will probably try to whip together a Shiro plugin for OpenTSDB.

**Comment by IDerr** [comment]
Yeah, it'll be a lot easier to implement pac4j instead of reimplement each auth protocol.

Keep me in touch :)

**Comment by johann8384** [comment]
#1140 finally has passing tests and implements the needed authentication framework to start this
