### ISSUE TITLE
opentsdb 2.4.0 RC1 exists nowhere

### ISSUE THREAD

**Issue by churrodog** [OpenTSDB/opentsdb#1068]
The link from http://opentsdb.net/ has a link to 2.4.0 RC1 which doesn't point to a valid RC.

**Comment by IDerr** [comment]
Like said, in https://github.com/OpenTSDB/opentsdb/issues/1047
The 2.4 release has been removed because of an issue.
But, @manolama should remove the RC link from the website.

(You can close this @manolama )

**Comment by IDerr** [comment]
Hi @churrodog,
could you please close this issue, if you have been answered ?

Thanks a lot :)
