### ISSUE TITLE
Remove jdk 6,7 from init.d script

### ISSUE THREAD

**Issue by IDerr** [OpenTSDB/opentsdb#1069]
Hi,
since, JDK 6 and 7 are deprecated, we should remove their references. @manolama 
https://github.com/OpenTSDB/opentsdb/blob/8feeb581bd80521dabb87d4be5ace7c785921d3b/build-aux/deb/init.d/opentsdb#L31-L37

Thanks for your work

**Comment by manolama** [comment]
I definitely want to keep 7 as a number of users are still on it (unfortunately) but we can get rid of 6 for 2.4.
