### ISSUE TITLE
Question: are delete queries issued via HTTP asynchronous?

### ISSUE THREAD

**Issue by igstan** [OpenTSDB/opentsdb#1072]
I'm referring to the same kind of asynchrony that appears when PUT-ing data, which prompted the introduction of the `sync` query string param, that allows users to make those requests synchronous. Can the same be done for DELETE queries?

**Comment by IDerr** [comment]
It appears so 👍 
https://github.com/OpenTSDB/opentsdb/blob/8feeb581bd80521dabb87d4be5ace7c785921d3b/src/core/TSDB.java#L1599-1602

**Comment by igstan** [comment]
Thanks, as far as I can see only PUT requests can be run synchronously.

**Comment by IDerr** [comment]
It seems so :)

If your question has been answered, can you close this issue ?

Thanks a lot :)
