### ISSUE TITLE
Java Exception in conjunction with Cloudera?

### ISSUE THREAD

**Issue by valexandersaulys** [OpenTSDB/opentsdb#1082]
I'm running [the quickstart VM via VirtualBox](https://www.cloudera.com/downloads/quickstart_vms/5-12.html) and I get this error after following all the instructions.

```
Exception in thread "main" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at org.hbase.async.HBaseClient.flush(HBaseClient.java:811)
	at org.hbase.async.HBaseClient.shutdown(HBaseClient.java:1061)
	at net.opentsdb.core.TSDB$1HClientShutdown.call(TSDB.java:1665)
	at net.opentsdb.core.TSDB$1HClientShutdown.call(TSDB.java:1660)
	at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
	at com.stumbleupon.async.Deferred.addCallbacks(Deferred.java:688)
	at com.stumbleupon.async.Deferred.addCallbackDeferring(Deferred.java:738)
	at net.opentsdb.core.TSDB.shutdown(TSDB.java:1744)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:233)

```

Am I missing something obvious? Cloudera shows that all the services are up, including HBase.

**Comment by lfblue** [comment]
which version of java do u have?

**Comment by valexandersaulys** [comment]
```
[cloudera@quickstart ~]$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
 ```

This was recommended on the website as a VM to install on [in the quickstart tutorial](http://opentsdb.net/docs/build/html/installation.html). I know there was an issue with some versions of java, [link here](https://groups.google.com/forum/#!topic/opentsdb/J3rtiPFUZ3c), but it appeared to be solved? 

If its not, then should I not bother using Cloudera's quickstart VM? I suggest removing it off the site in that case as a suggestion.

**Comment by mnottheone** [comment]
Had similar issue. Tried using jdk1.8 , and it works. 

For explanation : java.lang.NoSuchMethodError indicates you are unable to find some function whish usually happens there is some incompatibility with dependency version. 

Here you are having incompatibility for keyset() in java.util.concurrent.ConcurrentHashMap class i.e., in code 
 ```
class ConcurrentHashMap {
     :
 public keySetView keyset(){
      : 
}
}
```
which is part of your jvm and so dependent on your java version. Java 1.7 doesn't seems to have keyset() with same signature but jdk 1.8 has, verified myself. So, simply ensure java version to be 1.8* and it should work.

**Comment by johann8384** [comment]
We can update the website also, I don't see any reason to use their VM as a
quick start anymore. Setting up stand-alone HBase is much easier than it
used to ve, especially with things like Docker.

**Comment by valexandersaulys** [comment]
Thank you all for the help! I'll upgrade the JVM and use the stand-alone HBase instead.
