### ISSUE TITLE
How to migrate data from no salting table 

### ISSUE THREAD

**Issue by chenghao2262** [OpenTSDB/opentsdb#1096]
About a week ago, I appended a salting byte for opentsdb, so I use an other tsdb table named tsdb-salt. 
I just want to migrate the old data from old table to new table.
How can I do to achieve it？
I have written a process to scan，add salting byte and put into new table.
However，I can't read or query the old data from opentsdb.

**Comment by Jeadren** [comment]
你好，我跟你遇到同样的问题，你现在迁移成功了吗？可以分享一下吗

**Comment by chenghao2262** [comment]
迁移成功了，你可以按照regionserver进行分布式迁移，当然会影响一定的hbase 使用性能
