### ISSUE TITLE
opentsdb default encode charset and UID hash collision 

### ISSUE THREAD

**Issue by huainansto** [OpenTSDB/opentsdb#1105]
OPENTSDB default encode charset is ISO-8859-1， when deal with Chinese characters, will get messy code, need change default encode charset to UTF-8。
We often encounter the following cases
Caused by: java.lang.IllegalStateException: id=[-75, -68, -116, -12, -81, -39, -58] => name='X', already mapped to 'Y'
The reason is ConcurrentHashMap instance 'id_cache' hash collision in file 'UniqueId.java'

**Comment by IDerr** [comment]
Is is possible to translate in english ?

Thanks :D

**Comment by huainansto** [comment]
1. OPENTSDB default encode charset is ISO-8859-1， when deal with Chinese characters,  will get messy code, need change default encode charset to UTF-8。
2. We often encounter the following cases
Caused by: java.lang.IllegalStateException: id=[-75, -68, -116, -12, -81, -39, -58] => name='X', already mapped to 'Y'
The reason is ConcurrentHashMap instance 'id_cache' hash collision in file 'UniqueId.java'

**Comment by IDerr** [comment]
Thanks :)

**Comment by Tony86Yan** [comment]
Default charset change to utf-8, also got this problem…

**Comment by manolama** [comment]
Right 3.0 supports UTF-8 now but older versions need a bunch of code changes for UTF-8 support and you have to truncate the UID and data tables when you make such a change.
