### ISSUE TITLE
Post to .../api/query gets "stuck"

### ISSUE THREAD

**Issue by MarkLavinAtUtopusInsights** [OpenTSDB/opentsdb#1110]
I've noticed on a number of occasions that when I issue an openTSDB query by posting to a URL .../api/query that the query never returns and it appears to be "stuck" in the openTSDB server.   It seems related to the size of the returned results.     Might this be due to a problem in the openTSDB server (e.g., quietly thrashing to death as a result of running low on memory)?   Is there anything I can look at in the openTSDB log that might provide some insights as to what's going wrong.

**Comment by MarkLavinAtUtopusInsights** [comment]
@manolama, sorry I forgot to tag you on first comment in this issue.

**Comment by johnewing1** [comment]
If you enable query logging, it's very useful for analysing what's going on with your queries

http://opentsdb.net/docs/build/html/user_guide/logging.html

The stats section includes lots of information about rows scanned vs returned and how many datapoints  each query returned. It also has a breakdown of the time spent in each part of the query process.
