### ISSUE TITLE
ERROR [HBaseClient.processResult] -The znode for the -ROOT- region doesn't exits!

### ISSUE THREAD

**Issue by drinktea** [OpenTSDB/opentsdb#1111]
when using "Service opentsdb start" command to start opentsdb, I got this error:ERROR [HBaseClient.processResult] -The znode for the -ROOT- region doesn't exits!

I use hbase1.*.   Doesn't Hbase 1.* later version have -Root region ? why i got this kind of error ?

**Comment by johann8384** [comment]
That sounds like you have the wrong path for Hbase within Zookeeper in your OpenTSDB config.

**Comment by gsocgsoc** [comment]
Check that your package manager didn't overwrite your old config.
