### ISSUE TITLE
Java client returns data points for one hour instead of time range

### ISSUE THREAD

**Issue by pinglot** [OpenTSDB/opentsdb#1117]
I'm trying to use Java Client to connect to Open TSDB. 
Data retrieval looks like this (similar to example in the repository):

TSQuery tsQuery = new TSQuery();
        tsQuery.setStart(Long.toString(from));
        tsQuery.setEnd(Long.toString(to));
        final TSSubQuery subQuery = new TSSubQuery();
        subQuery.setMetric(myMetric);
        subQuery.setAggregator("sum");
        final ArrayList<TSSubQuery> subQueries = new ArrayList<>(1);
        subQueries.add(subQuery);
        tsQuery.setQueries(subQueries);
        tsQuery.setMsResolution(true);
        tsQuery.validateAndSetQuery();
        Query[] queries = tsQuery.buildQueries(tsdb);
        Query query = queries[0];
        DataPoints[] dataPoints = query.run();

However I receive data points for the whole hour instaed of the given time range specified by from and to variables. The same query executed through HTTP API works fine. I have some unit tests and they pass every hour, when there's no data already saved in tsdb for given metric.

Is it recommended to use Java API or HTTP API? The JAVA one seems to be much faster.

**Comment by johann8384** [comment]
This happens for two reasons, one, HBase returns the data for one hour because the data a compactd into hour rowkeys.

Additionally, ths behavior is desired because in order to do interpolation you need data from before your desired time range.

Just discard the extra data.

**Comment by pinglot** [comment]
Thanks for your reply.
HTTP API used to work the same way as you describe, however recently they've changed its behaviour to return data exactly for the requested period. I think the same should be the case with JAVA API, unless otherwise documented or unless the explicit possibility to set the time range with is replaced.

**Comment by johann8384** [comment]
Well, the HTTP Api  just throws away the extra data, and in this case, it isnt a Java API so much as rhe internal classes made public.
