### ISSUE TITLE
[OpenTSDB 2.4.0RC2]Rollup query can't use 'end' to limit the result range

### ISSUE THREAD

**Issue by dumbsparrow** [OpenTSDB/opentsdb#1125]
I've tried the openTSDB 2.4.0RC2 on HBase-1.2.6. I enabled the rollup feature and put next rollup data points into database:
_[{
	"metric": "sys.mem",
    "timestamp": 1514768400000,
    "value": 1,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "SUM"
},
{
	"metric": "sys.mem",
    "timestamp": 1514772000000,
    "value": 2,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "SUM"
},
{
	"metric": "sys.mem",
    "timestamp": 1514775600000,
    "value": 3,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "SUM"
}
]_
Then I tried the next query on HTTP API /api/query:
  _{
    "start": "1514768400000",
    "end": "now",
    "queries": [
      {
        "aggregator": "sum",
        "metric": "sys.mem",
        "tsuids": null,
        "downsample": "3600s-sum",
        "rate": false,
        "filters": [
          {
            "tagk": "host",
            "filter": "host = 'web01' and dc = 'lga'",
            "group_by": false,
            "type": "expr"
          }
        ]
      }
    ],
    "msResolution": true
  }_
The results are like below:
_[
    {
        "metric": "sys.mem",
        "tags": {
            "host": "web01",
            "dc": "lga"
        },
        "aggregateTags": [],
        "dps": {
            "1514768400000": 1,
            "1514772000000": 2,
            "1514775600000": 3
        }
    }
]_
But if I tried to set the end time like the last time, it won't give me the right answer:
  _{
    "start": "1514768400000",
    "end": "1514775600000",
    "queries": [
      {
        "aggregator": "sum",
        "metric": "sys.mem",
        "tsuids": null,
        "downsample": "3600s-sum",
        "rate": false,
        "filters": [
          {
            "tagk": "host",
            "filter": "host = 'web01' and dc = 'lga'",
            "group_by": false,
            "type": "expr"
          }
        ]
      }
    ],
    "msResolution": true
  }_
The results is empty. I think it's a bug for range search on rollup.

**Comment by icence** [comment]
I have the same problem. I only get result if I set end time be a large number.

**Comment by icence** [comment]
(code)[https://github.com/OpenTSDB/opentsdb/blob/v2.4.0RC2/src/core/TsdbQuery.java#L1400-L1406]
I find out something wrong with config "use_otsdb_timestamp", I now set it to be false to work around this issue.

**Comment by dumbsparrow** [comment]
Yes, that maybe works. But I think it affects the normal query process.

**Comment by manolama** [comment]
Fixed in b95172b5e00893fd30d60920ee8ad93228a3130f and disabled the date tiered compaction by default.
