### ISSUE TITLE
How to make loading data faster from opentsdb

### ISSUE THREAD

**Issue by nch14** [OpenTSDB/opentsdb#1130]
Is there any plan to make this?
Or is there any guides?
Recently we planned to implement a opentsdb-client directly to HBase, but i wonder if it really works.

**Comment by johann8384** [comment]
Well, querying data can be faster or slower depending on how you setup your cluster, what types of queries you are sending, how you structured your metrics, etc.

Maybe you can provide some more information about what you're doing, what results your seeing, and then someone can assist you with suggesting how to improve the performance you are seeing. 

This seems like a good question for the mailing list.

https://groups.google.com/forum/#!forum/opentsdb
