### ISSUE TITLE
No such name for 'metrics'

### ISSUE THREAD

**Issue by jyzhangbo** [OpenTSDB/opentsdb#1138]
Hi!
I use opentsdb to storage the metrics of device, the device has thousands of metrics.
I want to query all the metrics,so the queries contain many metrics.
Probably one metric never upload data,so the result will be error,the message is "No such name for 'metrics': 'UES.Eoutput'".
I want the result has data of other metric,not the error.
The opentsdb version is 2.3.

**Comment by manolama** [comment]
Hi, this is by design and we can address it in 2.5 with a flag to ignore missing metrics. Thanks.

**Comment by mindflying** [comment]
> Hi, this is by design and we can address it in 2.5 with a flag to ignore missing metrics. Thanks.

@manolama Hi, is this feature finished in lastest version `OpenTSDB 2.4.1`
