### ISSUE TITLE
Need to test tsdb functions

### ISSUE THREAD

**Issue by vyshaliN** [OpenTSDB/opentsdb#1180]
I was looking through the test cases written for the repository and was trying to reproduce it.I was also trying to create a tsdb with mocked client and UID assignments.But I was not able to import net.opentsdb.storage.Mockbase though I have imported net.opentsdb maven dependency

**Comment by manolama** [comment]
Since MockBase is in the tests folder we have to allow exporting the test jar. This is fixed now in: c1fe5f347a34e7bfd34d075e4bd3c3281059d746. Thanks!
