### ISSUE TITLE
Switch to HTML5 doctype

### ISSUE THREAD

**Issue by tsuna** [OpenTSDB/opentsdb#12]
Right now the TSD uses this doctype:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">`
It should instead be changed to use the HTML5 doctype:
`<!DOCTYPE html>`

**Comment by kaustubhmallik** [comment]
Is this issue still open? I want to take this.

**Comment by IDerr** [comment]
It seems to be resolved no ?

**Comment by IDerr** [comment]
![](http://i.imgur.com/prnBwaw.png)

Seems already fixed 

@manolama You can close this

**Comment by IDerr** [comment]
or @johann8384

**Comment by IDerr** [comment]
Any news on closing this ? @manolama @johann8384

**Comment by manolama** [comment]
Thanks @IDerr It's still an issue that's a simple patch. Somewhere in the HttpRequest code I think.

**Comment by manolama** [comment]
Pushed in f371ba02ba296125b334cb45b0d210e3f5dd3a1a on next.
