### ISSUE TITLE
the problem of  aggregator parameter send to /api/query

### ISSUE THREAD

**Issue by LynnYuanInspur** [OpenTSDB/opentsdb#1210]
the raw data is:
{"metric":"temperature","ts":1526604334000,"tags": {"city":"Bj"}, "value":21}
{"metric":"temperature","ts":1526604334147,"tags": {"city":"Bj"}, "value":19}
{"metric":"temperature",,"ts":1526604335047,"tags": {"city":"Bj"}, "value":20}
{"metric":"temperature","ts":1526604335247,"tags": {"city":"Bj"}, "value":18}
{"metric":"temperature",,"ts":1526604356047,"tags": {"city":"Bj"}, "value":22}
add datetime field is:
{"metric":"temperature","datetime":"2018-05-18 08:45:34.000","ts":1526604334000,"tags": {"city":"Bj"}, "value":21}
{"metric":"temperature","datetime":"2018-05-18 08:45:34.147","ts":1526604334147,"tags": {"city":"Bj"}, "value":19}
{"metric":"temperature","datetime":"2018-05-18 08:45:35.047","ts":1526604335047,"tags": {"city":"Bj"}, "value":20}
{"metric":"temperature","datetime":"2018-05-18 08:45:35.247","ts":1526604335247,"tags": {"city":"Bj"}, "value":18}
{"metric":"temperature","datetime":"2018-05-18 08:45:56.047","ts":1526604356047,"tags": {"city":"Bj"}, "value":22}

when call /api/query send the follow json:
{
	"start":"1h-ago",
	"queries":[
		{
			"metric":"temperature",
			"aggregator":"sum"
		}
	]
}
**the result:**
[
	{
		"metric":"temperature",
		"dps":{
			"1526604335":18,
			"1526604334":19,
			"1526604356":22
		},
		"aggregateTags":[],
		"tags":{
			"city":"Bj"
		}
	}
]
or send json:
{
	"start":"1h-ago",
	"queries":[
		{
			"metric":"temperature",
			"aggregator":"avg"
		}
	]
}
**result:**
[
	{
		"metric":"temperature",
		"dps":{
			"1526604335":18,
			"1526604334":19,
			"1526604356":22
		},
		"aggregateTags":[],
		"tags":{
			"city":"Bj"
		}
	}
]

as the document
http://opentsdb.net/docs/build/html/user_guide/query/index.html
![image](https://user-images.githubusercontent.com/11604685/40211994-4f901bae-5a80-11e8-81cf-07ba025fe946.png)
Is it a bug?

**Comment by manolama** [comment]
Thank you for finding that. It *is* a bug in that I never implemented the downsampling code. Let me see if I can get that done easily.

**Comment by manolama** [comment]
This one won't be easy so I'll fix the docs and in them mean time, add a 1s downsampler to your queries if you can.

**Comment by manolama** [comment]
Updated, thanks.
