### ISSUE TITLE
2.3.1 release tarball?

### ISSUE THREAD

**Issue by ilovezfs** [OpenTSDB/opentsdb#1215]
There is a GitHub source archive tarball
https://github.com/OpenTSDB/opentsdb/archive/v2.3.1.tar.gz

but no release tarball like the one for 2.3.0
https://github.com/OpenTSDB/opentsdb/releases/download/v2.3.0/opentsdb-2.3.0.tar.gz

**Comment by manolama** [comment]
Just posted it :) Sorry for the wait, had to fix certs on an ancient VM to pull from Git.

**Comment by ilovezfs** [comment]
Thanks @manolama!
