### ISSUE TITLE
Unable to send data to opentsdb?

### ISSUE THREAD

**Issue by dineshkumar4728** [OpenTSDB/opentsdb#1257]
HI all,
            I have installed openTSDB in cloudera quick start vm . with the help of this site[https://medium.com/@zshao/15-min-getting-started-guide-for-opentsdb-44b81341f54e] evertyhing is working fine but but when i try to send data to opentsdb i am getting some errors .when i am enter this command

        **sudo echo “stats” | nc 0 4242 | awk ‘{print “put “$0;}’ | nc 0 4242**

and I get below -
 
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.connections’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.connections’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.connections’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.connectionmgr.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.received’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.received’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.received’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_50pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_75pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_90pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_95pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_50pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_75pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_90pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_95pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_50pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_75pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_90pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.latency_95pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.graph.requests’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.graph.requests’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.received’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.rpc.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.query.invalid_requests’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.query.exceptions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.http.query.success’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.states’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.thread.count’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-hit’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-miss’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-size’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.random-collisions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.rejected-assignments’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-used’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-available’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-hit’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-miss’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-size’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.random-collisions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.rejected-assignments’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-used’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-available’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-hit’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-miss’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.cache-size’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.random-collisions’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.rejected-assignments’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-used’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.ids-available’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.filter.rejected’
put: unknown metric: No such name for ‘metrics’: ‘tsd.uid.filter.rejected’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.ramfree’
put: unknown metric: No such name for ‘metrics’: ‘tsd.jvm.ramused’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_50pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_75pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_90pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_95pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.datapoints.added’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_50pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_75pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_90pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.latency_95pct’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.root_lookups’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.meta_lookups’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.meta_lookups’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.rpcs.batched’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.flushes’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.connections.created’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.connections.idle_closed’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.nsre’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.nsre.rpcs_delayed’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.region_clients.open’
put: unknown metric: No such name for ‘metrics’: ‘tsd.hbase.region_clients.idle_closed’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.count’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.duplicates’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.duplicates’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.queue.size’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.errors’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.writes’
put: unknown metric: No such name for ‘metrics’: ‘tsd.compaction.deletes’

what i need to change ?can you suggest how to overcome this?

Thank you

**Comment by johnhomsea** [comment]
I think maybe you didn't configure the following keys in  your conf?  
 tsd.core.auto_create_metrics=true
tsd.core.auto_create_tagks=true
tsd.core.auto_create_tagvs=true
tsd.storage.fix_duplicates=true

**Comment by dineshkumar4728** [comment]
hi @johnhomsea ,
                               Thanks for the reply , in my config file i am only  able to see **tsd.core.auto_create_metrics=true** only remaining tow i am unable to see in my config file ,can u please help on this how to overcome?
Thanks

**Comment by dineshkumar4728** [comment]
after restart the tcollector ,everything works fine

Thanks

**Comment by sahil16897** [comment]
Can u please tell how to restart tcollector
