### ISSUE TITLE
/tools/clean_cache.sh

### ISSUE THREAD

**Issue by myg821561935** [OpenTSDB/opentsdb#1268]
in this scripts,"find . -x" will cause an error in centos.
the err is : 
           find: unknown predicate `-x'
i modify it with  find . -type f -exec ,is this better?
![clean_cache](https://user-images.githubusercontent.com/5190099/42883675-d64c2998-8ace-11e8-9d70-39c92a9a471f.png)

**Comment by manolama** [comment]
Merged in 1f93070a34fa4ee89eac621a8be1d80357c80412. Thanks!
