### ISSUE TITLE
build 2.3.1 failed in mac osx

### ISSUE THREAD

**Issue by zuzeep** [OpenTSDB/opentsdb#1284]
I use `wget https://github.com/OpenTSDB/opentsdb/releases/download/v2.3.1/opentsdb-2.3.1.tar.gz` command to get codes.
Then tar it and run `./build.sh`, it report the error:
javac: file not found: ./src/net/opentsdb/query/expression/parser/*.java
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [.javac-stamp] Error 2
make: *** [all] Error 2

**Comment by MrKingHH** [comment]
can u tell me how do u solve this problem? i have encountered this problem too...

**Comment by MrKingHH** [comment]
@zuzeep
