### ISSUE TITLE
'format' argument not work in url

### ISSUE THREAD

**Issue by whitelilis** [OpenTSDB/opentsdb#1299]
For example:  http://10.10.2.61:8484/#start=2018/08/07-16:18:57&m=sum:proc.meminfo.anonpages%7Bhost=611.slave.adh%7D&o=axis%20x1y2&m=sum:proc.meminfo.memtotal%7Bhost=611.slave.adh%7D&o=axis%20x1y2&m=sum:rate:proc.net.bytes%7Bdirection=*,host=611.slave.adh,iface=em1%7D&o=&yformat=%25b%20%25B&yrange=%5B0:%5D&y2range=%5B0:%5D&key=out%20center%20top%20box&wxh=1260x580&style=linespoint&autoreload=15

get nothing, but without the 'format' option,  http://10.10.2.61:8484/#start=2018/08/07-16:18:57&m=sum:proc.meminfo.anonpages%7Bhost=611.slave.adh%7D&o=axis%20x1y2&m=sum:proc.meminfo.memtotal%7Bhost=611.slave.adh%7D&o=axis%20x1y2&m=sum:rate:proc.net.bytes%7Bdirection=*,host=611.slave.adh,iface=em1%7D&o=&yrange=%5B0:%5D&y2range=%5B0:%5D&key=out%20center%20top%20box&wxh=1260x580&style=linespoint&autoreload=15
work fine.

**Comment by whitelilis** [comment]
I have made a  PR  https://github.com/OpenTSDB/opentsdb/pull/1304

**Comment by manolama** [comment]
Merged in dc315037db3015df767f6abf0e8ec9adc614ce00, thanks!
