### ISSUE TITLE
opentsdb does not handle daylight savings switch

### ISSUE THREAD

**Issue by victorjerlin** [OpenTSDB/opentsdb#130]
After switching from CEST(Central European Summer Time) to CET this Sunday, the graphs presented from opentsdb were still showing them as it were CEST.  (i.e. values collected 10.50 CET were being displayed as 11:50 in the graph)

A restart of tsd fixed this, and moved the values previously displayed at 11.50 back to 10.50.

**Comment by kaustubhmallik** [comment]
Is this still open?
