### ISSUE TITLE
2.4  Rolled-up Pre-Aggregates cannot query the results

### ISSUE THREAD

**Issue by yujimoyouran** [OpenTSDB/opentsdb#1308]
I have to query the condition：{
	"start": 1532707200,
	"noAnnotations":true,
	"globalAnnotations":true,
	"queries": [{
			"aggregator": "sum",
			"metric": "sys.sum.nice",
			"preAggregate":"true",
			"rollupUsage":"ROLLUP_NOFALLBACK",
			"tags": {
				"host": "host12",
				"dc": "lga2"
			}
		}
	]
}
There's data in hbase，
tsdb                                                                                                                                                                                           
tsdb-agg                                                                                                                                                                                       
tsdb-meta                                                                                                                                                                                      
tsdb-preagg                                                                                                                                                                                    
tsdb-rollup-1d                                                                                                                                                                                 
tsdb-rollup-1h                                                                                                                                                                                 
tsdb-rollup-agg-1d                                                                                                                                                                             
tsdb-rollup-agg-1h                                                                                                                                                                             
tsdb-tree                                                                                                                                                                                      
tsdb-uid ，
But the query result is always []，
Can you give me a hand? thank you!

**Comment by zhenghong-you** [comment]
Same issue here, anyone know the solution?
