### ISSUE TITLE
Which official tsdb branch or release supports api/histogram endpoint

### ISSUE THREAD

**Issue by dilipdevaraj-sfdc** [OpenTSDB/opentsdb#1320]
I am looking to store histogram data using tsdb.
I see from docs http://opentsdb.net/docs/build/html/api_http/histogram.html , this is available with OpenTSDB 2.4.

However when I look at TSDB official release https://github.com/OpenTSDB/opentsdb/releases the last one I see is https://github.com/OpenTSDB/opentsdb/releases/tag/v2.3.1
But I do not find /api/histogram endpoint

When will the next version of TSDB supporting /api/histogram endpoint be released ?  I also do not see it listed in master branch https://github.com/OpenTSDB/opentsdb/blob/master/src/tsd/RpcManager.java

Is there any way I can leverage this by making simple tweaks in source code while we wait for official release of this ?

**Comment by manolama** [comment]
Right we don't have an official release yet. It's in the `next` branch which is 2.4. Trying to get it out ASAP.
