### ISSUE TITLE
Unable to build 3.0 branch of opentsdb

### ISSUE THREAD

**Issue by dilipdevaraj-sfdc** [OpenTSDB/opentsdb#1321]
Did a git clone and then checkout 3.0 branch
Tried running ./build.sh on mac as well as linux box but  I get message

                                 Dload  Upload   Total   Spent    Left  Speed
100  1091    0  1091    0     0   3107      0 --:--:-- --:--:-- --:--:--  3108
error: invalid checksum for third_party/hbase/asynchbase-2.0.0-20161025.204140-1.jar
error: expected: 01d497e9391a9be1c0c319574bbc02ca
error:    found: ab1f7b66398f4da763f527d9654d44d2
make: *** [third_party/hbase/asynchbase-2.0.0-20161025.204140-1.jar] Error 1

**Comment by manolama** [comment]
Ah sorry it's all maven for 3.0 now, just run mvn install. I'll yank out the old build script.
