### ISSUE TITLE
Unable to build next branch of opentsdb

### ISSUE THREAD

**Issue by dilipdevaraj-sfdc** [OpenTSDB/opentsdb#1322]
Did a git clone and then checkout next branch
Tried running ./build.sh on mac as well as linux box but  I get message

../src/tsd/QueryRpc.java:430: warning: [deprecation] getLastPoint(TSDB,byte[],boolean,int,long) in TSUIDQuery has been deprecated
          deferreds.add(TSUIDQuery.getLastPoint(tsdb, entry.getKey(), 
                                  ^
../src/tsd/GraphHandler.java:211: warning: [rawtypes] found raw type: HashSet
    final HashSet<String>[] aggregated_tags = new HashSet[nqueries];
                                                  ^
  missing type arguments for generic class HashSet<E>
  where E is a type-variable:
    E extends Object declared in class HashSet
../src/tsd/PutDataPointRpc.java:841: error: cannot find symbol
          if ((authorization.hasPermission(authState, Permissions.TELNET_PUT).getStatus() != AuthState.AuthStatus.SUCCESS)) {
                                                      ^
  symbol:   variable Permissions
  location: class PutDataPointRpc
../src/tsd/PutDataPointRpc.java:866: error: cannot find symbol
          if ((authorization.hasPermission(authState, Permissions.TELNET_PUT).getStatus() != AuthState.AuthStatus.SUCCESS)) {
                                                      ^
  symbol:   variable Permissions
  location: class PutDataPointRpc
../src/tsd/LogsRpc.java:115: warning: [cast] redundant cast to ILoggingEvent
        final ILoggingEvent event = (ILoggingEvent) logbuf.get(nevents);
                                    ^
../src/tsd/QueryExecutor.java:854: warning: [rawtypes] found raw type: Map
      tags = new Map[dps.length];
                 ^
  missing type arguments for generic class Map<K,V>
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
../src/tsd/QueryExecutor.java:855: warning: [rawtypes] found raw type: List
      agg_tags = new List[dps.length];
                     ^
  missing type arguments for generic class List<E>
  where E is a type-variable:
    E extends Object declared in interface List
../src/utils/JSON.java:214: warning: [deprecation] createJsonParser(String) in JsonFactory has been deprecated
      return jsonMapper.getFactory().createJsonParser(json);
                                    ^
../src/utils/JSON.java:236: warning: [deprecation] createJsonParser(byte[]) in JsonFactory has been deprecated
      return jsonMapper.getFactory().createJsonParser(json);
                                    ^
../src/utils/JSON.java:258: warning: [deprecation] createJsonParser(InputStream) in JsonFactory has been deprecated
      return jsonMapper.getFactory().createJsonParser(json);
                                    ^
../src/utils/PluginLoader.java:70: warning: [rawtypes] found raw type: Class
  private static final Class<?>[] PARAMETER_TYPES = new Class[] {
                                                        ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
./src/net/opentsdb/query/expression/parser/TokenMgrError.java:110: warning: [cast] redundant cast to int
          (EOFSeen ? "<EOF> " : ("\"" + addEscapes(String.valueOf(curChar1)) + "\"") + " (" + (int)curChar + "), ") +
                                                                                              ^
4 errors
54 warnings
make[1]: *** [.javac-stamp] Error 1
make: *** [all] Error 2

**Comment by grkarthik** [comment]
Even I faced the same issue, can someone please help here.

**Comment by johann8384** [comment]
That would be my code most likely, I'll check it and fix the branch :-/

On Mon, Sep 10, 2018 at 4:20 PM, dilipdevaraj-sfdc <notifications@github.com

**Comment by manolama** [comment]
We fixed it at some point. Builds good now.
