### ISSUE TITLE
BatchedDataPoints cannot persist in 2.4.0RC1

### ISSUE THREAD

**Issue by kennethleider** [OpenTSDB/opentsdb#1436]
public Deferred<Object> persist() {
    final byte[] q = Arrays.copyOfRange(batched_qualifier, 0, qualifier_index);
    final byte[] v = Arrays.copyOfRange(batched_value, 0, value_index);
    final byte[] r = Arrays.copyOfRange(row_key, 0, row_key.length);
    reset();
    return tsdb.put(r, q, v, base_time);
  }

The call to "reset" set "base_time=Long.MIN_VALUE".  This causes the tsdb.put operation to fail.  I think you need to save "base_time" in a local variable before the call to reset.

**Comment by manolama** [comment]
Fixed in a9c735b97241205aa8d62ff69895ba183d4e8a06, thanks!
