### ISSUE TITLE
OpenTSDB cannot read historical data from HBase

### ISSUE THREAD

**Issue by xchen9** [OpenTSDB/opentsdb#1536]
OpenTSDB cannot query historical data any more after operations as follows:

1. enterprise level Linux system patching
2. add salting in configuration
tsd.storage.salt.width=1
tsd.storage.salt.buckets = 3

version: Opentsdb2.4 RC2
configuration: one Opentsdb instance is installed in a cluster with 11 HBase region servers

There is no error when querying the data, but historical data prior to the event is not returned - yet still exists in hbase tables.

![image](https://user-images.githubusercontent.com/23622610/52616308-1c57bd00-2ed3-11e9-94af-90bb1bde8b17.png)

**Comment by langerma** [comment]
you cannot add a salting configuration to opentsdb afterwards. you should add that before writing. you will have to  migrate old data.

**Comment by xchen9** [comment]
Thanks @langerma
