### ISSUE TITLE
add "top-n" capabilities

### ISSUE THREAD

**Issue by filippog** [OpenTSDB/opentsdb#154]
Hi,
when dealing with a lot of metrics (esp. tag=*) it'd be nice to be able to say "give me only the top-n entries", main reason being that even with more than an handful of metrics the graph is likely to be cluttered and having an indication of what are the top-n metrics could be useful (e.g. latency graphs to identify outliers)
Not sure how easy it is to implement this however and/or it can be done on hbase side though

**Comment by sglwlb** [comment]
What's the status now, i also need this feature.

**Comment by digrich** [comment]
If we get the support to limit and also define the order (i.e asc, dsc) to the final output of query, we may achieve the "top-n" capability. 

I agree this is a very important feature to have. We collect thousand of metrics from hundreds of servers and if we can plot top-n or worst-n performing servers for any metric, that would be very great.

**Comment by godfreyhe** [comment]
hi @adrien-mogenet , @filippog 

I have meet the same problems, there are so many lines in one graph that I can't read the graph when add host=*. so I had added  "top-n capabilities" in TSD server base on 2.2.0 RC1.

unit now, support top-n, bottom-n, sample-n, above-n, below-n (the last two are threshold-filters)
add filed "limit" in TSQuery, e.g. :  limit=avg:top:10 . When limit is threshold filter, the value N may be negative number, So I choose ":" as separator.

there are my works in the limit function:
1. get the value of the DataPoints in the query result of each by avg/min/max. The query result is like  List<DataPoints[]>>
2. sort by the values
3. filter the DataPoints by the value, N and top/bottom/sample/above/below
at last, add the limit function in the QueriesCB.class before calling formatQueryAsyncV1()

**Comment by sigma420** [comment]
Hi @godfreyhe,

Can you please share ur code which has these changes. Thanks.

**Comment by manolama** [comment]
Hey folks, the engineers at Turn added top-n capabilities with their Graphite style expressions and it's now in the "put" branch, i.e. OpenTSDB 2.3. I'll crank out some docs shortly so if ya'll could start poking the tires I'd appreciate it. Thanks!

**Comment by johann8384** [comment]
http://opentsdb.net/docs/build/html/api_http/query/gexp.html

This can probably be closed now.

**Comment by filippog** [comment]
:+1:

**Comment by pbn04001** [comment]
This doesn't work.  I have tried both highestMax and highestCurrent and the series that is obviously should be the top series is not being returned at all.
This is my query string
/api/query/gexp?start=1468972800&end=1469059200&exp=highestCurrent(none:17m-avg:tr.metrics.netflow.port.count{port=*},40)

**Comment by costimuraru** [comment]
Is this working?

**Comment by johann8384** [comment]
We didn't notice any issues with it, but I haven't explicitly gone to test it. I am not there any more, but if I get an environment setup sometime soon I will try and test it out. So I guess for now the answer is "works on Turn's computer"

**Comment by ace-han** [comment]
Hi, there. I think `/api/query/gexp` is not flexible as `/api/query/exp`. 

For example, I have a metric `mx` and it's made up by `mx=my+mz`. `my` and 'mz' are the raw collecting metrics. How should I get this `highestMax(mx)` using `/api/query/gexp`?
