### ISSUE TITLE
How can i put the string value to the open TSDB?

### ISSUE THREAD

**Issue by victor9309** [OpenTSDB/opentsdb#1564]
url: http://192.168.3.101:4242/api/put?details
json:
 {
 	"timestamp": 1551317746,
 	"metric": 36, 
 	"value": "D_500K",    
 	"tags": {
 		"operationValue": "7a0b5e8f540d",
 		"gateMac": "00E2690CF71D"
 		
 	}
 }
result:
{
    "success": 0,
    "failed": 1,
    "errors": [
        {
            "datapoint": {
                "metric": "36",
                "timestamp": 1551317746,
                "value": "D_500K",
                "tags": {
                    "operationValue": "7a0b5e8f540d",
                    "gateMac": "00E2690CF71D"
                }
            },
            "error": "Unable to parse value to a number"
        }
    ]
}

**Comment by victor9309** [comment]
I wonder if this problem has been solved?

**Comment by langerma** [comment]
i guess you should switch the metric and value thing: metric: "d_500k" value: 36

**Comment by johann8384** [comment]
I don't believe we'll ever support storing string values. It does look like you intended to store the value 36 and the metric d_500k.
