### ISSUE TITLE
Very very slow start or restart time

### ISSUE THREAD

**Issue by GreatSnoopy** [OpenTSDB/opentsdb#1676]
This is as much a question as it may be an issue.
I noticed that on a cluster that accumulated some data, the startup time of opentsdb is very very bad, like 15...20 minutes or more.
I see in the logs records from time to time that look like

 Added client for region RegionInfo(table="tsdb-uid",..... 

I suspect that the issue might be due to the fact that we accumulated data with very very high cardinality. 
Would that be the reason for this slowness in startup? What would be required to optimize the startup time under these conditions?  
Because as it is now, a rolling restart, if required is an absolute pain.
I am also aware that high cardinality data is generally a bad thing for OpenTSDB, but that is an issue that we can improve for new data, but its not quite doable for existing data.

**Comment by johnhomsea** [comment]
Do you mean OpenTSDB query is very slow at the startup time?

**Comment by GreatSnoopy** [comment]
No, opentsdb is not even serving data or listening on its service port. From the moment I launch the service until the moment it says "ready to serve on port 4242" it takes 20 min or more.

**Comment by iondulgheru** [comment]
This also happens to me. I have around 300 milion unique metric names. When opentsdb starts it seems it tries to create the cache for uuid's.
But I don't see any type of load on opentsdb and hbase VM's when this happens. 
Any idea on how to optimise this so it will use the resources available (cpu, ram, disk i/o, network i/o)?

**Comment by iondulgheru** [comment]
This problem is gone if I disable the uid cache preloading (tsd.core.preload_uid_cache).
But I don't understand why the uid cache preloading is so slow, why it doesn't use the cpu or disk i/o. Is there something special about how Opentsdb queries the tsdb-uid table?
