### ISSUE TITLE
Feature request: Combine results from raw and rollup queries

### ISSUE THREAD

**Issue by neilfordyce** [OpenTSDB/opentsdb#1686]
I am working on setting up an OpenTSDB with rollups using version 2.4.   Our use case is largely for near real time alerting (requiring sub one minute latency) but occasionally we want to query several months back on high-ish volume data.  Rollups should offer us a great performance improvement here, so thank you for the work in that area.

We are working on creating a daily batch job to create hourly rollups.  That means there will be a delay of up to one day (plus job runtime) to the rollup data being available.  The delay means that any query served by the rollup table would be missing the latest data which is available in the raw table.

If we were stream processing to produce rollups, we would hit similar issues albeit with a lower latency.  We likely wouldn't want the stream processor sending rollup updates as every new raw data point comes in, so there would be a delay in the stream processor producing data points while the rolled up data point "matures".  That delay would cause a similar issue.

We wondered if it might be a reasonable idea to execute the query with some knowledge of what the latest available timestamps are in the rollup table.  With that knowledge, a rollup query could be split up; populating the majority of data from rollup table, but still fall back to the raw table to create the latest data points, then finally joining both sets of data points together.

Does this seem like a reasonable feature or is it too complicated and we would be better off stream processing to reduce latency and just ignore the latest data point?

**Comment by johnseekins** [comment]
We've found using RPC ingest for rollup tables to be an effective trade-off here. It isn't as heavy as the HTTP endpoint and you get close to realtime ingest for rollups as well as raw data.
We are successful at doing this with Kafka. Basically, our rollups are calculated and pushed to a unique Kafka topic and then written to HBase with the Kakfa-RPC system. Works pretty well.

**Comment by neilfordyce** [comment]
Thanks for the information.  It's great to hear from other people using the rollup features.  We are also using the Kafka RPC plugin.  We don't emit points to the rollup Kafka topic until it's unlikely that there will be any more updates to the rollup data point.  

If we run a rollup query, that delay means we miss the latest data points which are available in the raw table.  I was really wondering if it's worth altering the rollup query behaviour to retrieve those latest data points from the raw table.

**Comment by johnseekins** [comment]
Seems an interesting idea, yeah. Personally, I'd like it. The way downsampling works right now makes it look like you're missing data near "now" on graphs. Which is annoying.

**Comment by neilfordyce** [comment]
Awesome.  Thanks for the feedback.  Hoping to open a PR for that.  Will let you know how it goes.
