### ISSUE TITLE
No finding records in HBASE

### ISSUE THREAD

**Issue by senthilr2k** [OpenTSDB/opentsdb#1731]
Hi ,

  I am using Opentsdb 2.3.1 version. I inserted 50k records on the basis of every record per min. When i ran count 'tsdb' in hbase shell i see only 2k records but when i query in opentsdb ui, i am seeing 50k records. I am guessing that opentsdb is not flushing all the records to HBASE. Please help me to push the records to hbase every 5 mins or so. 

Thanks,
Senthil R

**Comment by johnseekins** [comment]
I assume by records you mean datapoints. HBase stores multiple datapoints per row. A `count` in HBase would naturally return a lower number than counting all the datapoints you inserted.

**Comment by senthilr2k** [comment]
Hi thanks for reply. I was under an assumption that for each metric value timestamp combination there would be a hbase row. Could you please correct/explain a bit here
Thanks,
Senthil R

**Comment by johnseekins** [comment]
The architecture of OpenTSDB storage in HBase is fairly well described in the documentation. But generally, HBase is a columnar store, why _wouldn't_ you store multiple values per row?

To clarify your question, I believe HBase stores 1 hour (based on insertion timestamp) of values per row.

**Comment by johnseekins** [comment]
You could...probably close this ticket if my answers satisfied you.
