### ISSUE TITLE
Cannot build opentsdb version 2.4.0

### ISSUE THREAD

**Issue by pauldj54** [OpenTSDB/opentsdb#1745]
Hi everyone, 
I am trying to build opentsdb version 2.4.0 following the directions on the documentation.

My environment:
- OS: Centos 7
- Java: openjdk version "1.8.0_222"
- GnuPlot 4.6
- Autotools m4 (GNU M4) 1.4.16
- Make --> I installed it using yum groupinstall "Development Tools"
- Python 2.7.5

I tried to build it with
`mvn clean package` 
and for cassandra profile using
`mvn clean package -Pcassandra` 

and I am getting the same errors:

`[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TSDB.java:[45,22] error: cannot find symbol
[ERROR]   symbol:   class TableNotFoundException
  location: package org.hbase.async
/home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[30,45] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/tsd/PutDataPointRpc.java:[33,27] error: package org.apache.zookeeper does not exist
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[30,45] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/MultiGetQuery.java:[41,22] error: cannot find symbol
[ERROR]   symbol:   class GetResultOrException
  location: package org.hbase.async
/home/vagrant/git/opentsdb/src-main/net/opentsdb/core/MultiGetQuery.java:[249,56] error: cannot find symbol
[ERROR]   symbol:   class GetResultOrException
  location: class MultiGetQuery
/home/vagrant/git/opentsdb/src-main/net/opentsdb/core/MultiGetQuery.java:[351,34] error: cannot find symbol
[ERROR]   symbol:   class GetResultOrException
  location: class MultiGetQuery.MulGetCB
/home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TSDB.java:[2092,24] [deprecation] prefetchMeta(byte[]) in HBaseClient has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TSDB.java:[2093,24] [deprecation] prefetchMeta(byte[]) in HBaseClient has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TsdbQuery.java:[589,23] [deprecation] DownsamplingSpecification(long,Aggregator,FillPolicy) in DownsamplingSpecification has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TsdbQuery.java:[1338,28] [deprecation] DownsamplingSpecification(long,Aggregator,FillPolicy) in DownsamplingSpecification has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/TsdbQuery.java:[1711,20] [deprecation] DownsamplingSpecification(long,Aggregator,FillPolicy) in DownsamplingSpecification has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/utils/ByteSet.java:[83,47] [unchecked] unchecked cast
[ERROR]   required: ByteMap<Object>
  found:    Object
/home/vagrant/git/opentsdb/src-main/net/opentsdb/core/Span.java:[501,13] [deprecation] Downsampler(SeekableView,long,Aggregator) in Downsampler has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/Span.java:[505,13] [deprecation] FillingDownsampler(SeekableView,long,long,long,Aggregator,FillPolicy) in FillingDownsampler has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/tsd/AbstractHttpQuery.java:[478,18] [deprecation] toStringHelper(Object) in Objects has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/tsd/QueryRpc.java:[430,34] [deprecation] getLastPoint(TSDB,byte[],boolean,int,long) in TSUIDQuery has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/tools/ConfigArgP.java:[128,56] [deprecation] reader(Class<?>) in ObjectMapper has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/tools/ConfigArgP.java:[825,39] [deprecation] reader(Class<?>) in ObjectMapper has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/utils/JSON.java:[214,36] [deprecation] createJsonParser(String) in JsonFactory has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/utils/JSON.java:[236,36] [deprecation] createJsonParser(byte[]) in JsonFactory has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/utils/JSON.java:[258,36] [deprecation] createJsonParser(InputStream) in JsonFactory has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[341,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[360,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[365,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[370,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/UnionIterator.java:[390,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/graph/Plot.java:[142,32] [deprecation] decode(String) in URLDecoder has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/SimpleHistogram.java:[250,77] [unchecked] unchecked cast
[ERROR]   required: Set<Entry<HistogramBucket,Long>>
  found:    Set
/home/vagrant/git/opentsdb/src-main/net/opentsdb/core/SpanGroup.java:[198,13] [deprecation] DownsamplingSpecification(long,Aggregator,FillPolicy) in DownsamplingSpecification has been deprecated
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[448,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[453,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[458,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[463,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[483,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[488,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/query/expression/IntersectionIterator.java:[493,14] NotImplementedException is internal proprietary API and may be removed in a future release
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/MultiGetQuery.java:[340,29] error: incompatible types: List<GetRequest> cannot be converted to GetRequest
[ERROR] /home/vagrant/git/opentsdb/src-main/net/opentsdb/core/MultiGetQuery.java:[355,19] error: cannot find symbol
[INFO] 39 errors
`
If I had to guess I would say there is a problem with the java version but I have no clue.
Any help would be appreciated.

B.R. Paul

**Comment by xujiesh0510** [comment]
https://github.com/OpenTSDB/opentsdb/issues/1752

**Comment by xujiesh0510** [comment]
#1752

**Comment by xujiesh0510** [comment]
any updates?

**Comment by pauldj54** [comment]
> any updates?

Hi, 
I had to followed the following steps in order to be able to build it:
1) Clone the 2.3.0 version instead of 2.4.0
2) Clone the asynccassandra project
3) Modified the file HBaseClient.java (asynccassandra) according to #1752   and also the pom.xml
4) I still got a compilation error and had to include this import to the HBaseClient.java `import com.netflix.astyanax.model.ConsistencyLevel;`
5) Last but not least, I had to remove the javadoc portion of the pom.xml
6) Built asyncassandra and moved the generated fat jar to the openTSDB project, then renamed it as also explained in the issue 1752 above
7) Then I was able to build openTSDB following the steps proposed in #920 (https://github.com/OpenTSDB/opentsdb/issues/920) 

I am still trying to start it, but I need to find the time to continue.

I think it worths to write an article about it and try to explain the reason of the modifications.

Best Regards, 
Paul

**Comment by xujiesh0510** [comment]
I've decided to use hbase as storage facility based on  #1752

**Comment by pauldj54** [comment]
I don't know if this is the correct place to give my opinion.
The thing here, I had expectations to be able to effectively use cassandra. 
I have nothing against HBase, but if you want to deliver a solution from scratch to a customer, which does not have Hadoop, there is a huge infrastructure overhead to start:
Hadoop --> HBase --> openTSDB
While cassandra is much easier to set up.
Of course you can pay for managed instances of HBase on the cloud.
I would also try other alternatives like Influx.
Best Regards, 
Paul
