### ISSUE TITLE
support time-shift of a metric

### ISSUE THREAD

**Issue by jtamplin** [OpenTSDB/opentsdb#175]
Graphite supports a timeShift(metric, delta) function which adjusts the time shown by the delta.  This is particularly useful for week-over-week/etc comparisons, where you plot one metric against that same metric 7 days ago.

It shouldn't be hard to implement, you just subtract the delta from the timestamp you are looking for before fetching it from the database.

**Comment by johann8384** [comment]
We have this in our internal OpenTSDB as one of the expressions, I'll try to get a PR together for it.

http://opentsdb.net/docs/build/html/api_http/query/gexp.html
