### ISSUE TITLE
"Unable to parse the given JSON","details":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException

### ISSUE THREAD

**Issue by JerAxxxxxxx** [OpenTSDB/opentsdb#1755]
When I used opentsdb to do the query, I encountered this error.
My parameters are  
query request：{"start":1566712800,"end":1566801499,"queries":[{"aggregator":"avg","metric":"7_8_13","rate":false,"downsample":"10m-avg-zero","tags":{},"filters":[{"type":"literal_or","tagk":"server_info","filter":"0.0.0.0","groupBy":false},{"type":"literal_or","tagk":"code","filter":"FR_B","groupBy":false}]}],"noAnnotations":false,"globalAnnotations":false,"msResolution":false,"showTSUIDs":false,"showSummary":false,"showQuery":false,"delete":false}
error
opentsdb查询失败异常提示：{"error":{"code":400,"message":"Unable to parse the given JSON","details":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"start\" (class net.opentsdb.core.IncomingDataPoint), not marked as ignorable (5 known properties: \"metric\", \"value\", \"timestamp\", \"tags\", \"tsuid\"])\n at [Source: (String)\"{\"start\":1566712800,\"end\":1566801499,\"queries\":[{\"aggregator\":\"avg\",\"metric\":\"7_8_13\",\"rate\":false,\"downsample\":\"10m-avg-zero\",\"tags\":{},\"filters\":[{\"type\":\"literal_or\",\"tagk\":\"server_info\",\"filter\":\"0.0.0.0\",\"groupBy\":false},{\"type\":\"literal_or\",\"tagk\":\"code\",\"filter\":\"FR_B\",\"groupBy\":false}]}],\"noAnnotations\":false,\"globalAnnotations\":false,\"msResolution\":false,\"showTSUIDs\":false,\"showSummary\":false,\"showQuery\":false,\"delete\":false}\"; line: 1, column: 20] (through reference chain: net.opentsdb.core.IncomingDataPoint[\"start\"])","trace":"net.opentsdb.tsd.BadRequestException: Unable to parse the given JSON\n\tat net.opentsdb.tsd.HttpJsonSerializer.parsePutV1(HttpJsonSerializer.java:151) ~[build/:na]\n\tat net.opentsdb.tsd.PutDataPointRpc.execute(PutDataPointRpc.java:122) ~[build/:na]\n\tat net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [build/:na]\n\tat net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [build/:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.6.Final.jar:na]\n\tat net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:128) [build/:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.6.Final.jar:na]\n\tat org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.6.Final.jar:na]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]\n\tat java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]\nCaused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"start\" (class net.opentsdb.core.IncomingDataPoint), not marked as ignorable (5 known properties: \"metric\", \"value\", \"timestamp\", \"tags\", \"tsuid\"])\n at [Source: (String)\"{\"start\":1566712800,\"end\":1566801499,\"queries\":[{\"aggregator\":\"avg\",\"metric\":\"7_8_13\",\"rate\":false,\"downsample\":\"10m-avg-zero\",\"tags\":{},\"filters\":[{\"type\":\"literal_or\",\"tagk\":\"server_info\",\"filter\":\"0.0.0.0\",\"groupBy\":false},{\"type\":\"literal_or\",\"tagk\":\"code\",\"filter\":\"FR_B\",\"groupBy\":false}]}],\"noAnnotations\":false,\"globalAnnotations\":false,\"msResolution\":false,\"showTSUIDs\":false,\"showSummary\":false,\"showQuery\":false,\"delete\":false}\"; line: 1, column: 20] (through reference chain: net.opentsdb.core.IncomingDataPoint[\"start\"])\n\tat net.opentsdb.utils.JSON.parseToObject(JSON.java:112) ~[build/:na]\n\tat net.opentsdb.tsd.HttpJsonSerializer.parsePutV1(HttpJsonSerializer.java:142) ~[build/:na]\n\t... 47 common frames omitted\nCaused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"start\" (class net.opentsdb.core.IncomingDataPoint), not marked as ignorable (5 known properties: \"metric\", \"value\", \"timestamp\", \"tags\", \"tsuid\"])\n at [Source: (String)\"{\"start\":1566712800,\"end\":1566801499,\"queries\":[{\"aggregator\":\"avg\",\"metric\":\"7_8_13\",\"rate\":false,\"downsample\":\"10m-avg-zero\",\"tags\":{},\"filters\":[{\"type\":\"literal_or\",\"tagk\":\"server_info\",\"filter\":\"0.0.0.0\",\"groupBy\":false},{\"type\":\"literal_or\",\"tagk\":\"code\",\"filter\":\"FR_B\",\"groupBy\":false}]}],\"noAnnotations\":false,\"globalAnnotations\":false,\"msResolution\":false,\"showTSUIDs\":false,\"showSummary\":false,\"showQuery\":false,\"delete\":false}\"; line: 1, column: 20] (through reference chain: net.opentsdb.core.IncomingDataPoint[\"start\"])\n\tat com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind-2.9.5.jar:2.9.5]\n\tat net.opentsdb.utils.JSON.parseToObject(JSON.java:108) ~[build/:na]\n\t... 48 common frames omitted\n"}}

**Comment by JerAxxxxxxx** [comment]
I am a newcomer to opentsdb.This problem came up when the project went live, I was about to collapse. @qudongfang

**Comment by muffix** [comment]
From the stack trace, it looks like you sent the query to the `put` endpoint, rather than `/api/query`.

**Comment by JerAxxxxxxx** [comment]
@muffix Yes, it is. It was my negligence. Thank you very much.
