### ISSUE TITLE
How to improve the query performance of opentsdb?

### ISSUE THREAD

**Issue by JerAxxxxxxx** [OpenTSDB/opentsdb#1757]
In the process of querying, the performance is very low, tps is 100 (query speed per second), even if multi-threading is the same, there is no way to improve query efficiency, such as modifying the configuration of the opentsdb.conf file, etc.

**Comment by JerAxxxxxxx** [comment]
@johnseekins Thank you, but I don't know much about HBase. I plan to do a cache through redis. I don't know if this works.

**Comment by johnseekins** [comment]
There isn't currently a way to use Redis to cache data in OpenTSDB. There's supposed to be with the 3.0 release, but that hasn't happened yet, and the 3.0 docs don't mention it yet.

If you're going to use OpenTSDB, understanding HBase is a _really_ good idea.

**Comment by JerAxxxxxxx** [comment]
Ok, I understand, thank you very much for your advice.

> 目前没有办法使用Redis缓存OpenTSDB中的数据。应该有3.0版本，但尚未发生，3.0文档尚未提及。
> 
> 如果你打算使用OpenTSDB，理解HBase是一个_非常_好的主意。

**Comment by johann8384** [comment]
There is actually a way to use a Redis cache with OpenTSDB using Splicer but it isn't really supported or maintained much anymore. https://github.com/turn/splicer

**Comment by johnseekins** [comment]
@johann8384 Has a good point. Splicer does work, but doesn't support some newer functions (exp/gexp/etc) in OpenTSDB.

**Comment by johann8384** [comment]
It supports graphite expressions (gexp), but not query expressions (qexp). We added gexp at the same time as writing Splicer to OpenTSDB because we were migrating from Graphite. Query Expressions were being developed at the same time and also weren't merged in yet so we didn't have those at the time.
