### ISSUE TITLE
RPC Plugin doesn't appear to create/update metadata

### ISSUE THREAD

**Issue by johnseekins** [OpenTSDB/opentsdb#1779]
Using the Kafka RPC plugin to ingest data, we don't seem to get metadata updates created as new/existing metrics are written. It's hard to show examples of this, but is there any reason the metadata wouldn't be populating from the RPC plugin?

**Comment by manolama** [comment]
Nope, should work ok as long as meta is enabled. I'll try it out.

**Comment by johnseekins** [comment]
Oh wow. I forgot about this issue. While I don't recall what was wrong, we for sure got past it some time ago.

**Comment by manolama** [comment]
No worries, confirmed it worked when I added some logging and fixed the column families in the table config.
