### ISSUE TITLE
Opentsdb query, return after adding filter: [ ]

### ISSUE THREAD

**Issue by JerAxxxxxxx** [OpenTSDB/opentsdb#1822]
**Request message**: 
{"start":1571374800,"end":1571396399,"queries":[{"aggregator":"none","metric":"7_8_13","rate":false,"downsample":"","tags":{},"filters":[],"explicitTags":true,"useMultiGets":true}],"noAnnotations":false,"globalAnnotations":false,"msResolution":false,"showTSUIDs":false,"showSummary":false,"showQuery":false,"delete":false}
**Return message**:
[{"metric":"7_8_13","tags":{"interval":"600","code":"0101011001","server_info":"0.0.0.0"},"aggregateTags":[],"dps":{"1571385600":0,"1571385605":1,"1571385610":2,"1571385615":3,"1571385620":4,"1571385625":5}}]
##### But once the filter is added, only the brackets are left.
**Request message**: 
{"start":1571374800,"end":1571396399,"queries":[{"aggregator":"none","metric":"7_8_13","rate":false,"downsample":"","tags":{},"filters":[{"type":"literal_or","tagk":"server_info","filter":"0.0.0.0","groupBy":false}],"explicitTags":true,"useMultiGets":true}],"noAnnotations":false,"globalAnnotations":false,"msResolution":false,"showTSUIDs":false,"showSummary":false,"showQuery":false,"delete":false}
**Return message**:
[]

**Comment by deamerfire** [comment]
Because explicitTags will only return the tagk in the filter, the first query is invalid, so it can return data, the second query is valid, resulting in the failure to match the data
