### ISSUE TITLE
Client tried to access missing scanner

### ISSUE THREAD

**Issue by FreaxLin** [OpenTSDB/opentsdb#1854]
when I submit  a series of read request and cancel A few seconds later.I found HRegionserver keep printing logs with "regionserver.RSRpcServices: Client tried to access missing scanner 3008209529503481894". when I stop opentsdb server, the HRegionserver stop print.
![image](https://user-images.githubusercontent.com/25652335/68853489-0f435500-0715-11ea-86b3-da461bd1b9ab.png)

**Comment by johnseekins** [comment]
I've experienced this as well. I'm hoping to test whether patching https://github.com/OpenTSDB/opentsdb/pull/1830 in helps resolve the problem without requiring restarts.

**Comment by FreaxLin** [comment]
Thank you very much.I will test whether this patching is useful.

**Comment by FreaxLin** [comment]
> I've experienced this as well. I'm hoping to test whether patching #1830 in helps resolve the problem without requiring restarts.

Thank you very much.I will test whether this patching is useful.

**Comment by manolama** [comment]
That patch should work. Also AsyncHBase RPC timeouts can be used now.
