### ISSUE TITLE
Null pointer exception in Query.validate()

### ISSUE THREAD

**Issue by XOSplicer** [OpenTSDB/opentsdb#1886]
When calling the query expression api without providing `filters` and `expressions`, 
a null pointer exception is thrown from within `Query.validate`.

The null pointer arises from the following code, as `filters` and `expressions` are not checked to not be `null` before iterating over them.

https://github.com/OpenTSDB/opentsdb/blob/793cfede1f3d2da0a4b0d219c95fb536009c98c7/src/query/pojo/Query.java#L125-L149

## Non-working example
```json
{
	"time": {
		"start": "10m-ago",
		"aggregator": "sum",
		"end": "now",
		"downsampler": {
			"interval": "1m",
			"aggregator": "avg"
		}
	},
	"metrics": [
		{
			"id": "somemetric",
			"metric": "some.metric",
			"aggregator": "sum"
		}	
	],
}
```

## Working example

```json
{
	"time": {
		"start": "10m-ago",
		"aggregator": "sum",
		"end": "now",
		"downsampler": {
			"interval": "1m",
			"aggregator": "avg"
		}
	},
        "filters": [],
	"metrics": [
		{
			"id": "somemetric",
			"metric": "some.metric",
			"aggregator": "sum"
		}	
	],
      "expressions": []
}
```

## Error message:
```json
{
    "error": {
        "code": 500,
        "message": "An internal null pointer exception was thrown",
        "trace": ...
    }
}
```

## Versions
OpenTSDB: mapr-v2.4.0

**Comment by FernandaCG** [comment]
Hi, can I work on this?

**Comment by XOSplicer** [comment]
Sure, thanks for picking this issue up

**Comment by manolama** [comment]
The original code wasn't meant to allow just a metric query as the `/api/query` API is more efficient for that use case. The missing filter issue was a goof up. But we now have a patch for this so go crazy.
