### ISSUE TITLE
The Central Repository no longer supports insecure communication over plain HTTP

### ISSUE THREAD

**Issue by hipotures** [OpenTSDB/opentsdb#1899]
Effective from 15 January 2020, the central maven repository doesn't support insecure communication over plain HTTP.

set dummy "http://central.maven.org/maven2/org/ow2/asm/asm/4.0" "third_party/kryo/asm-4.0.jar"; shift; ./build-aux/fetchdep.sh "$@"
--2020-01-16 09:15:59-- http://central.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Resolving central.maven.org... 151.101.248.209
Connecting to central.maven.org|151.101.248.209|:80... connected.
HTTP request sent, awaiting response... 501 HTTPS Required
2020-01-16 09:15:59 ERROR 501: HTTPS Required.

make: *** [Makefile:2261: third_party/kryo/asm-4.0.jar] Error 8

**Comment by datto-aparrill** [comment]
Doing a global replace of `http://central.maven.org/maven2/` and `http://repo1.maven.org/maven2/` with `https://repo1.maven.org/maven2/` fixed the issue for us.

**Comment by selimchergui** [comment]
Try this:
`find . | xargs grep -s central.maven.org | cut -f1 -d : | xargs sed -i '' -e  "s/http:\/\/central/https:\/\/repo1/g"`
and then:
`find . | xargs grep -s repo1.maven.org | cut -f1 -d : | xargs sed -i '' -e  "s/http:\/\/repo1/https:\/\/repo1/g"`

**Comment by datto-aparrill** [comment]
While we're on this topic, please consider moving to a maven-only build system, which would prevent issues like this in the future and simplify building.
