### ISSUE TITLE
Find an effective way to migrate from opentsdb to sqlserver and postgresql 

### ISSUE THREAD

**Issue by suishaojian** [OpenTSDB/opentsdb#1923]
Hi ,  nowadays I got a trouble which needs to migrate from opentsdb to sqlserver and postgresql . 
I am looking forward if anyone can offer any advice about this ... 
Thank you so much.

**Comment by manolama** [comment]
Ug this would be a tough one if there is a lot of data. You can use the http://opentsdb.net/docs/build/html/user_guide/cli/scan.html tool to get data out a bit at a time. Otherwise your best bet may be to write a Java app to scan and inject into SQL.

**Comment by suishaojian** [comment]
> Ug this would be a tough one if there is a lot of data. You can use the http://opentsdb.net/docs/build/html/user_guide/cli/scan.html tool to get data out a bit at a time. Otherwise your best bet may be to write a Java app to scan and inject into SQL.

Thanks for replying.  Actually，I did use this way and I just want  to find some better way .
