### ISSUE TITLE
data delete bug

### ISSUE THREAD

**Issue by imxushuai** [OpenTSDB/opentsdb#1939]
# issues
i want delete data from 14:00 - 14:30

**Comment by imxushuai** [comment]
this is my post request

**Comment by imxushuai** [comment]
```json
{
  "start":1587880800,
  "queries": [{
    "aggregator": "none",
    "metric": "1e8d6a5bcc783a0a49901af3eaee174.1ea85dae70f0f30ad9f775340444936",
    "tags": {
      "prop": "UB"
    }
  }],
  "end":1587882600
}
```

**Comment by imxushuai** [comment]
The deletion was successful, but I found that the data from 14: 30-15: 00 is also gone.
Is there a problem with the request I sent? Or something else happened

**Comment by imxushuai** [comment]
my opentsdb version 2.3.0

**Comment by swissashley** [comment]
```Deleting data is permanent. Also beware that when deleting, some data outside the boundaries of the start and end times may be deleted as data is stored on an hourly basis.```

**Comment by manolama** [comment]
@victorlin-houzz is correct. We can only delete an entire row right now in HBase, which is an hour wide. Supporting a true delete of just the values in a narrow time range is tricky but if someone wants to tackle it we could add it.
