### ISSUE TITLE
 Questions about OpenTSDB2.4  /api/rollup

### ISSUE THREAD

**Issue by kongweiteng** [OpenTSDB/opentsdb#1943]
Hello,I have such another requirement about version 2.4 / api / rollup, I do n’t know if OpenTSDB can achieve it, please help me to see.

My configuration

{
      "aggregationIds": {
              "sum": 0,
              "count": 1,
              "min": 2,
              "max": 3
      },
      "intervals": [{
              "table": "tsdb",
              "preAggregationTable": "tsdb-pre",
              "interval": "1m",
              "rowSpan": "1h",
              "defaultInterval": true
      }, {
              "table": "tsdb-rollup-1h",
              "preAggregationTable": "tsdb-rollup-1h-pre",
              "interval": "1h",
              "rowSpan": "1d"
      }]
}

I use flink to aggregate the data and store it in OpenTSDB,But I encountered such a problem.

The window set by my flink is 15 minutes, but I want to store hourly rollup data to OpenTSDB.

E.g

/api/rollup

{
    "metric": "sys.cpu.nice1",
    "timestamp": 1589299200,
    "value": 10,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "sum",
    "groupByAggregator": "sum"
}

{
    "metric": "sys.cpu.nice1",
    "timestamp": 1589300100,
    "value": 10,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "sum",
    "groupByAggregator": "sum"
}

{
    "metric": "sys.cpu.nice1",
    "timestamp": 1589301000,
    "value": 10,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "sum",
    "groupByAggregator": "sum"
}

{
    "metric": "sys.cpu.nice1",
    "timestamp": 1589301600,
    "value": 10,
    "tags": {
       "host": "web01",
       "dc": "lga"
    },
    "interval": "1h",
    "aggregator": "sum",
    "groupByAggregator": "sum"
}
When i execute the query

{
    "start": 1589299200,
 
    "queries": [
        {
            "aggregator": "sum",
            "metric": "sys.cpu.nice1",
            "tags": {
                "host": "web01",
    			"dc": "lga"
            },
            "downsample": "1h-sum",
            "rollupUsage": "ROLLUP_NOFALLBACK",
            "preAggregate":true
        }
    ]

}

result

[
    {
        "metric": "sys.cpu.nice1",
        "tags": {
            "host": "web01",
            "_aggregate": "SUM",
            "dc": "lga"
        },
        "aggregateTags": [],
        "dps": {
            "1589299200": 10
        }
    }
]

I want to get 40 instead of 10.What I get now is 10, can you tell me how I can get 40?

My expected result

[
    {
        "metric": "sys.cpu.nice1",
        "tags": {
            "host": "web01",
            "_aggregate": "SUM",
            "dc": "lga"
        },
        "aggregateTags": [],
        "dps": {
            "1589299200": 40
        }
    }
]

**Comment by deamerfire** [comment]
I use the same configuration and query, and encountered the following ERROR, is there something wrong with me?

{"error":{"code": 424, "message": "Too many attempts: OpenScannerRequest(scanner=Scanner(table=\"c3tstpmq7:tsdb-servic-rollup-1h\", start_key=[0, 0, 0, 6, 94, -71, -25, 0], stop_key=[0, 0, 0, 6, 94, -67, -37, -128], columns={\"t\"}, populate_blockcache=true, max_num_rows=128, max_num_kvs=4096, versions=1, region=null, filter=FilterList(filters=[KeyRegexpFilter(\"(?s)^.{8}(?:.{8})*\\Q\u0000\u0000\u0000\f\\E(?:\\Q\u0000\u0000\u0003ê\\E)(?:.{8})*\\Q\u0000\u0000\u0000\r\\E(?:\\Q\u0000\u0000\u0003ë\\E)(?:.{8})*$\", ISO-8859-1), FilterList(filters=[QualifierFilter(EQUAL, BinaryPrefixComparator(\"sum\")), QualifierFilter(EQUAL, BinaryPrefixComparator(\"\\x00\"))], op=MUST_PASS_ONE)], op=MUST_PASS_ALL), scanner_id=0x0000000000000000, minTimestamp=0, maxTimestamp=9223372036854775807))",…}

**Comment by deamerfire** [comment]
I still do n’t understand. Do I need other computing plugins when using api / rollup endpoint? Such as flink

**Comment by kongweiteng** [comment]
> I still do n’t understand. Do I need other computing plugins when using api / rollup endpoint? Such as flink

I guess yours may not have created the table tsdb-servic-rollup-1h
No additional plug-ins are required. OpenTSDB only provides storage and aggregation of data, and does not help us calculate. We need to use an external calculation program to achieve data aggregation

**Comment by deamerfire** [comment]
I reproduced your error. By looking at the data in HBase, I found that only the last piece of data, that is, the first three pieces were overwritten. I guess, the interval used is one hour, then only the latest data will be kept within one hour

**Comment by iamsurya-dev** [comment]
@kongweiteng  You'd rather create a table `tsdb-rollup-15m` instead for your usecase. Since the rollups will be overwritten

**Comment by manolama** [comment]
Right, the rollups will only store one value per rollup interval and keep overwriting. So Flink would need to run and compute the rollups for an entire hour, then post. Or switch to a 15m config and have Flink post to that.
