### ISSUE TITLE
query return dps is empty

### ISSUE THREAD

**Issue by slin1972** [OpenTSDB/opentsdb#1944]
first result dps is empy.
![image](https://user-images.githubusercontent.com/7867412/81915631-6e6f1d00-9605-11ea-97f0-6a2a6d011590.png)

but my put body is 
![image](https://user-images.githubusercontent.com/7867412/81916538-85fad580-9606-11ea-9d87-073fb535ee84.png)

And I tried to put repeatedly, all successful

but result still like first picture

why?

**Comment by iamsurya-dev** [comment]
The timestamps do not seem to overlap over here in /query vs /put. Did it work otherwise?

**Comment by manolama** [comment]
Right, the posted value is outside of the query time range.
