### ISSUE TITLE
How to troubleshoot high cpu utilisation?

### ISSUE THREAD

**Issue by tomaustin700** [OpenTSDB/opentsdb#1957]
Hi,
I have a standalone hbase server with opentsdb running on it for testing purposes. I'm seeing high cpu utilisation from the opentsdb process that seems to last 5-10 mins that reoccurs once every 5 mins. During the high utilisation the UI becomes very slow and clients start to timeout. How can I debug this? 

![image](https://user-images.githubusercontent.com/6324102/83133456-d2e8ac80-a0da-11ea-91ba-0f2d43fc7659.png)

Thanks

**Comment by qiguoxiaosheng** [comment]
Perhaps it caused by gc, is there any large writes or queries when occur high cpu utilisation?  You can print out the thread which caused the high cpu utilisation.

**Comment by tomaustin700** [comment]
Hi @qiguoxiaosheng, I don't think there are any large writes or queries but it does seem to happen when a large amount of data is being sent to OpenTSDB. How would I print out the thread?

Thanks

**Comment by qiguoxiaosheng** [comment]
you can try to use top, jstat, jstack command.

**Comment by johnewing1** [comment]
https://visualvm.github.io
Visual VM is good for profiling the live service so you can see where the time is going. You can drill down into each thread and see where the CPU is being spent. 

Flight recorder is also great, but requires using specific JDKs for it to work
https://www.baeldung.com/java-flight-recorder-monitoring
