### ISSUE TITLE
Hbase issue post cloudera upgrade

### ISSUE THREAD

**Issue by ADDale** [OpenTSDB/opentsdb#1974]
Hi,

We switched to cloudera CDG 2.6.0-1 and post that getting below error for hbase application.

HBaseClient: Lost connection with the .META. region Client is invoking getClosestRowBefore removed in hbase-2.0.0

rg.apache.hadoop.hbase.exceptions.UnknownProtocolException: Is this a pre-hbase-1.0.0 or asynchbase client? Client is invoking getClosestRowBefore removed in hbase-2.0.0 replaced by reverse Scan.
at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2438)

hbase version-2.0

Any idea how this can be fixed?

**Comment by johnseekins** [comment]
What version of OpenTSDB are you running? I _believe_ 2.4 has patches to the asynchbase libraries that solve this. I know we're successfully running against HBase 2.2.3, so...

**Comment by manolama** [comment]
Yeah make sure to at least update AsyncHBase to 1.8 or later.
