### ISSUE TITLE
Unit opentsdb.service could not be found

### ISSUE THREAD

**Issue by Triggergirl** [OpenTSDB/opentsdb#2033]
Hi ,
I installed opentsdb-2.4.0.noarch.rpm using yum in OEL7 box as root user. Post installation  while checking the status, it throws below error:

root@localhost:/root# /bin/systemctl status opentsdb
Unit opentsdb.service could not be found.

root@localhost:/root# service opentsdb status
Redirecting to /bin/systemctl status opentsdb.service
Unit opentsdb.service could not be found.

Kindly let me know anyone faced this issue

**Comment by johann8384** [comment]
I'll have to look, it's possible we haven't updated the init scripts in the RPM to work for SystemD.

**Comment by Triggergirl** [comment]
Hi Johann, May i know when this can be updated and released

**Comment by serafeimgr** [comment]
Any update on this?

**Comment by manolama** [comment]
Merged a fix. The previous commit had a parameterized systemd service. This now has a standard version as well as the parameterized version.
