### ISSUE TITLE
/api/search/lookup always return empty list

### ISSUE THREAD

**Issue by tarjintor** [OpenTSDB/opentsdb#2052]
Hello,I am using opentsdb 2.3 and I trying to use grafana's variables,and it use 
`api/search/lookup`
and I try alot of diffirent metrics,it always return empty list,am I use it wrong?

```
api/search/lookup?m=memory_cache_gauge
{"type":"LOOKUP","metric":"memory_cache_gauge","tags":[],"limit":25,"time":1.0,"results":[],"startIndex":0,"totalResults":0}
```

**Comment by deamerfire** [comment]
When you want to use the lookup function, you need to turn on tracking or increment to enable the meta table

**Comment by tarjintor** [comment]
> When you want to use the lookup function, you need to turn on tracking or increment to enable the meta table

```
#tsd.core.meta.enable_tsuid_tracking = true
#tsd.core.meta.enable_tsuid_incrementing = true
```

Do you mean these configs?

**Comment by deamerfire** [comment]
Yes, you should enable one of these config and you can use lookup endpoint

**Comment by tarjintor** [comment]
> Yes, you should enable one of these config and you can use lookup endpoint

thanks,our opentsdb operator says use these configs will make opentsdb lose performance，so I will try another way to get variables in grafana
