### ISSUE TITLE
Uri should not transfer to lower case in FileFactory.java

### ISSUE THREAD

**Issue by pengmq1** [OpenTSDB/opentsdb#2056]
when start 3.0 tsd use:
./bin/tsdb tsd --config.providers=file:///Var/opentsdb.yaml
it will throw ERROR and terminate.
WARN  [main] YamlJsonFileProvider: No file found at: /var/opentsdb.yaml
but the is truely exist in /Var/opentsdb.yaml. 
Because the file PATH has Upper case character.
It is a bug.

**Comment by pengmq1** [comment]
see PR as follows

**Comment by manolama** [comment]
Merged, thanks.
