### ISSUE TITLE
what should i do when open this project with IDEA？

### ISSUE THREAD

**Issue by IAmJustApiCaller** [OpenTSDB/opentsdb#2076]
Hello, everyone. I download this repository through "git clone" and then open the opentsdb project directory with IntelliJ IDEA. But error occurs when maven resolve dependencies, it's seems like maven could not resolve artifact version. I don't know how to make it work😢.
Any suggestions will be appreciate. Thank you.

Here is a screenshot of the error message:
![image](https://user-images.githubusercontent.com/77848829/105526819-dee64600-5d1d-11eb-9e2d-66e09cf2f51d.png)

**Comment by neilfordyce** [comment]
Hey.  pom.xml.in is actually a template input file for `make`.  The 3.0 branch has a pom.xml already made up, so it's easier to get up and running with IDEA if that's of interest.  If you want to run from master though, the following should work to generate a pom.xml.

```git clone git@github.com:OpenTSDB/opentsdb.git
cd opentsdb
./configure
./build.sh pom.xml
```

Then launch IDEA importing a maven project.

**Comment by caolizhi** [comment]
@neilfordyce hi, I have a question about running 3.0, should I run TsdMain in opentsdb-server-undertow module to run 3.0 branch ?

**Comment by manolama** [comment]
@caolizhi Yes that's the correct way. Another company asked for updated 3.x docs so let me get a quick-start up there along with config examples. The current prod Docker container is at https://hub.docker.com/r/opentsdb/opentsdb
