### ISSUE TITLE
about functions and expressions

### ISSUE THREAD

**Issue by zhangwenbo3616** [OpenTSDB/opentsdb#2082]
how can i use this,or where can i find the documention about it.
![1614157608](https://user-images.githubusercontent.com/38577369/108977078-28320880-76c3-11eb-8e9b-ac1489e881cb.png)

**Comment by manolama** [comment]
Those functions can be found on http://opentsdb.net/docs/build/html/api_http/query/gexp.html with that query endpoint.

**Comment by manolama** [comment]
Updated the source with links, thanks!
