### ISSUE TITLE
Bugs when different types of UniqueIds use different width

### ISSUE THREAD

**Issue by tsuna** [OpenTSDB/opentsdb#21]
Right now, the 3 types of unique IDs (managed by the `UniqueId` class) are hard-coded to be on 3 bytes.  We ran into some bugs at StumbleUpon when using 8 bytes for the tag value IDs.  This issue is about merging the bugfixes into the public tree.  Eventually each unique ID type should be configurable through command-line flags.

**Comment by johann8384** [comment]
They are now configurable, I'm closing this mostly due to age, although there may indeed still be bugs if they are different widths.
