### ISSUE TITLE
OpenTSDB DB Schema Clarification

### ISSUE THREAD

**Issue by Sync1011** [OpenTSDB/opentsdb#2115]
I am trying to learn more about OpenTSDB.

I came across the [database schema documentation](http://opentsdb.net/docs/build/html/user_guide/backends/hbase.html) documentation. It mentions that, *"Rows are broken up into hour increments, reflected by the timestamp in each row. Thus each timestamp will be normalized to an hour value, e.g. 2013-01-01 08:00:00."*

If I understand this correctly, OpenTSDB will store all the metrics emitted for that one hour in a single row with the timestamp normalized to the beginning of that hour.

***

My question now is, if I want to see the metrics emitted for a given label/metric between the 20th minute and the 40th minute for a given hour, how will OpenTSDB accommodate this query? Since the row key is normalized to the beginning of the hour and it does not keep track of any other timestamp (AFAIK), how will it know which metrics came between the 20th minute and the 40th minute?

**Comment by johann8384** [comment]
It will retrieve the entire hour from HBase.

**Comment by Sync1011** [comment]
Thanks @johann8384! 

If I were plotting he 1hr period on a graph, how does it maintain the order? For example if I wanted to see how many `500s` an API emitted in the past 1hour, how will it graph the number of `500s` at the 10min mark and 20min mark and so on.
