### ISSUE TITLE
HTTP API delete bug version 2.4

### ISSUE THREAD

**Issue by nimitnagpal** [OpenTSDB/opentsdb#2139]
I am using the http api to delete a metric, but after the deletion, the metric still shows in the subsequent queries

Trying a curl call :
`curl --request POST \
  --url http://tsdb_server:4242/api/query/?details \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{
    "start":<start_time>,
    "end": <end_time>,
    "delete": true,
    "queries": [{
        "metric": "<metric_name>",
        "aggregator": "sum",
        "tags": {
            "tag1": "value1",
            "tag2": "value2",
            "tag3": "value3",
            "tag4": "value4"
        }
    }]
}'`

I get a 200 response even though the metric still appears in subsequent queries.

**Comment by manolama** [comment]
Anything in the logs about a failed call?

**Comment by manolama** [comment]
Oh @nimitnagpal Did you have `tsd.http.query.allow_delete` set to true in your config? That's disabled by default to avoid accidental erasure.

**Comment by manolama** [comment]
Yeah try that. Confirmed that it worked with my copy.
