### ISSUE TITLE
Is there python/node library for opentsdb?

### ISSUE THREAD

**Issue by piaoyuankui** [OpenTSDB/opentsdb#214]
I know there will be a new 2.0 release for OpenTSDB soon, and It will provide more http interfaces.
I hope that it better have a python/node library for there apis.

**Comment by johann8384** [comment]
I'll work on these for the 2.4 release, with the addition of the authentication plugin this will be more important.

**Comment by luluprat** [comment]
are you working on a python library for 2.4 ?

**Comment by IDerr** [comment]
https://pypi.python.org/pypi/potsdb
https://www.npmjs.com/package/opentsdb

There's already that
@manolama You could add the node library to ressources on the website.

I think that with this answer, we can close this issue :D

**Comment by IDerr** [comment]
or @johann8384

**Comment by IDerr** [comment]
?
