### ISSUE TITLE
How can i create, and read data by python using CLI?

### ISSUE THREAD

**Issue by Dhruvinhp** [OpenTSDB/opentsdb#2167]
I'm trying to save json data into the database of opentsdb, but when i try to retrieve the data that time i got this ERROR, <br> ```invalid character 'E' looking for beginning of value``` <br> i don't know what causing it! I'm using opentsdb with python, <br> Here is my Commands for it, <br> for put the data, <br> ```curl -X POST --data-binary @opentsdb.json 'https://DESC:TOKEN_WRITE@opentsdb.gra1.metrics.ovh.net/api/put'``` <br> 
for retrieve the data, <br>
```curl --data-binary @query.json 'https://DESC:TOKEN_READ@opentsdb.gra1.metrics.ovh.net/api/query'```

and here is my Json files for enter and retrieve data, <br><b>opentsdb.json</b> <br>
``` [
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346846400000,
        "value": 18,
        "tags": {
           "host": "web01",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346846800000,
        "value": 19,
        "tags": {
           "host": "web01",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346847000000,
        "value": 20,
        "tags": {
           "host": "web01",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346847000005,
        "value": 19,
        "tags": {
           "host": "web01",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346846400000,
        "value": 9,
        "tags": {
           "host": "web02",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346846800000,
        "value": 8,
        "tags": {
           "host": "web02",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346847000000,
        "value": 7,
        "tags": {
           "host": "web02",
           "dc": "lga"
        }
    },
    {
        "metric": "sys.cpu.nice",
        "timestamp": 1346847000005,
        "value": 10,
        "tags": {
           "host": "web02",
           "dc": "lga"
        }
    }
]
 ```
<b>query.json</b>
```{
    "start": 1346846000000,
    "end": 1346847300005,
    "queries": [{
        "metric": "sys.cpu.nice",
        "aggregator": "min",
        "downsample": "4m-avg",
        "tags": {
            "host": "*",
            "dc": "*"
        }
    }]
}
```
<b>
And also i want to perform these kind of queries by python & CLI, if you know the way to do this please share it with me, cause opentsdb don't have enough community to help us. </b>

**Comment by bjozet** [comment]
@Dhruvinhp if the `opentsdb.json` you posted here, is the same that you use and get the error, it's malformed. Missing an opening `[` at the beginning. Verify your json before posting to opentsdb maybe? :)

**Comment by langerma** [comment]
if you want to tryout: https://github.com/langerma/py-opentsdb

**Comment by Dhruvinhp** [comment]
As I'm not working on this anymore I close this issue, Thanks for reaching out!

**Comment by deamerfire** [comment]
你的邮件我已收到，会及时回复你的，谢谢啦啦。。。。吴琼
