### ISSUE TITLE
OpenTSDB 2.4.1 is not published in Maven Central

### ISSUE THREAD

**Issue by funamoto** [OpenTSDB/opentsdb#2170]
Thank you for releasing OpenTSDB 2.4.1.

We would like to update, but we could not find OpenTSDB 2.4.1 in Maven Central.
Could you please publish it in Maven Central or other Public Maven Repository?

**Comment by manolama** [comment]
Yes, I ran into Javadoc issues last week when trying to deploy. I need to update those and then it should push properly.

**Comment by manolama** [comment]
Posted now in Maven.

**Comment by kish5430** [comment]
HI Team,

Getting below connection timed out error. Plz suggest.

-bash-4.2$ ./build.sh
+ test -f configure
+ test -d build
+ cd build
+ test -f Makefile
+ ../configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for md5sum... /usr/bin/md5sum
checking for java... /usr/java/applejdk-8-8.0.222.10.3/bin/java
checking for javac... /usr/java/applejdk-8-8.0.222.10.3/bin/javac
checking for jar... /usr/java/applejdk-8-8.0.222.10.3/bin/jar
checking for true... /usr/bin/true
checking for javadoc... /usr/java/applejdk-8-8.0.222.10.3/bin/javadoc
checking for wget... /usr/bin/wget
checking for curl... /usr/bin/curl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating opentsdb.spec
config.status: creating build-aux/fetchdep.sh
+ MAKE=make
++ uname -s
+ '[' Linux = FreeBSD ']'
+ exec make
/usr/bin/mkdir -p .git && echo unknown >.git/HEAD
set dummy "https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0" "third_party/kryo/asm-4.0.jar"; shift; ./build-aux/fetchdep.sh "$@"
--2022-07-11 13:24:49--  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Resolving repo1.maven.org (repo1.maven.org)... 151.101.40.209
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:26:57--  (try: 2)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:29:07--  (try: 3)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:31:17--  (try: 4)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:33:28--  (try: 5)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:35:41--  (try: 6)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:37:54--  (try: 7)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:40:08--  (try: 8)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

--2022-07-11 13:42:23--  (try: 9)  https://repo1.maven.org/maven2/org/ow2/asm/asm/4.0/asm-4.0.jar
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... failed: Connection timed out.
Retrying.

thanks
