### ISSUE TITLE
Makefile issues when build from source on Windows

### ISSUE THREAD

**Issue by hunt978** [OpenTSDB/opentsdb#2206]
* Javac on Windows using `;` as path separator

https://github.com/OpenTSDB/opentsdb/blob/877cdfad2e456b566f366f8ccbb9cbcdbdaa2836/Makefile.am#L587
https://github.com/OpenTSDB/opentsdb/blob/877cdfad2e456b566f366f8ccbb9cbcdbdaa2836/Makefile.am#L758

* Error of `Arguments too long`

https://github.com/OpenTSDB/opentsdb/blob/877cdfad2e456b566f366f8ccbb9cbcdbdaa2836/Makefile.am#L814

my version
```
	echo $(classes_with_nested_classes)  $(get_expr_classes) || xargs -0 $(JAR) cfm `basename $(jar)` manifest  \
         || { rv=$$? && rm -f `basename $(jar)` && exit $$rv; }
```

**Comment by hunt978** [comment]
failed building project on windows, and dropped tries.

**Comment by manolama** [comment]
Sorry, it's been a looong time since I tried to build on Windows. If you just need the Jar you could create the pom on a linux/mac host via `sh build.sh pom` and copy that over to your windows machine. Then it will build with Maven.
