### ISSUE TITLE
"Setup HBase" docs out-of-date

### ISSUE THREAD

**Issue by rodnaph** [OpenTSDB/opentsdb#222]
Hey, just going through the docs to try out OpenTSDB and noticed the "Setup HBase" page has become a little out of date as the release listed at the top isn't available for download any more.

This snippet....

```
wget http://www.apache.org/dist/hbase/hbase-0.94.5/hbase-0.94.5.tar.gz
tar xfz hbase-0.94.5.tar.gz
cd hbase-0.94.5
```

Needs to ba 0.94.10?

**Comment by johann8384** [comment]
I'll verify and close for the 2.3.0 release.
