### ISSUE TITLE
Can't Enable Tree Processing

### ISSUE THREAD

**Issue by kylebrandt** [OpenTSDB/opentsdb#239]
When I run `./tsdb uid treesync` I get the following warning:

`2013-09-16 21:48:56,540 WARN  [main] UidManager: Tree processing is disabled`

However, when I query the config using the API it verifies that tree processing is enabled:

`{'tsd.core.auto_create_metrics': 'true',
 'tsd.core.meta.enable_realtime_ts': 'true',
 'tsd.core.meta.enable_realtime_uid': 'true',
 'tsd.core.meta.enable_tsuid_incrementing': 'true',
 'tsd.core.plugin_path': '',
 'tsd.core.tree.enable_processing': 'true',
 'tsd.http.cachedir': '/tmp/tsd',
 'tsd.http.request.cors_domains': '',
 'tsd.http.request.enable_chunked': 'false',
 'tsd.http.request.max_chunk': '4096',
 'tsd.http.show_stack_trace': 'true',
 'tsd.http.staticroot': 'build/staticroot',
 'tsd.network.async_io': 'true',
 'tsd.network.bind': '0.0.0.0',
 'tsd.network.keep_alive': 'true',
 'tsd.network.port': '4242',
 'tsd.network.reuse_address': 'true',
 'tsd.network.tcp_no_delay': 'true',
 'tsd.network.worker_threads': '',
 'tsd.rtpublisher.enable': 'false',
 'tsd.rtpublisher.plugin': '',
 'tsd.search.enable': 'false',
 'tsd.search.plugin': '',
 'tsd.stats.canonical': 'false',
 'tsd.storage.enable_compaction': 'true',
 'tsd.storage.flush_interval': '1000',
 'tsd.storage.hbase.data_table': 'tsdb',
 'tsd.storage.hbase.meta_table': 'tsdb-meta',
 'tsd.storage.hbase.tree_table': 'tsdb-tree',
 'tsd.storage.hbase.uid_table': 'tsdb-uid',
 'tsd.storage.hbase.zk_basedir': '/hbase',
 'tsd.storage.hbase.zk_quorum': 'localhost'}`

**Comment by lekai9** [comment]
Hi,

I am having the same problem.
Did this issue fixed?
