### ISSUE TITLE
Migrate data from OpenTSDB instance

### ISSUE THREAD

**Issue by spyroslalos** [OpenTSDB/opentsdb#255]
So how easy is to migrate data from an Opentsdb instance running over Hadoop and Hbase?

**Comment by sanketplus** [comment]
this piece I wrote recently might help: https://superuser.blog/migrate-opentsdb-hbase/

**Comment by IDerr** [comment]
Exactly, as said @sanketplus , you can use either hbase mechanisms to move data from one cluster to another one : 

Snapshot or the Copytable job 
https://stackoverflow.com/questions/7952213/how-to-copy-a-table-from-one-hbase-cluster-to-another-cluster
http://hbase.apache.org/0.94/book/ops.snapshots.html


@manolama You can close this

**Comment by IDerr** [comment]
or @johann8384

**Comment by johann8384** [comment]
@spyroslalos If the normal ways to "copy hbase data" don't work, you can also use the command line utilities to dump the raw data and import it to another cluster. This is however, not a great experience.
