### ISSUE TITLE
HTTP API for listing all tag values for a specified tag key

### ISSUE THREAD

**Issue by rhwood** [OpenTSDB/opentsdb#267]
It would be helpful if the HTTP API included a method for listing all tag values for a given tag key. This would make it possible to (for example) create a client for a openTSDB-based monitoring system that listed every host (tagk="host") with a set of interesting stats for each host.

Without this additional API method, the client has to iterate through A-Z and 1-9 in `/suggest?type=tagv&q=<character>` for all tags that may or not be a host and then running a query similar to `/q?start=1h-ago&m=sum:rate:proc.stat.cpu.idle{host=<returned-tag>}&ascii` with each tag returned in the first query to test if the tag is a host or an attribute on a host.

I would much prefer to be able to run a query like `/api/suggest?type=tagv&q={tagk=host}` to (in this case) return all tag values for the tag "host"

**Comment by sanblch** [comment]
Is that issue really finished?
Could you, please, then show how to get a list of tagv values for a certain tagk? Examples are (not working, of coarse):
http://localhost:4242/api/suggest?type=tagv&q=*{tagk = host}
http://localhost:4242/api/search/lookup?m=*{type = tagv, tagk = host} .
Maybe I have an error, correct it, please.

**Comment by Carl-Hee** [comment]
Does anyone find a solution about this issue? 
Please share to us, thanks

**Comment by sumannewton** [comment]
Me too looking for a solution to get the list of tag values for a certain tag key.

**Comment by Ishmin** [comment]
I am facing the exact same issue. Any solutions? Please help.

**Comment by manolama** [comment]
We don't have anything really good for this yet, I'm working again on meta-integration with 3.0 though.
