### ISSUE TITLE
Include the release version number in log and support "--version" option on CLI.

### ISSUE THREAD

**Issue by adeconsulting** [OpenTSDB/opentsdb#268]
The Google Group forums talk about OpenTSDB release 2.0 and such, however this value doesn't exist anywhere in the product -- at least that I can find.

The TSD log only says:
TSDMain: net.opentsdb built at revision 6f1d105 (MINT)

Please include the release version number in this output, e.g.
TSDMain: net.opentsdb 2.0.0 built at revision 6f1d105 (MINT)

In addition, it would be helpful for the CLI to also support a "--version" option, e.g.
$ ./tsdb --version

**Comment by manolama** [comment]
Merged the PR related to this issue. 54303ce20668a1fb3e3c444ce2c577a064ac6147
