### ISSUE TITLE
Arithmetic expressions in queries

### ISSUE THREAD

**Issue by tsuna** [OpenTSDB/opentsdb#27]
OK this one is non-trivial but much wanted.  Instead of plotting one time series, I'd like to be able to do some simple arithmetic operations on multiple time series.  For instance divide the rate of errors by the rate of requests to get the ratio of failures.  Or find the percentage of disk space used using the disk space available and the disk space used.

This requires major changes in the query handling path, so it's going to happen in some sort of "v1.5".

**Comment by johann8384** [comment]
This ticket can now be closed.

http://opentsdb.net/docs/build/html/api_http/query/gexp.html

**Comment by manolama** [comment]
Done in 2.3
