### ISSUE TITLE
Native packages (.deb, .rpm)

### ISSUE THREAD

**Issue by tnn** [OpenTSDB/opentsdb#296]
Please consider to provide native package, instead of forcing users to build from source themselves. Platforms to consider could be Debian (.deb) and Redhat (.rpm).

Please consider to include service manifests also.

**Comment by bryan4887** [comment]
I tried building the rpm package on CentOS.  It builds an rpm called opentsdb-2.0.1*-root.noarch.rpm, where the * seems to be the date.  Installing it seemed to work fine except that it does not create the `opentsdb` user as it does with the deb.  The essentially forces you to run as root with `sudo service opentsdb start`.  This, of course, is not ideal, unless I've messed up one of these steps?

Thanks for any suggestions.
