### ISSUE TITLE
Bug while reading global annotations from the  /api/query endpoint

### ISSUE THREAD

**Issue by bbhati** [OpenTSDB/opentsdb#377]
Steps to reproduce: 
1)Upload 2 global annotations represented by : [
  {
    "description" : "A"
    "endTime": 0,
    "startTime": 1404689949000
  },
  {
    "description" : "B"
    "endTime": 0,
    "startTime": 1404690638000
  }
]
2)Issue a read request to /api/query endpoint with global_annotations=true query parameter. The global annotations array returned is buggy.
Expected:[
  {
    "description" : "A"
    "endTime": 0,
    "startTime": 1404689949000
  },
  {
    "description" : "B"
    "endTime": 0,
    "startTime": 1404690638000
  }
]

Actual: [
  {
    "description" : "A"
    "endTime": 0,
    "startTime": 1404689949000
  },
  {
    "description" : "A"
    "endTime": 0,
    "startTime": 1404689949000
  },
]

**Comment by IDerr** [comment]
Hi @bbhati 
if your question has been answered, could you close this issue ?

Thanks a lot :)
