### ISSUE TITLE
Is there a plan for the next version of OpenTSDB?

### ISSUE THREAD

**Issue by mxk1235** [OpenTSDB/opentsdb#383]
currently we depend on the next branch for the CORS headers fix.  wondering when that can make it into master.

**Comment by johann8384** [comment]
This can probably be closed.

**Comment by IDerr** [comment]
As @johann8384 said, It can be closed @manolama

**Comment by IDerr** [comment]
Hi @mxk1235,
if your problem has been resolved, could you please close this issue ?

Thanks :)
