### ISSUE TITLE
Graphing functions

### ISSUE THREAD

**Issue by davebarr** [OpenTSDB/opentsdb#4]
Currently there's no way to plot one time series against another.  There are some obvious use cases for this.  For example iostat's method of computing disk utilization involves comparing disk io time against idle cpu time.

The plan is to have a general purpose way to do functional plots of metrics against another.

**Comment by vitorboschi** [comment]
Was there any progress on this issue? Operations on metrics are a really useful thing to have

**Comment by jongwook** [comment]
+1

**Comment by johann8384** [comment]
These are now added to OpenTSDB in the 2.3 branch. http://opentsdb.net/docs/build/html/api_http/query/gexp.html
