### ISSUE TITLE
Feature request: Add functions to OpenTSDB (similar to Graphite)

### ISSUE THREAD

**Issue by trixpan** [OpenTSDB/opentsdb#433]
It would be great if OpenTSDB had a broader range of functions capable of performing calculations (couldn't find it in the OpenTSDB doco anything equivalent beyong the aggregation) similar to the [functions available in Graphite](https://graphite.readthedocs.org/en/0.9.10/functions.html) (e.g. absolute, asPercent, scale)

**Comment by calvinxiu** [comment]
yes , the function provided by Graphite and InfluxDB is rich than OpenTSDB, here is InfluxDB's aggregate functions. <http://influxdb.com/docs/v0.8/api/aggregate_functions.html>

Will OpenTSDB has plan to  improve it?

**Comment by manolama** [comment]
Yeah we're definitely looking to implement a number of expressions and functions though we have to make sure to do it in the right way. Thanks!

**Comment by johann8384** [comment]
This is now in 2.3, we can probably close this issue. @manolama

**Comment by johann8384** [comment]
https://github.com/OpenTSDB/opentsdb/issues/501
