### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by IzakMarais** [OpenTSDB/opentsdb#435]
On the [Writing Data](http://opentsdb.net/docs/build/html/user_guide/writing.html) official documentation page, the following sentence is incorrectly structured:

### Aggregations
> While the tagging system is flexible, some problems can arise if you don't understand how the querying  side of OpenTSDB, hence the need for some forethought. 

Possible intent:
> While the tagging system is flexible, some problems can arise if you don't understand ~~how~~ the querying  side of OpenTSDB, hence the need for some forethought. 

### Limited Unique IDs (UIDs)
> while consuming only 1 tag value UID (`1`) and 4 tag name UIDs 

Given the context, this explanation should probably read:

> while consuming only 1 tag value UID (`2`) and 4 tag name UIDs 

On the [Installation page](http://opentsdb.net/docs/build/html/installation.html):
### Installation
> ...HBase is running, you can choose to install OpenTSDB from a package (*Debian is the only one available at this time*) or from source using GIT or a source tarball.

Rpms have also been made available since this documentation was written.

**Comment by oozie** [comment]
Nice! All of it is pretty non-controversial. Would you like to submit a pull request for the two named docs?
https://github.com/OpenTSDB/opentsdb.net/blob/gh-pages/docs/source/user_guide/writing.rst
https://github.com/OpenTSDB/opentsdb.net/blob/gh-pages/docs/source/installation.rst

**Comment by IzakMarais** [comment]
This is on my TODO list. Just picked up the following one as well.

On the [Understanding Metrics and Time Series] page:

# Your first data points

> (OpenTSDB does resolution down to the second only at this time). 

This is no longer true.

**Comment by manolama** [comment]
Fixed. Thanks a ton for the proof reading!

**Comment by IzakMarais** [comment]
My pleasure. Thanks for the fix.
