### ISSUE TITLE
Include a reference in Multi-set response data to the originating query

### ISSUE THREAD

**Issue by kylemallory** [OpenTSDB/opentsdb#438]
When requesting a multi-set query (and possibly even in a single query) via a call to api/query, It would be helpful if the user and/or OpenTSDB could assign a unique ID to the each query (ie, queryUID?) and reference that uID as a property in the individual query responses which are a result of that particular query.

Currently, assuming there are 3 unique tagv values for host (serv01, serv02, serv03):
```javascript
{
    "start": 1356998400,
    "end": 1356998460,
    "queries": [
        {
            "aggregator": "sum",
            "metric": "sys.cpu.0",
            "rate": "true",
            "tags": {
                "host": "*"
            }
        },
        {
            "aggregator": "avg",
            "metric": "sys.cpu.0",
            "rate": "true",
            "tags": {
                "host": "*"
            }
        }
    ]
}
```

This request will return 6 datasets:
```javascript
[{"metric": "sys.cpu.0", "tags": {"host": "serv01"}, "dps": [....]},
 {"metric": "sys.cpu.0", "tags": {"host": "serv02"}, "dps": [....]},
 {"metric": "sys.cpu.0", "tags": {"host": "serv03"}, "dps": [....]},
 {"metric": "sys.cpu.0", "tags": {"host": "serv01"}, "dps": [....]},
 {"metric": "sys.cpu.0", "tags": {"host": "serv02"}, "dps": [....]},
 {"metric": "sys.cpu.0", "tags": {"host": "serv03"}, "dps": [....]}
]
```

However, in processing this response, there is no way to identify which dataset is tied to which query (either the SUM or AVG).

Proposal:
Allow an optional parameter in the query request, (GET: "id", POST: "queryId"); This value is returned in the result set along with the "metric" and "tags" properties, as "queryId". If no queryId is specified by the user/agent, the result set includes a "queryId" value with an index referencing the requesting query.  In the example above, without a queryId parameter, the response would look as follows:

```javascript
[{"queryId": 0, "metric": "sys.cpu.0", "tags": {"host": "serv01"}, "dps": [....]},
 {"queryId": 0, "metric": "sys.cpu.0", "tags": {"host": "serv02"}, "dps": [....]},
 {"queryId": 0, "metric": "sys.cpu.0", "tags": {"host": "serv03"}, "dps": [....]},
 {"queryId": 1, "metric": "sys.cpu.0", "tags": {"host": "serv01"}, "dps": [....]},
 {"queryId": 1, "metric": "sys.cpu.0", "tags": {"host": "serv02"}, "dps": [....]},
 {"queryId": 1, "metric": "sys.cpu.0", "tags": {"host": "serv03"}, "dps": [....]}
]
```

Ideally, the user/agent specified queryId would not be type-constrained, so it could be used as a name ("hosts", "average"), UID (0123456789ABCDEF), or a simple index.

Background:  I am attempting to add support for "alias variables" in Grafana, which can be used to expand an series name using tagk/tagv values, so that a query for "cpu{host=*}" with a series alias of "$host" will name each series the value of the individual host.  However, if multiple queries are made within the same graph, such as requesting individual CPU on the left-Y axis, and a combined, average CPU of all hosts on the right-Y axis, there is no simple, concrete way to determine which of those returning datasets are associated with which query.

**Comment by manolama** [comment]
We faced the exact same issue and added code to dump the full sub-query in the response so you can associate the proper request with the proper data. I'll get that pushed up soon.

**Comment by manolama** [comment]
This is now in the 2.2 or the ``put`` branch of Git. Simply add the flag ``&show_query=true`` to the URL query or ``"showQuery":true`` in JSON.
