### ISSUE TITLE
Tracking Invalid Values

### ISSUE THREAD

**Issue by DawgTool** [OpenTSDB/opentsdb#450]
Hi All,

Trying to track invalid and illegal arguments, however I am not having any success.
I currently have the root logger set in debug, along with hb,zk,as.  This doesn't seem to give me anything in regards to catching these errors.  Any suggestions?

tsd.rpc.errors 1424987992 1302 type=invalid_values host=localhost
tsd.rpc.errors 1424987992 2268 type=illegal_arguments host=localhost

**Comment by manolama** [comment]
How are you trying to write data, over HTTP or Telnet? Right now TSDB only returns errors like those to the client and doesn't log them locally (though it does increment the proper error counters). If you use Telnet you can read the errors off the socket (though you can't really associate them with a data point) or if you use HTTP it will return them if you ask for details. Of you do want to log them, I can point you at the locations where you can add some log lines.

**Comment by manolama** [comment]
Closing post @oozie's merge.
