### ISSUE TITLE
GUI stops responding after a while.

### ISSUE THREAD

**Issue by bryan4887** [OpenTSDB/opentsdb#452]
After a long time running the web interface GUI seems to stop responding to changes in the plotting parameters.  I can change things in the URL query parameters (the GET parameters) and then reload the browser, and this works.  Everything changed via the GUI, however, does not respond.  What's more weird, is that I have other tabs open that don't seem to be staled out at all.  Copying the staled URL and pasting it into a fresh tab has no effect either.  What does seem to work is starting over from a fresh http://host:4242 and then using the GUI to build up the time series that I want to plot.  This, however, is time consuming.

Has anyone else experienced this and found a way to fix it when it happens?

Thanks!

**Comment by oozie** [comment]
* Does it happen repeatedly or was it a one-off so far?
* If repeatedly, what's the best way to reproduce it?
* When you open Web Console (Firefox) or Chrome JavaScript Console do you see JavaScript errors that you don't see in a healthy tab?

**Comment by manolama** [comment]
I've seen the same thing using Chrome. One easy way to reproduce it is to setup one metric that graphs properly, then add a new metric tab and add another metric but set a tag and value that causes the graph to fail. I'm unable to recover from that without deleting the url parameters. I'm not particularly good at debugging browser/UI issues :(

**Comment by bryan4887** [comment]
@manolama  yes that sounds consistent with my experiences.  
@oozie  I'll look for those diagnostics the next time it happens.  Interestingly, it seems to be happening less frequently now that I've moved my system to a more powerful machine.

**Comment by oozie** [comment]
Thanks folks. I can reproduce the UI getting stuck when tags have bad values (seems like fair behavior) but my browser recovers when tags get corrected or removed.
That's on Chromium Version 41.0.2272.76. Anyway, I'll keep a lookout for weird behavior.

**Comment by oozie** [comment]
Totally reproducible in Firefox :)

**Comment by oozie** [comment]
The bug resurfaced again, web console shows an error that a healthy TSD UI doesn't:
```
TypeError: s is null
```
For more clues, GWT has to be recompiled in verbose mode.

**Comment by oozie** [comment]
DETAILED style of compilation reveals a hint:
```
TypeError: tags is null
```

**Comment by manolama** [comment]
Thanks to @oozie for the patch, reopen if it continues.
