### ISSUE TITLE
Racing in UID creation

### ISSUE THREAD

**Issue by huangjs** [OpenTSDB/opentsdb#453]
I'm using TSDB's Java API directly in my Spark app, and it seems there's racing condition happened during new UID creation. Here's the scan of my tsdb-uid table:

\x00\x00\x00\x00\x01                                        column=name:metrics, timestamp=1425281300443, value=limitation.count
 \x00\x00\x00\x00\x02                                        column=name:metrics, timestamp=1425281300443, value=limitation.count
 \x00\x00\x00\x00\x03                                        column=name:metrics, timestamp=1425281300443, value=limitation.count
 \x00\x00\x00\x00\x04                                        column=name:metrics, timestamp=1425281300443, value=limitation.count
...
 \x00\x00\x00\x16                                            column=name:tagv, timestamp=1425281300486, value=Active
 \x00\x00\x00\x17                                            column=name:tagv, timestamp=1425281300487, value=Active
 \x00\x00\x00\x18                                            column=name:tagv, timestamp=1425281300488, value=Active
 \x00\x00\x00\x19                                            column=name:tagv, timestamp=1425281300488, value=Active
 \x00\x00\x00\x1A                                            column=name:tagv, timestamp=1425281300488, value=Active
...

And the reverse index seems ok, it points to the first uid.
 Active                                                      column=id:tagv, timestamp=1425281300487, value=\x00\x00\x00\x16
 limitation.count                                            column=id:metrics, timestamp=1425281300447, value=\x00\x00\x00\x00\x01

Jianshi

**Comment by oozie** [comment]
Good catch. Could you please share what `opentsdb.log` recorded around this time?

**Comment by manolama** [comment]
Also which version of OpenTSDB are you using? Thanks!

**Comment by huangjs** [comment]
Hi,

I'm using 2.1RC1. I'll rerun it and check the logs.

Jianshi

On Wed, Mar 11, 2015 at 9:05 AM, Chris Larsen <notifications@github.com>
wrote:

> Also which version of OpenTSDB are you using? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTSDB/opentsdb/issues/453#issuecomment-78181789>.
>



-- 
Jianshi Huang

LinkedIn: jianshi
Twitter: @jshuang
Github & Blog: http://huangjs.github.com/

**Comment by huangjs** [comment]
I'm not using the REST API, I'm calling the Java API like this:

  def put(m: MetricDataPoint): Deferred[AnyRef] = {
    tsdb.addPoint(m.metric, m.timestamp, m.value, m.tags)
      .addErrback(putErrorHandler)
  }

tsdb is a TSDB singleton instance.

Is it ok to just call addPoint?

Jianshi

On Wed, Mar 11, 2015 at 11:27 AM, Jianshi Huang <jianshi.huang@gmail.com>
wrote:

> Hi,
>
> I'm using 2.1RC1. I'll rerun it and check the logs.
>
> Jianshi
>
> On Wed, Mar 11, 2015 at 9:05 AM, Chris Larsen <notifications@github.com>
> wrote:
>
>> Also which version of OpenTSDB are you using? Thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OpenTSDB/opentsdb/issues/453#issuecomment-78181789>.
>>
>
>
>
> --
> Jianshi Huang
>
> LinkedIn: jianshi
> Twitter: @jshuang
> Github & Blog: http://huangjs.github.com/
>



-- 
Jianshi Huang

LinkedIn: jianshi
Twitter: @jshuang
Github & Blog: http://huangjs.github.com/

**Comment by luluprat** [comment]
hello 
i am interrested in you appli
you said you are accessing opentsdb from spark.
is it possible to share your knowledge and code ?
I want to use spark over opentsdb|hbase.

**Comment by manolama** [comment]
Sorry for the wait, yeah it's fine to call ``addPoint()`` directly from your application.

Regarding the duplicates though, since your Spark setup is likely writing to multiple embedded TSD instances, they all simply received the same time series at around the same time. Thus they all started a UID assignment but only one "won" the race so this is expected behavior (not ideal, but expected ;). You can run a UID FSCK to clean up the orphaned reverse maps.

**Comment by huangjs** [comment]
Get it. Thank you for the explanation.

Jianshi

On Mon, Apr 20, 2015 at 10:10 AM, Chris Larsen <notifications@github.com>
wrote:

> Closed #453 <https://github.com/OpenTSDB/opentsdb/issues/453>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTSDB/opentsdb/issues/453#event-284855952>.
>



-- 
Jianshi Huang

LinkedIn: jianshi
Twitter: @jshuang
Github & Blog: http://huangjs.github.com/
