### ISSUE TITLE
A likely bug in Tree.deleteTree()

### ISSUE THREAD

**Issue by oozie** [OpenTSDB/opentsdb#459]
The test `TestTree.deleteTree()` had been passing under a false assumption about how asynchbase's Scanner works: `MockBase` has been including the stop row in the result set, which is not what happens in reality. `MockBase`'s behavior has been corrected in #458 but the test is now failing for either one of two reasons:
* it's a broken test with improper setup or 
* it surfaces an off-by-one bug in `Tree.deleteTree()`

Not sure which one it is; here is a TODO:
https://github.com/oozie/opentsdb/commit/db201c43c4d99cf3309100d3c20c9a99b3ba8048#diff-e95c7bedd8fc8751e18c663aa4fbef37R557

**Comment by manolama** [comment]
Fixed with @Oozie's commit.
