### ISSUE TITLE
Double-precision floating-point values?

### ISSUE THREAD

**Issue by lburg** [OpenTSDB/opentsdb#473]
According to the [documentation](http://opentsdb.net/docs/build/html/user_guide/writing.html#floating-point-values) only single-precision floating-points are supported, double-precision will come in a future release.

However, looking at the OpenTSDB core documentation, I see that there is a [addPoint](http://opentsdb.net/docs/javadoc/net/opentsdb/core/TSDB.html#addPoint%28java.lang.String, long, double, java.util.Map%29) method to add a double-precision floating-point value to the database. The PR #380 also refers to this by patching a comment. This PR was submitted in August 2014 and the `addPoint` method was added in version 1.2. I'm using version 2.0 and adding a double-precision floating-point value through telnet stores only a single-precision value (I'm running HBase 1.0).

Do you have an estimate release date for double-precision support?

**Comment by manolama** [comment]
Just need to review the PR and we can likely get it into 2.2 where I'm aiming for a May RC1 release.

**Comment by IDerr** [comment]
You can close this @manolama

**Comment by IDerr** [comment]
Hi @lburg,
if your problem has been resolved, could you please close this issue ?

Thanks :)

**Comment by lburg** [comment]
Whoops, sorry! Closing it, thanks!
