### ISSUE TITLE
opentsdb unable to delete tagv

### ISSUE THREAD

**Issue by yujinqiu** [OpenTSDB/opentsdb#474]
Hi there,  

I try to delete tag value but failed.    
1:  query tag value meta info :  

    curl 'http://localhost:4242/api/uid/uidmeta?uid=041F44&type=tagv'
        
 output:          

    {"uid":"041F44","type":"TAGV","name":"t.qq.com","description":"","notes":"","created":0,"custom":null,"displayName":""}
2: try to delete, I'm not sure which is right, so query both.     
    
    curl -X DELETE 'http://localhost:4242/api/uid/uidmeta?uid=041F44&type=tagv&method=delete' 
    curl 'http://localhost:4242/api/uid/uidmeta?uid=041F44&type=tagv&method=delete'      

3: drop caches.  

    curl 'http://localhost:4242/api/dropcaches'
    {"message":"Caches dropped","status":"200"}   

4: query again and I can still get the result.   

    curl 'http://localhost:4242/api/uid/uidmeta?uid=041F44&type=tagv'
output: 
    
       {"uid":"041F44","type":"TAGV","name":"t.qq.com","description":"","notes":"","created":0,"custom":null,"displayName":""}

**Comment by manolama** [comment]
I apologize for the confusion. The DELETE command doesn't actually remove the tag value from the system. It simply clears the UIDmeta information, essentially resetting it to the default. I'll update the documentation to make that clear.

**Comment by yujinqiu** [comment]
Thanks for your reply, and what I care about is there any way to actually delete tag key and value ? I read  documents but cannot find the way out.
