### ISSUE TITLE
How does OpenTSDB handle gaps in the data?

### ISSUE THREAD

**Issue by ebereketoglu** [OpenTSDB/opentsdb#478]
OpenTSDB does not store datapoints indepently. But some time series don't always have data points or sometimes the data interval can change.
How does it handle these gaps and interval changes? 

"Row Key - Row keys are byte arrays comprised of the metric UID, a base timestamp and the UID for tagk/v pairs: <metric_uid><timestamp><tagk1><tagv1>[...<tagkN><tagvN>]. By default, UIDs are encoded on 3 bytes.
The timestamp is a Unix epoch value in seconds encoded on 4 bytes. Rows are broken up into hour increments, reflected by the timestamp in each row. Thus each timestamp will be normalized to an hour value, e.g. 2013-01-01 08:00:00. This is to avoid stuffing too many data points in a single row as that would affect region distribution. Also, since HBase sorts on the row key, data for the same metric and time bucket, but with different tags, will be grouped together for efficient queries."

Thanks,
Erdinc

**Comment by IzakMarais** [comment]
> How does OpenTSDB handle gaps in the data

Can you explain a little more what aspect you are uncertain of? Like your quote explained, each datapoint is stored with a timestamp; this means gaps are not a problem, since there is no implicit assumption about expected intervals or gaps.

**Comment by ebereketoglu** [comment]
As I understand OpenTSDB stores data like the below structure.
[base timestamp] <value1><value2>.......<valueN>
And it is calculating actual timestamp for each value adding interval between datapoints to base timestamp. 
For example we have sensors and we are reading temperature value from this sensors per 10 minutes.
The temperature series will be like  
2013-01-01 08:00:00 - 23  - 21 - 30 ......

Actual time stamps for these temperatures are :

2013-01-01 08:00:00 - 23
2013-01-01 08:10:00 - 21
2013-01-01 08:20:00 - 30

But the problem occurs if we change the interval or don't send data for a while. For example after 30 value we change the interval as 1 minute. And after 40 value we don't send data for an hour and send 25 value. The storage will be like that:

2013-01-01 08:00:00 - 23  - 21 - 30 - 35 - 40 - 25

Actual time stamps for these temperatures should be:
2013-01-01 08:00:00 - 23
2013-01-01 08:10:00 - 21
2013-01-01 08:20:00 - 30
2013-01-01 08:21:00 - 35
2013-01-01 08:22:00 - 40
2013-01-01 09:22:00 - 40

If I understand correctly the storage structure of OpenTSDB, how it can handle these changes?

Thanks,
Erdinc

**Comment by IzakMarais** [comment]
It seems you are concerned about the underlying way OpenTSDB stores data in Hbase. This is abstracted away from the client of OpenTSDB. All you have worry about is that you supply a timestamp for each point you submit. OpenTSDB will handle it correctly.

Also, in future I suspect questions like these should be posed to the [google group](https://groups.google.com/forum/#!forum/opentsdb) rather than creating a github-issue.

**Comment by ebereketoglu** [comment]
Ok, I understand, thank you.

**Comment by manolama** [comment]
Just to clarify the storage format, we do store the exact timestamp for every value using the qualifier of the column. Each column has a qualifier with an offset from the row's base timestamp so when you retrieve the data, you get the original timestamp back, regardless of missing data. http://opentsdb.net/docs/build/html/user_guide/backends/hbase.html

**Comment by ebereketoglu** [comment]
Thank you for clarifying,  I also found this video and I understand the data structure clearly.
https://www.youtube.com/watch?v=WlsyqhrhRZA&feature=youtu.be
