### ISSUE TITLE
no JDK found - please set JAVA_HOME

### ISSUE THREAD

**Issue by ebereketoglu** [OpenTSDB/opentsdb#480]
I installed the java 8 and set the JAVA_HOME but when I try to start the opentsdb service, I'm getting the 'no JDK found - please set JAVA_HOME' error.  
![opentsdb_error](https://cloud.githubusercontent.com/assets/10550625/6971910/199dad30-d93d-11e4-97eb-45d953ba0320.PNG)

**Comment by ebereketoglu** [comment]
In the init script java 8 path has not been added. I added JAVA_HOME path for Java 8 into init script and the opentsdb service is running now. Does not support opentsdb java 8? Should I use java7?

JDK_DIRS="/usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-7-openjdk \
/usr/lib/jvm/java-7-openjdk-amd64/ /usr/lib/jvm/java-7-openjdk-i386/ \
/usr/lib/jvm/java-6-sun /usr/lib/jvm/java-6-openjdk \
/usr/lib/jvm/java-6-openjdk-amd64 /usr/lib/jvm/java-6-openjdk-i386 \
/usr/lib/jvm/default-java"

**Comment by cikeGit** [comment]
what  is Solution？ friend！

**Comment by cikeGit** [comment]
I fix the problem . the solution is following :
` vim /usr/share/opentsdb/bin/tsdb
#JAVA=${JAVA-'java'} #annotation
JAVA=$JAVA_HOME/bin/java #add after JAVA=${JAVA-'java'}

export JAVA_HOME=/usr/local/jdk1.8.0_112 # modfiy , before: export JAVA_HOME `

**Comment by wingyiu** [comment]
+1
