### ISSUE TITLE
Topology Question - tcollector to data center based openTSDB/Hbase

### ISSUE THREAD

**Issue by kkossack** [OpenTSDB/opentsdb#484]
Has anyone tried doing remote tcollector/scollector logging to a data center based openTSDB(s) and hbase cluster? We would prefer to centralize our openTSDB/hbase environment with remote tcollectors over WAN.

Any issues found / concerns? Configuration hints?

Thanks.

**Comment by mxk1235** [comment]
I am also interested in this topic.  We were also considering an write-only opentsdb instance that would point to hbase in a different datacenter, but initial tests showed that this is probably too slow.

**Comment by tcolgate** [comment]
I've got 3 datacenters logging to a tsdb/hbase instance hosted in one of them with no problems. Network profile of tcollector is pretty light (especially with dedupe). Where are you expecting problems? I've co-located the tsdb install with the hbase master, I've got 130'ish hosts doing about 7000 datapoints/s in total, and am not sure I'd want the tsdb -> hbase just between two hosts over any real distance. I guess a per-dc tsd talking back to hbase might be OK but I can't see any huge advantage.

Securing a single port for tsdb seems preferable to having to have tsdb's talking over a wan to zk and hbase, but that's just a peronsal taste thing.

**Comment by kkossack** [comment]
Good to learn about the write-only approach being too slow.

**Comment by manolama** [comment]
TSD to HBase across a WAN will likely be pretty ugly long term. I always wanted to create a little daemon that implemented the TSD API but then stored and forwarded the data over a WAN, just never got around to it. Or you could look at tweaking the output of t/scollector to write to a messaging system like Kafka or RabbitMQ with local brokers and have daemons pulling data off those busses in the same colo where the HBase and TSD clusters are.

**Comment by johann8384** [comment]
You could use tcollector with the tco_bridge and udp_bridge collectors as this little daemon. Also there is turnbeat, which can accept tsdb data and write to kafka. And there is also this method: http://www.svds.com/brain-monitoring-kafka-opentsdb-grafana

Although I have used 4 data centers to a central TSDB without issue at two different installations.
