### ISSUE TITLE
OpenTSDB service is not starting

### ISSUE THREAD

**Issue by ebereketoglu** [OpenTSDB/opentsdb#487]
I have installed OpenTSDB on a standalone Hbase. Yesterday the database was running properly. But today opentsdb service has stopped and when I try to start it, it is printing "* Starting TSD..." but it is not starting. I checked the logs, there is not any error in log file. There are some warnings but I don't know the issue is because of those warnings. I added a screen capture.

![opentsdb](https://cloud.githubusercontent.com/assets/10550625/7075166/14cff65c-debd-11e4-82bb-66c98be22294.PNG)

**Comment by ebereketoglu** [comment]
The OpenTSDB is running on an EC2 micro instance. Can it be because of memory?

**Comment by manolama** [comment]
you can try running the tsd in the foreground. Find the install directory and run "tsdb tsd <settings>" and see if it dumps an error message that isn't captured in the log file please.

**Comment by ebereketoglu** [comment]
I upgraded my instance type and it's working now, I think it was because of the lack of memory. Thank you for response.

**Comment by sathish-hike** [comment]
I had similar issue. The problem was, my `tsd.storage.hbase.zk_quorum = x.x.x.x:2181 ` had a space at the end. Nothing came in the log.
But running tsdb directly showed it.
`/usr/share/opentsdb/bin/tsdb tsd`
