### ISSUE TITLE
TSMeta object not created when inserting multiple points the first time

### ISSUE THREAD

**Issue by lburg** [OpenTSDB/opentsdb#492]
I'm using OpenTSDB 2.1 RC2 that I compiled myself from this repo.

I'm writing a simple Python client to interact with OpenTSDB. I enabled both `tsd.core.meta.enable_realtime_uid` and `tsd.core.meta.enable_realtime_ts` to use metadata. The UID metadata is created fine when I issue a query to the `uid/assign` endpoint. However, when trying to insert some data points into my newly created metric, the TSMeta object was not created. Querying `uid/tsmeta` using both the query style parameter `m` or the regular `tsuid` gave me either an empty result, or a `BadRequestException` saying:

    Requested TSMeta did not exist

Also, I was seeing some warning in my logs:

    2015-04-14 17:29:01,466 WARN  [New I/O worker #18] TSMeta: Found a counter TSMeta column without a meta for TSUID: 050BE800000700000A
    2015-04-14 17:29:01,467 WARN  [New I/O worker #2] HttpQuery: [id: 0x81cdbb11, /194.254.61.161:40035 => /62.210.69.193:4242] Bad Request on /api/uid/tsmeta?tsuid=050BE800000700000A: Could not find Timeseries meta data

After some debugging, recompiling and adding a few calls to `LOG.info` in `src/meta/TSMeta.java`, I realized that the TSMeta object creation was skipped due to [this line](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L532):

    if (incremented_value > 1) {

I added a log call just before the if statement:

    LOG.info("incremented_value = " + incremented_value);

Here is what I saw in my logs after sending five telnet-style put commands using a Python socket:

    2015-04-14 17:48:18,137 INFO  [New I/O worker #18] TSMeta: incremented_value = 5
    2015-04-14 17:48:18,138 INFO  [New I/O worker #18] TSMeta: incremented_value = 5
    2015-04-14 17:48:18,140 INFO  [New I/O worker #18] TSMeta: incremented_value = 5
    2015-04-14 17:48:18,141 INFO  [New I/O worker #18] TSMeta: incremented_value = 5
    2015-04-14 17:48:18,142 INFO  [New I/O worker #18] TSMeta: incremented_value = 5

Since `incremented_value` is equal to 5, the function assumes that a TSMeta object was already created and thus returns early.

Isn't there another way to check for the existence of a TSMeta object? My current workaround is to add one point, wait a little, and then add the others; a bit bothersome.

**Comment by manolama** [comment]
Ah thanks for your help. It's actually due to using the ``bufferedAtomicIncrement()`` which returns the final value of all of the buffered increment calls. Switching it to the regular ``atomicIncrement()`` will solve that issue but it also puts more strain on HBase. I have code to buffer these increments in a local RocksDB instance, then flush them to HBase periodically and I'll get that upstreamed shortly. In the meantime, I'll patch this.

**Comment by manolama** [comment]
Patched in ab276c823ee082bc216951e371062d1d019652d6

**Comment by lburg** [comment]
Thanks! So to prevent overloading HBase with many writes, we shoud also deploy a RocksDB instance?

**Comment by manolama** [comment]
It depends on the load but we're pushing around 3M points per second right now and our cluster can't handle 6M at this point so hitting a local cache and flushing those periodically helps a ton.
