### ISSUE TITLE
agregation support : agg

### ISSUE THREAD

**Issue by luluprat** [OpenTSDB/opentsdb#494]
Hello, 
Are you planing to support the agg agrégation.
When you agregats for some values in a tag ( not all the values un a tag) ?

**Comment by manolama** [comment]
Yes, I have code to filter on tag values then aggregate them into a single result. It should be out in 2.2 after some input from the community.

**Comment by Misenko** [comment]
Hi, I was wandering if this functionality is available in current RC (2.2.0 RC3).
