### ISSUE TITLE
Missing info from /api/uid/tsmeta when using the metric query style

### ISSUE THREAD

**Issue by lburg** [OpenTSDB/opentsdb#498]
I'm using a version of OpenTSDB compiled straight from the `next` branch.

I have a metric named `toto` in which I added a few points through telnet. I activated the automatic creation of time series meta data objects and I want to retrieve the infos after my insertions. I issued a `GET` request using `curl`:

    curl -X GET "http://62.210.69.193:4242/api/uid/tsmeta?m=toto"

Here's what I got:

```json
[  
   {  
      "tsuid":"050BCD00000E000014",
      "metric":{  
         "uid":"050BCD",
         "type":"METRIC",
         "name":"toto",
         "description":"",
         "notes":"",
         "created":0,
         "custom":null,
         "displayName":""
      },
      "tags":[  
         {  
            "uid":"00000E",
            "type":"TAGK",
            "name":"v",
            "description":"",
            "notes":"",
            "created":1429280021,
            "custom":null,
            "displayName":""
         },
         {  
            "uid":"000014",
            "type":"TAGV",
            "name":"1",
            "description":"",
            "notes":"",
            "created":1429280021,
            "custom":null,
            "displayName":""
         }
      ],
      "description":"",
      "notes":"",
      "created":1429280022,
      "units":"",
      "retention":0,
      "max":"NaN",
      "min":"NaN",
      "displayName":"",
      "dataType":"",
      "lastReceived":0,
      "totalDatapoints":0
   }
]
```

As we can see, the `lastReceived` and `totalDatapoints` keys are not filled with the correct values, which I thought was weird. I then issued a second request, this time using the TSUID style:

    curl -X GET "http://62.210.69.193:4242/api/uid/tsmeta?tsuid=050BCD00000E000014"

And this was the answer:

```json
{  
   "tsuid":"050BCD00000E000014",
   "metric":{  
      "uid":"050BCD",
      "type":"METRIC",
      "name":"toto",
      "description":"",
      "notes":"",
      "created":0,
      "custom":null,
      "displayName":""
   },
   "tags":[  
      {  
         "uid":"00000E",
         "type":"TAGK",
         "name":"v",
         "description":"",
         "notes":"",
         "created":1429280021,
         "custom":null,
         "displayName":""
      },
      {  
         "uid":"000014",
         "type":"TAGV",
         "name":"1",
         "description":"",
         "notes":"",
         "created":1429280021,
         "custom":null,
         "displayName":""
      }
   ],
   "description":"",
   "notes":"",
   "created":1429280022,
   "units":"",
   "retention":0,
   "max":"NaN",
   "min":"NaN",
   "displayName":"",
   "dataType":"",
   "lastReceived":1429280091,
   "totalDatapoints":3
}
```

This time I got all the data. After looking around, I found out that [parseFromColumn](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L403) was at fault. It's calling [parseToObject](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L409) which only loads some data, not everything, namely not `lastReceived` nor `totalDatapoints`. Looking at the comment above [getStorageJSON](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L781), I see that's expected behaviour as it says:

```
Formats the JSON output for writing to storage. It drops objects we don't
need or want to store (such as the UIDMeta objects or the total dps)
```

Shouldn't `parseFromColumn` call [getFromStorage](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L631) like [getTSMeta](https://github.com/OpenTSDB/opentsdb/blob/next/src/meta/TSMeta.java#L388), which is called when using the TSUID style query?

**Comment by manolama** [comment]
Closed with the merge in b1c32620cd008572fcf9e7ed8c9701c22eac85b2
