### ISSUE TITLE
timestamp question

### ISSUE THREAD

**Issue by louzhenyu** [OpenTSDB/opentsdb#502]
Dear all,
       I saw this from opentsdb documentation:
       Timestamps with second resolution are stored on 2 bytes while millisecond resolution are stored on 4
       how to store timestamps in 2 bytes?

**Comment by louzhenyu** [comment]
Does it mean store seconds in one hour for a metric?

**Comment by ebereketoglu** [comment]
OpenTSDB stores an offset from the  row's base timestamp(Rows are broken up into hour increments, reflected by the timestamp in each row), so when you retrieve the data. So it does not store the exact timestamp value. When you retrieve the data it gives calculate the exact timestamp from this offset

I suggeset to watch this video to understand clearly.
https://www.youtube.com/watch?v=WlsyqhrhRZA&feature=youtu.be

**Comment by louzhenyu** [comment]
Thank for your explanation!
