### ISSUE TITLE
Could user determine which tags need aggregating?

### ISSUE THREAD

**Issue by louzhenyu** [OpenTSDB/opentsdb#504]
Eg. a metric named as http.hits, tag key is 'host', value is 'A', 'B' and 'C', 
may I query the sum result whose host is 'A' or 'B'?

**Comment by ebereketoglu** [comment]
http://opentsdb.net/docs/build/html/user_guide/query/examples.html
You can find an example under the title of "Query 8 - Grouping With OR"

**Comment by manolama** [comment]
Well, #8 from the docs really groups by with a filter, so it would have a result set for A and a different result for B. I have code that I'll upstream shortly that will let you filter on A or B and aggregated the result.

**Comment by louzhenyu** [comment]
thanks
