### ISSUE TITLE
Is wrong the documentation?

### ISSUE THREAD

**Issue by louzhenyu** [OpenTSDB/opentsdb#507]
I saw below in opentsdb documentation:
Since OpenTSDB uses HBase as the storage layer, you could use strings as the row key. Following the current schema, you may have a row key that looked like sys.cpu.0.user 1292148000 host=websv01.lga.mysite.com owner=operations. Ordering would be similar to the existing schema, but now you're using up 72 bytes of storage each hour instead of 40.

but I calculated the row key length, it should be 70 bytes.

**Comment by manolama** [comment]
```
String s = "sys.cpu.0.user 1292148000 host=websv01.lga.mysite.com owner=operations";
System.out.println(s.length());
> 70
```

Thanks for checking  and you're correct :) Would you care to issue a PR against that in the opentsdb.net repo?

**Comment by louzhenyu** [comment]
ok, has PR it.
