### ISSUE TITLE
support step interpolation

### ISSUE THREAD

**Issue by michaelbironneau** [OpenTSDB/opentsdb#508]
We would like to use OpenTSDB to ingest sensor data that arrives on change of value. For example,

```
sensor.temperature 12:00:00 27.0
sensor.temperature 12:00:01 27.1
sensor.temperature 12:00:30 27.5,
```

and for us this means that the value 27.1 should be held for 29 seconds (until the next point), not that the temperature increases linearly from 27.1 to 27.5 in this time. How difficult would it be to support this type of interpolation?

Thanks

**Comment by michaelbironneau** [comment]
Have thought this through a bit more and it does involve a lot of changes, unless I'm missing something:

* 'upsampling' in addition to 'downsampling', i.e. the downsampler should use the last datapoint before the interval and the next datapoint after the interval to work out the value during the interval.
* If doing a query on an interval that contains no datapoints, need to do a lookback to find the previous datapoint and include that instead of returning nothing. This probably involves a 'lookback' parameter similar to the last_dp feature.
* Implement a custom zero-order-hold mean aggregator that does a weighted average of the points in the interval (the weights are how long the values are held for).

Have looked through the source code and have an idea of how to implement these but they're probably best broken up into separate issues/PRs and will almost definitely need some discussion, so will post to the mailing list instead.

**Comment by ranjitreddy2013** [comment]
I'm curious if this was implemented in openTSDB. We need this feature for our use case.
