### ISSUE TITLE
Request for a script to pre-split table in OpenTSDB 2.1

### ISSUE THREAD

**Issue by ghost** [OpenTSDB/opentsdb#538]
Pre-splitting help improve write performance. I would like to have a script that help to pre-split table based on: 1) number of metrics, and 2) how many time series for each metric per second (on average). The script calculates the max file size and the number of regions as needed.

**Comment by manolama** [comment]
If you search the mailing list, someone posted a link to a few lines of Ruby that will perform a super simple split, but you're right in that we should provide a fully fleshed out script.

**Comment by kramerli** [comment]
I have one as below 
################################################
```ruby
#!/usr/bin/hbase org.jruby.Main
# usage: ./create_table.rb tsdb 255
include Java
import org.apache.hadoop.hbase.HBaseConfiguration
import org.apache.hadoop.hbase.HTableDescriptor
import org.apache.hadoop.hbase.client.HBaseAdmin
import org.apache.hadoop.hbase.HColumnDescriptor

tablename = ARGV[0]
regions = ARGV[1].to_i

hcd  = HColumnDescriptor.new('t')
#hcd.COMPRESSION="COMPRESSION"
#hcd.BLOOMFILTER="BLOOMFILTER"

htd = HTableDescriptor.new(tablename)

htd.addFamily(hcd)
HBaseAdmin.new(HBaseConfiguration.new).createTable(
  htd,
  "\x00\x00\x01".to_java_bytes,
  "\x00\x03\x48".to_java_bytes,
  regions)
```

To use this. Change the "\x00\x00\x01" to the begining metric uid , change the "\x00\x03\x48" to your end metric uid.
Save it as create.rb. 
Then run ./create.rb tsdb 256 ( if you want to have 256 regions for the tsdb table)


Please correct me if any wrong with this

**Comment by jtamplin** [comment]
On Sat, Sep 5, 2015 at 2:40 AM, kramerli <notifications@github.com> wrote:

> I have one as below
> ################################################
>
> #!/usr/bin/hbase org.jruby.Main# usage: ./create_table.rb tsdb 255include Java
> import org.apache.hadoop.hbase.HBaseConfiguration
> import org.apache.hadoop.hbase.HTableDescriptor
> import org.apache.hadoop.hbase.client.HBaseAdmin
> import org.apache.hadoop.hbase.HColumnDescriptor
>
> tablename = ARGV[0]
> regions = ARGV[1].to_i
>
> hcd  = HColumnDescriptor.new('t')#hcd.COMPRESSION="COMPRESSION"#hcd.BLOOMFILTER="BLOOMFILTER"
>
> htd = HTableDescriptor.new(tablename)
>
> htd.addFamily(hcd)HBaseAdmin.new(HBaseConfiguration.new).createTable(
>   htd,
>   "\x00\x00\x01".to_java_bytes,
>   "\x00\x03\x48".to_java_bytes,
>   regions)
>
> To use this. Change the "\x00\x00\x01" to the begining metric uid , change
> the "\x00\x03\x48" to your end metric uid.
> Save it as create.rb.
> Then run ./create.rb tsdb 256 ( if you want to have 256 regions for the
> tsdb table)
>
> Please correct me if any wrong with this
>
This is only useful if you don't add any metrics.  Otherwise, the last
region grows and still has to split.  The only real solution is to size
your regions for the maximum data you will retain (and use TTL or similar
to delete old data), and then arrange to have your metric UID space use all
the key space and divide it up evenly.  We added a config flag to swap the
bytes on the UID (so they were allocated 01 00 00, 02 00 00, etc), and I
think unmodified OpenTSDB now ha an option to assign them randomly which
accomplishes the same thing.

-- 
John A. Tamplin

**Comment by mxk1235** [comment]
how can we find out what the beginning and ending metric uid are in a running hbase?

**Comment by mxk1235** [comment]
@manolama  ping, can i get answers to my questions?  i really would like to take advantage of this but not sure how big of an item this is going to be and trying to plan.

**Comment by johann8384** [comment]
@mzk1235 I use one similar to the one proposed by @kramerli. I just guess how many we'll need in advance. I usually set it for for 300,000 or so.

**Comment by xiongsenlin** [comment]
I don't understand the clause: "\x00\x03\x48".to_java_bytes above, metric uids are encoded  on 3 bytes in the rowey, but "\x00\x03\x48".to_java_bytes results in more than 3 bytes, what's going on?

**Comment by xiongsenlin** [comment]
Here is the java code, it works fine for me.


import org.apache.hadoop.hbase.util.Bytes;

/**
 * Created by xiongsenlin on 16/7/12.
 */
public class OpentsdbPreSplitter {
    private static int METRIC_WIDTH = 3;
    
    public static byte[][] generate(int metricUidStart,
                                    int metricUidEnd, 
                                    int regionNum) {
        if (metricUidStart <= 0 || metricUidEnd <= 0 || regionNum <= 0) {
            throw new IllegalArgumentException("params can not be negative");
        }
        if (metricUidEnd < metricUidStart) {
            throw new IllegalArgumentException("end can not be less than start");
        }
        
        byte[] start = long2bytes(metricUidStart);
        byte[] end = long2bytes(metricUidEnd);
        
        return splits(start, end, regionNum - 1);
    }
    
    private static byte[] long2bytes(long n) {
        byte[] b = new byte[8];
        setLong(b, n);

        byte[] result = new byte[METRIC_WIDTH];
        System.arraycopy(b, 8 - METRIC_WIDTH, result, 0, METRIC_WIDTH);

        return result;
    }

    private static void setLong(byte[] b, long n) {
        b[0] = (byte) ((int) (n >>> 56));
        b[1] = (byte) ((int) (n >>> 48));
        b[2] = (byte) ((int) (n >>> 40));
        b[3] = (byte) ((int) (n >>> 32));
        b[4] = (byte) ((int) (n >>> 24));
        b[5] = (byte) ((int) (n >>> 16));
        b[6] = (byte) ((int) (n >>> 8));
        b[7] = (byte) ((int) (n >>> 0));
    }

    private static byte[][] splits(byte[] start, byte[] end, int num) {
        return  Bytes.split(start, end, num);
    }

    public static void main(String[] args) {
        generate(0, 300000, 200);
    }
}

**Comment by xiongsenlin** [comment]
Java code is as follows, it works fine for me.
`
import org.apache.hadoop.hbase.util.Bytes;

/**
 * Created by xiongsenlin on 16/7/12.
 */
public class OpentsdbPreSplitter {
    private static int METRIC_WIDTH = 3;
    
    public static byte[][] generate(int metricUidStart,
                                    int metricUidEnd, 
                                    int regionNum) {
        if (metricUidStart <= 0 || metricUidEnd <= 0 || regionNum <= 0) {
            throw new IllegalArgumentException("params can not be negative");
        }
        if (metricUidEnd < metricUidStart) {
            throw new IllegalArgumentException("end can not be less than start");
        }
        
        byte[] start = long2bytes(metricUidStart);
        byte[] end = long2bytes(metricUidEnd);
        
        return splits(start, end, regionNum - 1);
    }
    
    private static byte[] long2bytes(long n) {
        byte[] b = new byte[8];
        setLong(b, n);

        byte[] result = new byte[METRIC_WIDTH];
        System.arraycopy(b, 8 - METRIC_WIDTH, result, 0, METRIC_WIDTH);

        return result;
    }

    private static void setLong(byte[] b, long n) {
        b[0] = (byte) ((int) (n >>> 56));
        b[1] = (byte) ((int) (n >>> 48));
        b[2] = (byte) ((int) (n >>> 40));
        b[3] = (byte) ((int) (n >>> 32));
        b[4] = (byte) ((int) (n >>> 24));
        b[5] = (byte) ((int) (n >>> 16));
        b[6] = (byte) ((int) (n >>> 8));
        b[7] = (byte) ((int) (n >>> 0));
    }

    private static byte[][] splits(byte[] start, byte[] end, int num) {
        return  Bytes.split(start, end, num);
    }

    public static void main(String[] args) {
        generate(0, 300000, 200);
    }
}
`

**Comment by xiongsenlin** [comment]
#`
import org.apache.hadoop.hbase.util.Bytes;

/**
 * Created by xiongsenlin on 16/7/12.
 */
public class OpentsdbPreSplitter {
    private static int METRIC_WIDTH = 3;
    
    public static byte[][] generate(int metricUidStart,
                                    int metricUidEnd, 
                                    int regionNum) {
        if (metricUidStart <= 0 || metricUidEnd <= 0 || regionNum <= 0) {
            throw new IllegalArgumentException("params can not be negative");
        }
        if (metricUidEnd < metricUidStart) {
            throw new IllegalArgumentException("end can not be less than start");
        }
        
        byte[] start = long2bytes(metricUidStart);
        byte[] end = long2bytes(metricUidEnd);
        
        return splits(start, end, regionNum - 1);
    }
    
    private static byte[] long2bytes(long n) {
        byte[] b = new byte[8];
        setLong(b, n);

        byte[] result = new byte[METRIC_WIDTH];
        System.arraycopy(b, 8 - METRIC_WIDTH, result, 0, METRIC_WIDTH);

        return result;
    }

    private static void setLong(byte[] b, long n) {
        b[0] = (byte) ((int) (n >>> 56));
        b[1] = (byte) ((int) (n >>> 48));
        b[2] = (byte) ((int) (n >>> 40));
        b[3] = (byte) ((int) (n >>> 32));
        b[4] = (byte) ((int) (n >>> 24));
        b[5] = (byte) ((int) (n >>> 16));
        b[6] = (byte) ((int) (n >>> 8));
        b[7] = (byte) ((int) (n >>> 0));
    }

    private static byte[][] splits(byte[] start, byte[] end, int num) {
        return  Bytes.split(start, end, num);
    }

    public static void main(String[] args) {
        generate(0, 300000, 200);
    }
}
`

**Comment by IzakMarais** [comment]
To set compression, e.g. to LZO (given that you have installed compiled and installed LZO compression for HBase), replace 
`#hcd.COMPRESSION="COMPRESSION"`
with
`hcd.setCompressionType(Compression.getCompressionAlgorithmByName("lzo"))`
and add to the top
`import org.apache.hadoop.hbase.io.compress.Compression`

Tested with Hbase 0.98.
