### ISSUE TITLE
UID size

### ISSUE THREAD

**Issue by mxk1235** [OpenTSDB/opentsdb#550]
In the documentation, you mention that the size of the UID for the tagv space is configurable, but set to 3 bytes currently.   http://opentsdb.net/docs/build/html/user_guide/quickstart.html#create-your-first-metrics

I've read some advice in another thread of throwing the microsecond timestamp as a tagv, and we have played around with the idea of putting request-id into a tag, but the docs imply that it's probably not a good idea.

- Where in the code can I find the configuration for the tagv space?

- Are there significant performance implications of increasing the space to say 5 or 6 bytes?

- Is it possible to make a custom build of OpenTSDB with UID being longer than 3 bytes?

- If we upgraded all our instances to this custom build, would it be able to operate on old data, or does it have to be converted beforehand?

**Comment by manolama** [comment]
Hiya: https://github.com/OpenTSDB/opentsdb/blob/next/src/core/TSDB.java#L72-L76

* Just tweak those three numbers as you see fit from 1 to 7. 0 is plain silly and 8 is untested as it can swing negative.

* Performance shouldn't be too bad, it's mostly a matter of increased storage, heap usage and network traffic. We use 4 bytes and haven't seen any issues.

* Yep, just tweak those values in the source file and recompile. 

* Unfortunately it does have to be re-written as the schema changes with the UID sizes. You have to create new tables and read/write using the scan/import CLIs for now.
