### ISSUE TITLE
One bug in query last.html 

### ISSUE THREAD

**Issue by ansible-lee** [OpenTSDB/opentsdb#553]
In http://opentsdb.net/docs/build/html/api_http/query/last.html.
The "Requests" section include three parameters:"queries","resolve","backScan".
But in fact，After input the three parameter， TSD's log descrip "common frames omitted\nCaused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"resolve\" (class net.opentsdb.tsd.QueryRpc$LastPointQuery), not marked as ignorable (3 known properties: \"resolveNames\", \"backScan\", \"queries\"])".

Replace "resolve" to "resolveNames", this problem is resolved.

**Comment by ansible-lee** [comment]
Example: Enter "curl -i -X POST -d '{" queries ": [{" metric ":" dev.mem.used.rt "," tags ": {" host ":" standby "}}, {"metric": "dev.mem.used.rt", "tags": {"host": "active"}}], "resolve": false, "backScan": 24} '-H "Content-Type: application / json; charset = UTF-8 "http: //10.xx.xx.xx: 4242 / api / query / last?"

LOG：
{"error":{"code":400,"message":"Unable to parse the given JSON","details":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"resolve\" (class net.opentsdb.tsd.QueryRpc$LastPointQuery), not marked as ignorable (3 known properties: \"resolveNames\", \"backScan\", \"queries\"])

**Comment by manolama** [comment]
Yep, two bugs found so far, one is the documentation (should be ``resolveNames``) and the other is a map conversion. Fixing both and thanks for finding them!

**Comment by manolama** [comment]
Should be fixed in e2dc213251b5f518a90bc66f6c92f84e6b801402 and documentation has been updated. I'll likely cut a 2.1.1 shortly with these bugs fixed. Try it out and open a new bug if you still see issues. Thanks!

**Comment by JerAxxxxxxx** [comment]
@manolama
When I was using opentsdb, I also encountered this problem.
"Unable to parse the given JSON","details":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException
The version I am using 2.3.1 , the situation is similar to the brother above, I am going to crash.
