### ISSUE TITLE
What if UID reaches max value?

### ISSUE THREAD

**Issue by MichaelScofield** [OpenTSDB/opentsdb#555]
I'm designing a long running monitor system based on OpenTSDB. It will be fed with all kinds of metrics from time to time.

Since UIDs are auto incremented, what happen if UID reaches max value(about 16M)? Will it throw an error? If so, how to recover from it? Or will it restart counting from 0 and replace the old metric/tagk/tagv?

Thx! :-)

**Comment by manolama** [comment]
Hi, it will throw an error any time a new UID needs to be assigned, so at the 16Mth or so metric, tagk or tagv it won't allow you to assign any new UIDs. Existing metrics, tagks and tagvs can be used and any new combination thereof. At the point where you run out of UIDs your choices are:

* Manually rename some old strings that you aren't using any more. That's a pain.
* Bump the UID limit up in the TSDB code and setup new HBase tables, then read and write from the old to the new.

If you are expecting a ton of UIDs to be used, make sure to bump the limits up before you start writing.

**Comment by MichaelScofield** [comment]
Thanks @manolama. The problem we are encountering is that we cannot really estimate how much UIDs that will be assigned, since we are designing a monitoring platform system anyone can use.

So the 2 choices:
- Manually rename is a pain, and not operational in real production system;
- Transfer the data from old to new require a full system wide service halt for a period of time, while we expect 24x7 availability.

Does OpenTSDB currently (or in the future) provide some configs that can automatically expand the UID limitation?

**Comment by manolama** [comment]
Unfortunately there is no way to automatically expand the UID. Changing the UID size requires creating a new set of tables, then copying data from the old into the new. The reason being that parsing the row keys depends on consistent tag lengths. But we are planning to make the UID schema pluggable so that in the future we may allow straight strings or something like that for folks who have tons of storage.

**Comment by MichaelScofield** [comment]
Thx! That answer my question!
