### ISSUE TITLE
OpenTSDB How to find out TSUID of datapoint

### ISSUE THREAD

**Issue by Johnathon332** [OpenTSDB/opentsdb#561]
I am trying to use the HTTP API to query opentsdb for metrics. However in the opentsdb documentation it mentions that if you query via metric name and there are multiple metrics with the same metric name it will aggregate the results. However I want to return these results as separate values rather than aggregated. I believe the only way to do this is to give the query a list of TSUID values. The problem I am now facing is I am not sure how to acquire these values.

http://opentsdb.net/docs/build/html/api_http/query/index.html

**Comment by manolama** [comment]
Hiya, just use the ``showTSUIDs`` flag in your query and it will print out the list of unique time series aggregated in your results.

**Comment by Johnathon332** [comment]
Is there a way to do this beforehand if you know what the metric name and tags are?

**Comment by IDerr** [comment]
Hi @Johnathon332 
if your question has been answered, could you please close this issue.

Thanks a lot :)
