### ISSUE TITLE
/api/search/lookup returning incomplete data

### ISSUE THREAD

**Issue by heaje** [OpenTSDB/opentsdb#570]
This may or may not be related to https://github.com/OpenTSDB/opentsdb/issues/568.  If it is, please forgive me.

I'm having an odd problem when using OpenTSDB (2.1.0 and 2.2.0RC1) with 4 byte UIDs (metric, tagk, and tagv).  The tsdb-meta table gets populated (either using metasync or tsd.core.meta.enable_realtime_ts), but when I use the /api/search/lookup endpoint, only a very, very small subset (if any at all) of the data is actually searchable.

I can do a query like "/api/search/lookup?m={host=}&limit=50000" and only get metadata for 5 hosts, but I have 200+ tag values for the host tag.  If I then turn around and try to run a query like "/api/search/lookup?m={host=host_that_had_results}&limit=50000", I'll get nothing returned for the host, even though the previous query showed there was metadata.  The same results occur when I use the CLI "tsdb search" command.

I've tried this with both v2.1.0 (recompiled with 4-byte UIDs) and v2.2.0RC1 (compiled with 4-byte UIDs and also just using the configuration options for UID width).  I get the exact same result in all three cases.

This problem does not exist at all if I use 3-byte UIDs.

I am running CDH 5.4.5 for hbase/hadoop/zookeeper/etc.  CDH 5.4.1 has this same problem.

**Comment by manolama** [comment]
This should be fixed with #568, please give it a try and reopen if needed. Thanks!
