### ISSUE TITLE
Error "no JDK found - please set JAVA_HOME"

### ISSUE THREAD

**Issue by floyd-may** [OpenTSDB/opentsdb#579]
I installed the .deb package for the 2.1.1 release, expecting to run it atop an install of openjdk-8-jre. I receive this error message on attempting to start the opentsdb service:

`no JDK found - please set JAVA_HOME`

I'm confused by this error message for a couple reasons. First, I'm confused that a system service is asking for an environment variable to be set. Next, the [installation guide](http://opentsdb.net/docs/build/html/installation.html) indicates that I need a JRE, not a JDK.

#480 was closed with no apparent solution. What's the right solution here? Do I need a JDK, or just a JRE? Is version 8 unsupported? Why isn't it looking in `/usr/bin`?

**Comment by timurb** [comment]
I use the following script to run OpenTSDB with Oracle JDK 8 under runit and it works like a charm (haven't tried it with OpenJDK nor with JRE though):
```
# Autodetect JAVA_HOME if not defined
. /usr/lib/bigtop-utils/bigtop-detect-javahome

HBASE_HOME=/usr/lib/hbase

exec 2>&1

exec chpst -u opentsdb \
  /usr/share/opentsdb/bin/tsdb tsd
```

If you are using upstart or systemd it should be easy to port the script to these. If you are using vanilla init.d script you probably should define JAVA_HOME somewhere in sourced configs or use `bigtop-java-home` for detecting it.

**Comment by floyd-may** [comment]
Okay, I think I've found a solution. I'm running opentsdb via init.d (installed from the .deb package). The init.d script [sources /etc/default/opentsdb if it exists](https://github.com/OpenTSDB/opentsdb/blob/master/build-aux/deb/init.d/opentsdb#L45). Putting a file there via my config management system (SaltStack) containing this:

```
export JAVA_HOME=/lib
```

seems to fix the issue.

**Comment by cikeGit** [comment]
I fix  the  problem . the solution is following :  
`  vim   /usr/share/opentsdb/bin/tsdb
#JAVA=${JAVA-'java'}     #annotation
 JAVA=$JAVA_HOME/bin/java   #add after JAVA=${JAVA-'java'} 
	  
 export JAVA_HOME=/usr/local/jdk1.8.0_112   # modfiy , before: export JAVA_HOME     `

**Comment by xiashiwendao** [comment]
just fix it by change /etc/init.d/opentsdb

add or override "JDK_DIRS=XXX" for you JDK folder(at least in v2.4.1 can use it).

In the file(opentsdb), you can may find the JDK_DIRS default defination no one suit for u.
