### ISSUE TITLE
Opentsdb tree: Unable to locate branch

### ISSUE THREAD

**Issue by wangy1931** [OpenTSDB/opentsdb#584]
I follow the document to create the tree, rule and enabled it. The rule is simply use "." as separator on metric name. Issue http://localhost:4242/api/tree got back response just fine, as following:

[{"name":"roottree","description":"","notes":"","enabled":true,"rules":{"0":{"0":{"type":"METRIC","field":"","regex":"","separator":".","description":"","notes":"","level":0,"order":0,"treeId":1,"customField":"","regexGroupIdx":0,"displayFormat":""}}},"created":1444322555,"treeId":1,"strictMatch":false,"storeFailures":false}]

manually run treesync without any error
./tsdb uid treesync --config=/etc/opentsdb/opentsdb.conf

however, if I issue branch api http://localhost:4242/api/tree/branch?treeid=1 , got back (top of the error stack)
{"error":{"code":404,"message":"Unable to locate branch '0001' for tree '1'","trace":"net.opentsdb.tsd.BadRequestException: Unable to locate branch '0001' for tree '1'\n\tat net.opentsdb.tsd.TreeRpc.handleBranch(TreeRpc.java:239) ~[tsdb-2.1.0.jar:248fee6]\n\tat net.opentsdb.tsd.TreeRpc.execute(TreeRpc.java:63) ~[tsdb-2.1.0.jar:248fee6]\n\tat net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:273) [tsdb-2.1.0.jar:248fee6]\n\tat net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:180) [tsdb-2.1.0.jar:248fee6]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]\n\t

where did I miss?

**Comment by wangy1931** [comment]
After turned on all the meta related config flag, now I at least can see some output from treesync, however there are bunch of 

2015-10-09 15:51:48,976 WARN  [New I/O worker #1] TreeBuilder: Processed TSUID [000046000001000001] resulted in a null branch on tree: 1

http://localhost:4242/api/tree/branch?treeid=1

shows an empty branch

{"leaves":null,"branches":null,"path":{"0":"ROOT"},"displayName":"ROOT","treeId":1,"branchId":"0001","depth":0}

**Comment by wangy1931** [comment]
Turns out 2.1 document about creating rule example is wrong. The "separator=." should be "separator=\." since it is used in java String.split, which treat the pass-in as regex. "." needs to be escaped.

Can someone with permission to update document corrects it so that save others time to debug?

http://localhost:4242/api/tree/rule?treeid=1&level=0&order=0&type=METRIC&separator=\.&method_override=post

**Comment by manolama** [comment]
Ah thanks a ton for finding that. I'll update the docs

**Comment by manolama** [comment]
Updated, thanks!
