### ISSUE TITLE
batch import do not support salting?

### ISSUE THREAD

**Issue by juliennju** [OpenTSDB/opentsdb#585]
We changed our opentsdb version to 2.2.0-rc1 for salting yesterday, and batch import old metrics, but I found these metrics were not salted, and in src RowKey.prefixKeyWithSalt() is not called by IncomingDataPoints.class.

**Comment by manolama** [comment]
Yeah, an oversight, sorry! Fix on the way.

**Comment by manolama** [comment]
Fixed with 3cf9efbda8de321072c039d41e33830cc71de80b

**Comment by rgazaryants** [comment]
Can anyone confirm this fixed?
