### ISSUE TITLE
first command of telnet put never works

### ISSUE THREAD

**Issue by HitmanDeCoder** [OpenTSDB/opentsdb#593]
Hi, I tried sending data to opentsdb using telnet put command. What I found that first command, be it put or help, never works . It shows "unknown command: ÿûÿû". After first attempt, it works fine.
   I am observing same pattern when writing from java socket program (works with DataOutputStream).

thanks,

**Comment by RonPoon** [comment]
http://stackoverflow.com/questions/10099138/telnet-server-returning-strange-characters

This may help.

**Comment by HitmanDeCoder** [comment]
I am using putty telnet interface to connect. So this solution will not work

**Comment by RonPoon** [comment]
If you use putty to send command to opentsdb, I suggest you to try nc, it works for me.

$ get_traffic_script.py | /usr/bin/nc {my_opentsdb_host} 4242

**Comment by manolama** [comment]
TSDB accepts data over a raw socket in a format similar to Telnet but it does not implement the full Telnet protocol. Therefore make sure you use a raw socket that does not inject any extra handshake data. I think using the built-in Windows telnet client works fine (haven't tried TSD on Windows in about a year) so you could look at that as an alternative to Putty. Or if you are using Java then just open a raw socket and don't try to use a Telnet implementation.

**Comment by manolama** [comment]
Closing for now as it has to do with the Telnet client used, not TSDB itself.
