### ISSUE TITLE
tsdb import from stdin

### ISSUE THREAD

**Issue by rgazaryants** [OpenTSDB/opentsdb#596]
I don't think it's currently supported (I couldn't get it to work anyway), but would be nice to be able to run a `scan --import` & pipe it to a `tsdb import` with a different `--config`. I think data migration will be more common these days with the new features in 2.2. Handling hundreds of 100+gb compressed exports is not ideal for large data sets, as is our case.

**Comment by manolama** [comment]
That could be useful. A simple solution would be to pipe the output to a script that would read stdin and write to the TSD via telnet or http.

**Comment by rgazaryants** [comment]
Yeah. Right now I'm doing variations of:
```tsdb scan --import 2015/01/01 2015/12/31 sum proc.stat.cpu  | while read i; do echo "put $i";done | nc -w 30 another-opentsdbwriter 4242"```

This requires logging level set to ERROR on all so that you don't get unwanted output from the scan.

**Comment by hynd** [comment]
Sounds like this would be solved by PR #580?

**Comment by rgazaryants** [comment]
Will that be pulled in? Looks to be short & sweet.

**Comment by johann8384** [comment]
Merged in #580
