### ISSUE TITLE
Pluggable storage implementations

### ISSUE THREAD

**Issue by dlmarion** [OpenTSDB/opentsdb#597]
Has any thought been given to creating an interface for storing and querying data points? I'm currently testing with a fork of the OpenTSDB next branch that has been modified to read and write to a different storage engine. I think that I can get better write and query speeds by changing the key structure, but I would rather not continue working with a one-off. I would much rather understand the contract needed for write, query, compaction, etc and then provide an implementation.

**Comment by manolama** [comment]
Yeah we definitely want to create a good storage abstraction layer. A group working on the Cassandra port has already started on one but I'm not sure where it stands yet.

The easiest way right now is to provide an alternate implementation of the ``HBaseClient ``. Pythian's doing that with Google's Bigtable cloud API right now in https://github.com/OpenTSDB/asyncbigtable. I've also been hacking together a Cassandra implementation that I'll put up soon.

For the long term if you want to come up with a contract and submit it I'd be happy to review. Thanks!

**Comment by dlmarion** [comment]
Thanks for getting back to me. I am running into a StackOverflowError also, maybe the same as [1]. Do you think the resolution to that will cause a major change in the HBaseClient API?

[1] https://github.com/OpenTSDB/opentsdb/issues/334

**Comment by IDerr** [comment]
Hi @dlmarion 
if your question has been answered, could you please close this issue.

Thanks a lot :)
