### ISSUE TITLE
Incorrect handling of the fields in built-in GUI causes Bad Request

### ISSUE THREAD

**Issue by nhahtdh** [OpenTSDB/opentsdb#600]
This happens on many fields in the GUI. So far, I have confirmed this bug on 2 fields:

- Tag value field
- The Range field on the Axes tab.

Let's use the tag value field as example. Let's say we want to filter the time series to a specific host:

![](https://cloud.githubusercontent.com/assets/564162/10756506/13b928fc-7cd7-11e5-893d-c39220a0ecd8.png)

Then we type the name of the host or use the autocomplete feature to specify the host.

However, as soon as the tag value field is out of focus (by clicking outside the tag value input box, or use Tab to navigate to other field), the data in the fields get percentage escaped and mangled with the metric field:

![](https://cloud.githubusercontent.com/assets/564162/10756667/2038895a-7cd8-11e5-81da-fdfc99863a06.png)

Clicking on the address bar and pressing Enter to reload the page allow us to workaround this bug and view the graph. However, this is extremely cumbersome.

### Environment information

- Browser: Firefox 41.0.2 on Windows
- OpenTSDB version [2.1.1] built from revision 383df1b in a MINT state, on RHEL
- Python 2.6.6
- gnuplot 4.2 patchlevel 6

**Comment by manolama** [comment]
Yeah, Firefox changed their URL behavior and that surfaced an error in TSDB that was patched in 13c86109309dff393cf5921bbef0a5eb8759886e. If you build from ``next`` you should be good to go. It will be part of the 2.2 release and I may port it to 2.1.2 if it works well.

**Comment by eswdd** [comment]
Have noticed this on Firefox 42.0 on WIndows too. In my case it manifests first in the range on the y1 axis which gets inserted as `%5B0:%5D` which it looks like the current fix won't resolve?

**Comment by manolama** [comment]
@eswdd Good call, just cut 2.1.2.
