### ISSUE TITLE
Release request: v2.2.0RC2

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#605]
@manolama  - Can v2.2.0RC2 be released from the master branch, please? We need the /api/search/lookup fix to be available.

OpenTSDB/opentsdb@c4225ff

Thanks

**Comment by manolama** [comment]
I'll have an RC2 ready this weekend hopefully which will include that fix. Otherwise it should be good in 2.1.1. Could you try that one out please?

**Comment by utkarshcmu** [comment]
lookup API is good in 2.1.1. Thanks :)

**Comment by utkarshcmu** [comment]
@manolama - Opentsdb is way better than Graphite in terms of Scaling. We are loving it as a TSD and way happier than using Graphite. We are using Opentsdb on a 70 node HBase cluster. It has been working flawlessly. A big thanks to you and all the contributors.

Any chances of RC2 releasing today? :)

**Comment by manolama** [comment]
Thanks @utkarshcmu! I'm glad you're getting such great use from it! I'm sorry for the RC2 delay, I was a little too busy this weekend, I've been committing some fixes today to prep and I should be able to cut it tomorrow evening. Thanks!

**Comment by utkarshcmu** [comment]
@manolama Thanks for the RC2 release, closing this issue. :)
