### ISSUE TITLE
Can't downsample data in built-in GUI @tags/v2.2.0RC1

### ISSUE THREAD

**Issue by nhahtdh** [OpenTSDB/opentsdb#608]
My build steps:
```
git checkout v2.2.0RC1
./build.sh clean
cd build
make install
```

After restarting the TSD, the new field in Downsample always causes Bad request, regardless of any of the 4 options in the new field (none, nan, null, zero):

![](https://cloud.githubusercontent.com/assets/564162/10930572/1091a778-82f2-11e5-8dae-9062513a6fe8.png)

**Comment by manolama** [comment]
Hmm I couldn't reproduce it. Could you verify the proper TSD version is running? Click on the "Version" tab to make sure. Thanks!

**Comment by nhahtdh** [comment]
This is the build information:

> OpenTSDB version [2.1.1] built from revision 383df1b in a MINT state

I didn't do a `make uninstall` to clear the previous build, so I'm not sure if it's interfering with the new build.
