### ISSUE TITLE
The built-in GUI is blank due to missing s/queryui.nocache.js @v2.2.0RC2

### ISSUE THREAD

**Issue by nhahtdh** [OpenTSDB/opentsdb#611]
![](https://cloud.githubusercontent.com/assets/564162/11056307/1f448d74-87b3-11e5-8a06-109968486b4d.png)

Looking at the source and following the link to the UI script:

    <script type=text/javascript language=javascript src=s/queryui.nocache.js></script>

gives me this response:

    {"error":{"code":404,"message":"Page not found"}}

instead of `queryui()` in the previous working version v2.2.0RC1. Checking the log file:

```
2015-11-10 15:41:18,815 INFO  [New I/O worker #3] HttpQuery: [id: 0xed041541, /192.168.98.173:55330 => /192.168.94.125:4242] HTTP / done in 36ms
2015-11-10 15:41:18,849 WARN  [New I/O worker #3] HttpQuery: [id: 0xed041541, /192.168.98.173:55330 => /192.168.94.125:4242] File not found: /usr/local/share
/opentsdb/static/queryui.nocache.js (No such file or directory)
```

I do `git checkout v2.2.0RC2` and build as per usual. I have made sure to `make uninstall` the previous version, plus `make clean` and `./build.sh clean` and `rm -rf /tmp/opentsdb` to clear the cache before building.

### Environment information

- Browser: Firefox 42.0/Windows
- TSD compiled and run on RHEL 6

<s>I suspect this issue is caused by this commit https://github.com/OpenTSDB/opentsdb/commit/e1b125b8fe0cfe3a02c1ae191c53d0a05953fa6f</s>, since I can reproduce this on v2.1.2 tag and master branch 5bff570.

**Comment by manolama** [comment]
ahhh, shoot. Is there anything in /opentsdb/static on your host?

**Comment by nhahtdh** [comment]
If I remember correctly, only the `favicon.ico` is in the installation folder (`/usr/local/share
/opentsdb/static/`). The rest are missing.

**Comment by nhahtdh** [comment]
Confirmed fixed in https://github.com/OpenTSDB/opentsdb/tree/v2.2.0RC3 and https://github.com/OpenTSDB/opentsdb/tree/v2.1.3
