### ISSUE TITLE
memory leak in QueryStats.java

### ISSUE THREAD

**Issue by juliennju** [OpenTSDB/opentsdb#612]
My tsdb tagkey id is : cluster ---- 001, hostname----002

when I use /api/query to query (system.metric tags:[cluster:a, hostname:h]), QueryStats will put this query   in running_queries, and remove it by its hashcode after it ends.

but when I query (system.metric tags:[hostname:h, cluster:a]), QueryStats put this query in running_queries, but then TsdbQuery sorts key in place by tagkey id, so after query ends, QueryStats cannot remove it as its hashcode changes.

**Comment by manolama** [comment]
Which version of TSDB are you running?

**Comment by manolama** [comment]
NVM, confirmed. Fix coming.

**Comment by manolama** [comment]
Looking good in 1f6af3b235851369dbf088d9bd9153a6047f9420.
