### ISSUE TITLE
Add dependency on gnuplot in the RPM package please!!

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#617]
```
sudo rpm -Uvh opentsdb-2.2.0RC3.noarch.rpm
error: Failed dependencies:
	gnuplot is needed by opentsdb-2.2.0RC3-1.noarch
```

**Comment by vitaliyf** [comment]
What are you asking - there is already a dependency, that's what the error is saying (or see https://github.com/OpenTSDB/opentsdb/blob/master/opentsdb.spec.in#L17).  "rpm" command does not install dependencies, it'll only complain that you are missing one.

However, if you use "yum install opentsdb*.rpm" then yum will download and install necessary dependencies.

**Comment by utkarshcmu** [comment]
Got it, Thanks!!!
