### ISSUE TITLE
Return query Id/Index in showQuery response

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#620]
This is somewhat regarding #438. I see that a query object is returned if we put ```showQuery:true```. But can we also have a queryIndex or a queryId to be returned as well in the order in which the queries were sent to Opentsdb?

Thanks

**Comment by torkelo** [comment]
I througth that was the whole point of the showQuery feature, that is to have a simple id/index to match series to the query.

**Comment by manolama** [comment]
Emitting the query index wouldn't be too hard as it's already used to match the proper sub query with the result set. I'd just have to sneak it into a different field or maybe the query itself.

**Comment by utkarshcmu** [comment]
It would be great if the index can be a part of the query field. That will be awesome

**Comment by manolama** [comment]
Fixed in 31332d7077193010584c613241d000f679f7ffda
