### ISSUE TITLE
CompactionQueue - flush() there is a negative number in parentheses

### ISSUE THREAD

**Issue by liangshaopeng** [OpenTSDB/opentsdb#622]
like this 
DEBUG net.opentsdb.core.CompactionQueue - flush() took 32ms, new queue size=1672851 (-9345)  
is some wrong with this line of log?  what's this mean?

**Comment by manolama** [comment]
Took a walk through the code and the negative value is ok. It's just the difference between the new size of the queue after flush (the number of rows written while the flush was being performed) and the size of the queue when the flush started. It means the flush started when there were 1,682,196 rows originally.
