### ISSUE TITLE
Opentsdb slows down when regions are moved in HBase

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#631]
Opentsdb restart also fails after the regions are moved within HBase RS

**Comment by utkarshcmu** [comment]
The CPU goes up to 100% when HBase splits any table, especially tsdb.

**Comment by utkarshcmu** [comment]
Error - 

23:34:36.795 ERROR [CompactionQueue.call] - Failed to read a row to re-compact

**Comment by utkarshcmu** [comment]
Turned off compactions for now, let's see if Opentsdb hangs again.

**Comment by manolama** [comment]
Disabling compaction should help a lot. Look at using Appends instead as an alternatively. Also take a look at the settings I posted in https://github.com/OpenTSDB/opentsdb/issues/632 that should help with the region movement/splitting.

**Comment by utkarshcmu** [comment]
Opentsdb requires manual restarts after once in a while. I am trying to find the root cause of it. Will report back once I find it.

**Comment by utkarshcmu** [comment]
Root cause was - tsdb-meta does not split with equal load. Moved regions of tsdb-meta and Opentsdb works fine now.
