### ISSUE TITLE
The TSUID production is non-unique problem!

### ISSUE THREAD

**Issue by wuxuehong214** [OpenTSDB/opentsdb#642]
I have a timeseries.

(1) when i use uid/tsmeta post request with "create=true" paramater to produce the new tsmeta, then it produces a tsuid.

(2) when i put a timeseries datapoint  and use real-time method , then it produces a tsuid too.

In theory,the two method should have the same tsuid since the same timeseries.

In fact , two tsuid produced for the same timeseries. 

When the timeseries has two or more tags, then the tsuid may be non-unique as the different order of the tags by the two methods as above.

Here is the example:
and i have tested it in 2.1.0  2.1.1   2.1.3
![bugs](https://cloud.githubusercontent.com/assets/8855377/11489828/c310a1bc-980d-11e5-868c-5d3eb86ccd26.jpg)

**Comment by manolama** [comment]
Hmm, that's an interesting one. Could you try reproducing the same issue using simple ASCII tags please? I want to see if it lies with the UTF encoding.

**Comment by wuxuehong214** [comment]
i think   "id , 0 , ip , 172.16.71.22"   are just simple ASCII tags.

**Comment by manolama** [comment]
Ah found the issue and confirmed it. Fix on the way.
