### ISSUE TITLE
pull request #639 is required for branch "next" too, not only branch "put"

### ISSUE THREAD

**Issue by Dieken** [OpenTSDB/opentsdb#643]
AFAIK "next" is v2.2 and "put" is v2.3,  that patch is required by both branches,  I open this issue in case you missed my comment in that closed pull request.

And I guess you wrote wrong commit message in commit fb255884470597b3b4e8220b4250d75630099cdb to mention #639, actually that fixed #629 and #630  :-)

**Comment by manolama** [comment]
Doh, merged in 2b66c77a1f3024e73cb1ebe3cd4ca431d9676aa8. Thanks for catching that!
