### ISSUE TITLE
put branch: maven build is broken

### ISSUE THREAD

**Issue by sheepkiller** [OpenTSDB/opentsdb#645]
Hi,

When I try to build opentsdb with cassandra support with maven, it fails.
[INFO] Compiling 164 source files to /opentsdb/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opentsdb/src-main/net/opentsdb/core/DataPoints.java:[18,28] error: package org.hbase.async.Bytes does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[30,22] error: package org.hbase.async does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[31,22] error: package org.hbase.async does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[32,28] error: package org.hbase.async.Bytes does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[33,22] error: package org.hbase.async does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[34,22] error: package org.hbase.async does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[35,22] error: package org.hbase.async does not exist
[ERROR] /opentsdb/src-main/net/opentsdb/core/TSDB.java:[36,22] error: package org.hbase.async does not exist
[snip]

Without maven, build is successful.

Here the Dockerfile

FROM centos:7.1.1503
RUN yum install -y  epel-release\
        autoconf \
        automake \
      sysconftool.noarch \
      java-1.8.0-openjdk-devel \
      make \
      git \
      maven \
      hostname
RUN git clone https://github.com/opentsdb/opentsdb/ /opentsdb && \
    cd /opentsdb && \
    git checkout put 
WORKDIR /opentsdb
RUN ./bootstrap && \
    sh build-cassandra.sh pom.xml && \
    mvn clean compile

EXPOSE 4242

Thanks

clem

**Comment by lynchlee** [comment]
me too.
