### ISSUE TITLE
Fix for #620 not merged in next branch

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#646]
@manolama 

31332d7077193010584c613241d000f679f7ffda is not merged in next branch, which is a fix for #620. Please merge it in the "next" branch so that this is released in 2.2.0. Thanks. :)

**Comment by utkarshcmu** [comment]
Is there any timeframe currently, when will 2.2.0 be release or another RC for 2.2.0.

**Comment by manolama** [comment]
Hi, sorry since it's an API change (even though it's a teensy one) I want to release it with 2.3 as tagged in the commit. An extra field may break some user's code and I don't want to do that when in RC.

**Comment by manolama** [comment]
Back from Thanksgiving and missed my deadline but I do want to get the full 2.2.0 release out by the end of next week.
