### ISSUE TITLE
Zookeeper closing the session

### ISSUE THREAD

**Issue by shubhamagarwal003** [OpenTSDB/opentsdb#648]
Hi,
I tried to start opentsdb, but it each time it dies, since the zookeeper closes the session and it can't connect to .META region. The log messages are 

OpenTSDB Logs -

4:39:20.295 INFO  [ClientCnxn.primeConnection] - Socket connection established to 10.211.26.203:2181, initiating session
14:39:20.304 INFO  [ClientCnxn.readConnectResult] - Session establishment complete on server 10.211.26.203:2181, sessionid = 0x1515bd9bfaa0060, negotiated timeout = 5000
14:39:20.334 INFO  [HBaseClient.handleMetaZnode] - Connecting to .META. region @ 10.211.26.203:60020
14:39:20.388 INFO  [ZooKeeper.close] - Session: 0x1515bd9bfaa0060 closed
14:39:20.389 INFO  [ClientCnxn.run] - EventThread shut down
14:39:20.433 INFO  [HBaseClient.discoverRegion] - Added client for region RegionInfo(table="tsdb-meta", region_name="tsdb-meta,,1449029447518.c3b1889940bd784f29576e257ae6a9f7.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@1538234716(chan=[id: 0x77123262, /10.207.68.111:45950 => /10.211.26.203:60020], #pending_rpcs=0, #batched=0, #rpcs_inflight=1) is hosting 1 region.
14:39:20.435 INFO  [HBaseClient.discoverRegion] - Added client for region RegionInfo(table="tsdb", region_name="tsdb,,1449029357139.c3e9aaa10b589559f9add1d3d562be95.", stop_key=""), which was added to the regions cache.  Now we know that RegionClient@1538234716(chan=[id: 0x77123262, /10.207.68.111:45950 => /10.211.26.203:60020], #pending_rpcs=0, #batched=0, #rpcs_inflight=1) is hosting 2 regions.
14:39:20.442 INFO  [HBaseClient.removeClientFromCache] - Lost connection with the .META. region

Zookeeper Logs are

2015-12-02 14:39:20,299 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@793] - Connection request from old client /10.207.68.111:58788; will be dropped if server is in r-o mode
2015-12-02 14:39:20,299 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@839] - Client attempting to establish new session at /10.207.68.111:58788
2015-12-02 14:39:20,302 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@595] - Established session 0x1515bd9bfaa0060 with negotiated timeout 5000 for client /10.207.68.111:58788
2015-12-02 14:39:20,384 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@494] - Processed session termination for sessionid: 0x1515bd9bfaa0060
2015-12-02 14:39:20,388 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1001] - Closed socket connection for client /10.207.68.111:58788 which had sessionid 0x1515bd9bfaa0060

Can anyone help why this might be happening.

Thanks

**Comment by manolama** [comment]
Hello, the Zookeeper session termination is normal. AsyncHBase simply connects to ZK to find the address of the root or meta region server. Then it closes the ZK session and will reopen it later on if it needs to (e.g. if the meta region server crashes or the connection is closed due to timeout). 

The "Lost connection with the .META. region" is also normal if you're running 2.2 as it will close the connection if there hasn't been any traffic for a period of time. Though closing it after 7ms is a bit suspicious. After you see that are you able to write/read from the TSD?

**Comment by shubhamagarwal003** [comment]
Hi,
The TSD process is not even starting. Whenever I try to start it the process dies and anything suspicious (WARN or ERROR) that I found in the logs were those mention above.

OpenTSDB Logs also reports

04:03:10.729 WARN  [PluginLoader.loadPlugins] - Unable to locate any plugins of the type: net.opentsdb.query.filter.TagVFilter

If that might be helpful.
Thanks

**Comment by git-jeeva** [comment]
For any one visiting this page looking for answer:
Connecting to .META. region  followed by connection closed error could mean that the opentsdb tables are not setup by running create_table.sh.

**Comment by qgxiaozhan** [comment]
```
[HBaseClient.removeClientFromCache] - Lost connection with the .META. region . 

```

Is there any reason that cause this ?
