### ISSUE TITLE
Possible Documentation Error

### ISSUE THREAD

**Issue by CamJN** [OpenTSDB/opentsdb#649]
http://opentsdb.net/docs/build/html/user_guide/writing.html#ordering says that OpenTSDB allows for writing data for a given time series in any order you want, but everything I've read online says that's not true and datapoints must be in order for a time series.

So who's wrong? The docs or the internet at large?

**Comment by jtamplin** [comment]
On Wed, Dec 2, 2015 at 1:06 PM, Camden Narzt <notifications@github.com>
wrote:

> http://opentsdb.net/docs/build/html/user_guide/writing.html#ordering says
> that OpenTSDB allows for writing data for a given time series in any order
> you want, but everything I've read online says that's not true and
> datapoints must be in order for a time series.
>
> So who's wrong? The docs or the internet at large?
>
Shockingly, the anonymous entities on the internet are wrong.  We write
samples out of order all the time (we do use last-write-wins for duplicate
timestamps).

-- 
John A. Tamplin

**Comment by CamJN** [comment]
Well that's awesome. Solves so many problems for me.
