### ISSUE TITLE
Only one version of jar of opentsdb can be found in the maven central repository.

### ISSUE THREAD

**Issue by lynchlee** [OpenTSDB/opentsdb#652]
As I see, only one version of jar of opentsdb in the maven repository can be found, and perhaps it's not a stable version at the site: http://mvnrepository.com/artifact/net.opentsdb/opentsdb.  Is this what we want ?

**Comment by manolama** [comment]
No, I do want to get 2.1 up there then the final 2.2.0 once it's realesed.

**Comment by lynchlee** [comment]
OK

**Comment by lynchlee** [comment]
someone can close this issue ? thx ~
