### ISSUE TITLE
Space Issue

### ISSUE THREAD

**Issue by shubhamagarwal003** [OpenTSDB/opentsdb#669]
I am using OpenTSDB to store some time series data. Quite often my disk space gets filled. I was aware that there isn't too much data being pushed in the TSDB. So I tried to find what is occupying the space. I found that .tmp directories  ( ex;  /hbase/data/default/tsdb/f6384c3bfe60ba43a5d7c9e701e760b3/.tmp) are occupying a lot of space. So my question is what is the use of these .tmp directories. Can they be removed in case if there is no disk space left on the device. Or is there any better way to handle this?

**Comment by trixpan** [comment]
@shubhamagarwal003 

the folders you refer to are created by HBase not by OpenTSDB.

Anyhow, have a look here:

https://github.com/OpenTSDB/opentsdb/issues/490

And here:

http://apache-hbase.679495.n3.nabble.com/HBase-with-opentsdb-creates-huge-tmp-file-amp-runs-out-of-hdfs-space-td4067577.html

**Comment by shubhamagarwal003** [comment]
@trixpan in the links that you refer its mentioned that the problem occurs when metric-data is collected at millisecond granularity. But we are collecting data at the granularity of seconds. Can the problem occur in such a situation also?

**Comment by shubhamagarwal003** [comment]
@trixpan the links you shared suggested the workaround to turn off OpenTSDB Compaction. We have the compaction turned off ( tsd.storage.enable_compaction set to false) in opentsdb.conf. But we still faced the issue of large .tmp files.

**Comment by manolama** [comment]
Are you writing data with millisecond timestamps? http://opentsdb.net/docs/build/html/user_guide/troubleshooting.html?highlight=tmp#opentsdb-compactions-trigger-large-tmp-files-and-region-server-crashes-in-hbase

**Comment by IDerr** [comment]
Hi @shubhamagarwal003 
if your question has been answered can you close this issue please ?

Thanks
