### ISSUE TITLE
Release request 2.3 RC1

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#680]
Please release 2.3. RC1 if possible sometime in near future. Will test query matching and expressions using Grafana with that release candidate.

Thanks

**Comment by commarla** [comment]
:+1: 
It would be great.
I am waiting for the show_query feature :-)

Thanks,

**Comment by digrich** [comment]
+1

**Comment by manolama** [comment]
I'm *almost* there (really, I swear!) with 2.2 so then I can return to 2.3 and fix up a few things we found at Yahoo then cut an RC1.

**Comment by utkarshcmu** [comment]
:+1 :)

**Comment by pilgrimkst** [comment]
+1

**Comment by utkarshcmu** [comment]
@manolama Thanks for releasing 2.1.4 and 2.2.0. :)

**Comment by strotter** [comment]
+1  Great work on 2.2 btw!

**Comment by utkarshcmu** [comment]
Any news here?

**Comment by johann8384** [comment]
Targeting feature freeze and RC around March 21st.

https://groups.google.com/d/msg/opentsdb/q-XETzM189Y/bdGCLWnrCgAJ

**Comment by amalshah** [comment]
+1

**Comment by johann8384** [comment]
Just to update the thread here, I asked that the freeze be delayed about one week. Here is the list of items I am trying to work into 2.3.0:

https://github.com/OpenTSDB/opentsdb/milestones/v2.3.0

**Comment by johann8384** [comment]
The 2.3.0 milestone is closed out, we can cut the RC when @manolama returns.

**Comment by utkarshcmu** [comment]
Thanks @johann8384

**Comment by amalshah** [comment]
Is there an update on when a 2.3.0 RC1 package may be created?

**Comment by johann8384** [comment]
We're still waiting on a few more enhancements from Manolama's Yahoo! fork.

I've added an issue to the 2.3.0 milestone to reflect that.

https://github.com/OpenTSDB/opentsdb/milestones/v2.3.0

-Jonathan

**Comment by johann8384** [comment]
We're still waiting on some Yahoo! work to be merged in and in the meantime I've added a few more items to the release as they have rolled in.

So, the date for this is still not firmly defined. I apologize for the delay!

**Comment by johann8384** [comment]
Released.

**Comment by utkarshcmu** [comment]
This is awesome... Thanks @johann8384 and @manolama :)

**Comment by utkarshcmu** [comment]
Was waiting for this issue to be resolved for https://github.com/grafana/grafana/issues/1876 :)
