### ISSUE TITLE
What options to enable if I want to use /api/search/lookup API?

### ISSUE THREAD

**Issue by cannium** [OpenTSDB/opentsdb#681]
I enabled all four options, as 

```
tsd.core.meta.enable_realtime_uid
tsd.core.meta.enable_tsuid_tracking
tsd.core.meta.enable_tsuid_incrementing
tsd.core.meta.enable_realtime_ts
```

but the lookup call I issued seems hanging forever.
So I'd like to know what options should I enable if I want to get metadata like "what tag pairs I have for host=xxx"?

**Comment by cannium** [comment]
Currently I need to enable all the four options, but I think things could be improved.

**Comment by manolama** [comment]
For the lookup you really should only need 
```
tsd.core.meta.enable_tsuid_tracking
tsd.core.meta.enable_tsuid_incrementing
tsd.core.meta.enable_realtime_ts
```

Also make sure that you see data in the "tsdb-meta" table. If the lookups are really slow then you may have really high cardinality data or it's still falling back to scanning the raw table. But we certainly could improve things on this front.

**Comment by cannium** [comment]
I've read some of the related code and have a few thoughts. 
These options should be orthogonal themselves. I only need those metadata and not care about the TSUID counter but they are implemented dependently. For my use case, a get request followed by a put request if TSMeta does not exist should perform better. I'll submit patches to the master branch soon if everything goes well.

**Comment by IDerr** [comment]
Hi @cannium,
It seems that your patches has been merged, could you please close this issue ?

Thanks
