### ISSUE TITLE
2.2.0RC3 /search/lookup limit issue

### ISSUE THREAD

**Issue by mgoralczyk-viasat** [OpenTSDB/opentsdb#686]
After upgrading from 2.1.0 to 2.2.0RC3, I have noticed that when you call /search/lookup, you only get 128 total results back, no matter what limit value you set. In 2.1.0, I have verified that I would get all the results back (although it seems the limit variable had no effect in that version regardless of what you set it to).

Here is an example query:
http://myhost:4242/api/search/lookup?m=some.metric{foo=1, bar=*}&limit=200

Running this will return me 128 results at most on 2.2.0RC3. I know that there are more because I can set the bar tag to a value that was not returned and still get a valid result back that didn't originally appear. 

I have performed my tests on HBase versions 1.0.0 and 1.0.2. Is this a bug or did I not set some configuration parameter correctly? I will note that I upgraded my tag value UID size to 4 bytes in 2.2.0RC3 if that is at all relevant. 

Here are the meta settings I use:
tsd.core.meta.enable_realtime_uid = true
tsd.core.meta.enable_realtime_ts = true
tsd.core.meta.enable_tsuid_incrementing = true

Thanks in advance.

**Comment by mgoralczyk-viasat** [comment]
I think I have figured it out. In asynchbase, there is a parameter called DEFAULT_MAX_NUM_ROWS that is set to 128, hence where I am getting my limit from. 

http://tsunanet.net/~tsuna/asynchbase/api/org/hbase/async/Scanner.html#DEFAULT_MAX_NUM_ROWS

**Comment by manolama** [comment]
Hmm, but there was a patch someone issued that fixed that bug. It could be that I missed in in 2.2 and it's only in 2.1. I'll double check it here.

**Comment by manolama** [comment]
fixed in 5083a43cf9027bdb504f687d4bfe1c2313f2358d. Thanks!
