### ISSUE TITLE
Implement Service Discovery registration with Curator

### ISSUE THREAD

**Issue by johann8384** [OpenTSDB/opentsdb#688]
Turn has some services which would like to be able to discover the OpenTSDB instances running in an environment. One reason is so that we can query the TSD instance that is local to the regionserver where the data is hosted (in a non-salted setup of course).

https://curator.apache.org/curator-x-discovery/index.html

I believe this would be facilitate further integration and use cases for OpenTSDB and would not be detrimental to OpenTSDB.

**Comment by manolama** [comment]
Yeah, I'd love to see this too, particularly for query distribution.

**Comment by johann8384** [comment]
Startup plugins can be used to implement service discovery.
