### ISSUE TITLE
Skip unknown tag values in the query

### ISSUE THREAD

**Issue by bobrik** [OpenTSDB/opentsdb#690]
We want to run a query that looks like this: `mymetric{uid=a|b|c|d|e}`, where some `uid` values might not be in OpenTSDB. Right now we have to run separate query for each `uid` and it is more expensive than it could be. Having an option to skip unknown tag values would be nice.

**Comment by manolama** [comment]
Hiya, this is in 2.2 and the RCs. Just set ''tsd.query.skip_unresolved_tagvs'' to true in your config.

**Comment by bobrik** [comment]
Nice, thanks!
