### ISSUE TITLE
Logging issue : opentsdb.out not rotating

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#692]
opentsdb.log rotates but opentsdb.out does not. Is there any config to make it rotate? Or not to log into opentsdb.out at all.

**Comment by lynchlee** [comment]
see https://groups.google.com/forum/#!topic/opentsdb/dPUOc1Uca70

**Comment by utkarshcmu** [comment]
@lynchlee Thanks. :)
