### ISSUE TITLE
Specify timestamp resolution explicitly in /put request.

### ISSUE THREAD

**Issue by peetonn** [OpenTSDB/opentsdb#696]
If millisecond precision timestamps start from 0 and don't exceed 13-14 characters in length, OpenTSDB treats these timestamps as seconds instead of milliseconds.
There's a need in specifying timestamp precision explicitly in `/put` call.

**Comment by johann8384** [comment]
Using dotted notation would work. 000000000.000

I will add a test to ensure sending 0.000 and 0.001 is acceptable.
