### ISSUE TITLE
GUI is not Load balancer friendly.

### ISSUE THREAD

**Issue by aabes** [OpenTSDB/opentsdb#697]
The way that cached HTML files are generated breaks operation of the GUI behind an ELB.
The names of files generated (see below) seem to be dependent on timestamps hence not consistently named across TSDB servers. If the file name were e.g. dependent only on MD5 signature of content, this would not be an issue.

Current (on my system) files:
/usr/local/share/opentsdb/static
/usr/local/share/opentsdb/static/queryui.nocache.js
/usr/local/share/opentsdb/static/hosted.html
/usr/local/share/opentsdb/static/clear.cache.gif
/usr/local/share/opentsdb/static/EB208136B27A4C0D99D31E8F448B0054.cache.html
/usr/local/share/opentsdb/static/favicon.ico
/usr/local/share/opentsdb/static/76BACC93190E5D298F795AD0653FDC5C.cache.html
/usr/local/share/opentsdb/static/6D64D12635A6F084ED7096FC440E5C7A.cache.html
/usr/local/share/opentsdb/static/E916B6F3A080872994B7A0879D7C6995.cache.html
/usr/local/share/opentsdb/static/gwt
/usr/local/share/opentsdb/static/gwt/standard
/usr/local/share/opentsdb/static/gwt/standard/standard.css
/usr/local/share/opentsdb/static/gwt/standard/images
/usr/local/share/opentsdb/static/gwt/standard/images/splitPanelThumb.png
/usr/local/share/opentsdb/static/gwt/standard/images/vborder.png
/usr/local/share/opentsdb/static/gwt/standard/images/corner.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/vborder_blue_shadow.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/corner_dialog_topleft.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/vborder_gray_shadow.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/corner_dialog_topright.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/hborder_gray_shadow.png
/usr/local/share/opentsdb/static/gwt/standard/images/ie6/hborder_blue_shadow.png
/usr/local/share/opentsdb/static/gwt/standard/images/corner_ie6.png
/usr/local/share/opentsdb/static/gwt/standard/images/hborder.png
/usr/local/share/opentsdb/static/gwt/standard/images/hborder_ie6.png
/usr/local/share/opentsdb/static/gwt/standard/images/vborder_ie6.png
/usr/local/share/opentsdb/static/gwt/standard/standard_rtl.css
/usr/local/share/opentsdb/static/FD6FA7517E6898C6F7DBB5830F99430F.cache.html

**Comment by nickman** [comment]
I looked into this. This question on the FAQ, [What’s with all the cache/nocache stuff and weird filenames?](http://www.gwtproject.org/doc/latest/FAQ_DebuggingAndCompiling.html#What) explains it well. In short, the name of the files should only change when the underlying code changes, and the names are based on an MD5 of the source content. The naming is intended to avoid browser caching issues with the content.

**Comment by johann8384** [comment]
This is not an actual issue, the files don't change unless the code does, as @nickman pointed out, the UI does not appear to have any LB issues in my testing.
