### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by johann8384** [OpenTSDB/opentsdb#702]
set dummy "https://oss.sonatype.org/content/repositories/snapshots/org/hbase/asynchbase/1.7.1-SNAPSHOT/" "third_party/hbase/asynchbase-1.7.1-20151004.015637-1.jar"; shift; ./build-aux/fetchdep.sh "$@"
--2016-02-15 12:51:58--  https://oss.sonatype.org/content/repositories/snapshots/org/hbase/asynchbase/1.7.1-SNAPSHOT//asynchbase-1.7.1-20151004.015637-1.jar
Resolving oss.sonatype.org... 52.5.245.28, 52.7.35.94
Connecting to oss.sonatype.org|52.5.245.28|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-15 12:51:59 ERROR 404: Not Found.

make: *** [third_party/hbase/asynchbase-1.7.1-20151004.015637-1.jar] Error 8

**Comment by johann8384** [comment]
I'd be happy to setup Travis-CI to run build.sh for all Pull Requests and such. We just recently added that to the TCollector project also.

**Comment by utkarshcmu** [comment]
:+1: for Travis-CI integration

**Comment by manolama** [comment]
Travis is already setup for AsyncHBase and it's only failing under JDK 6, passing under 7. I need to find out why that's happening but it's working fine as I cut a final for 1.7.1 and uploaded it to OSS.

**Comment by manolama** [comment]
Should be good now :)
