### ISSUE TITLE
Flickering ui on 2.2.0

### ISSUE THREAD

**Issue by eswdd** [OpenTSDB/opentsdb#708]
Hiya,

Got an odd bug when using Firefox on Windows on 2.2.0. Just open this link:

http://<tsdb>:4242/#start=2h-ago&m=sum:rate:tsd.rpc.received%7Btype=put,host=*%7D&o=&yrange=%5B0:%5D&key=top%20center&wxh=1800x1000&style=linespoint

What happens is that the page loads, updates the url, but with the tags the other way round, whereupon it loads again, rendering the tags the other way round, updates the url with the tags back the first way, updates the url..... ad infinitum.

Works fine in Chrome.

Cheers
Simon

**Comment by manolama** [comment]
hmm, Do you know if it happens in 2.1.4 as well before the UI and tag handling changes? I'll take a look too.

**Comment by eswdd** [comment]
Doesn't happen in 2.1.4.

**Comment by katameru** [comment]
+1, still a problem in 2.3

**Comment by johann8384** [comment]
I was able to re-create this in the NEXT branch with Firefox on OSX

**Comment by manolama** [comment]
Ah, I can recreate it too. Ick. Working it now.

**Comment by katameru** [comment]
This is still a problem in 2.3.0, I prepared a PR.
