### ISSUE TITLE
Turn off aggregation.

### ISSUE THREAD

**Issue by mibzzz** [OpenTSDB/opentsdb#713]
Hello.
I would really appreciate your help. How can I turn off the aggregation? I don't need it. I need my original data to be shown on chart.

**Comment by manolama** [comment]
I'm working on a patch for this but in the mean time the only way is to star each of the tags associated with your metric (you can pick any aggregator). E.g.

``m=sum:my.metric{tag1=*,tag2=*....}``

**Comment by manolama** [comment]
Code committed in 47d94b8d2528ad7cf405b75faeadc993e81cb292 with the ``none`` aggregator.
