### ISSUE TITLE
Double logging

### ISSUE THREAD

**Issue by grzegorz-dubicki** [OpenTSDB/opentsdb#715]
When using RPM package v. 2.2.0 (final) and the init script from there, OpenTSDB logs the same things (but with a different format) to [${LOG_FILE}opentsdb.out](https://github.com/OpenTSDB/opentsdb/blob/master/build-aux/rpm/init.d/opentsdb#L93) and [/var/log/opentsdb.log](https://github.com/OpenTSDB/opentsdb/blob/master/build-aux/rpm/logback.xml#L22). I think that this should be disabled, for example by removing the STDOUT appender from logback.xml completely.

**Comment by manolama** [comment]
Yes, we should take the stdout from logback by default for the packages.
