### ISSUE TITLE
the "put" branch ,no ParseException and SyntaxChecker class error

### ISSUE THREAD

**Issue by zivyu** [OpenTSDB/opentsdb#726]
now ,I check out the "put" branch ,in ''net.opentsdb.query.expression.Expressions'' class  ,
on the line 20 and 21 ,import two class:

import net.opentsdb.query.expression.parser.ParseException;
import net.opentsdb.query.expression.parser.SyntaxChecker;

but under the package "net.opentsdb.query.expression" , there is no "parser" package .

**Comment by manolama** [comment]
Ah sorry, try the "next" branch. Put hasn't been updated in a little while (I need a way to mark it as inactive).
