### ISSUE TITLE
Include port as a tag in stats

### ISSUE THREAD

**Issue by sgarg7** [OpenTSDB/opentsdb#743]
I am running multiple tsds on the same host with different ports. The stats data only distinguishes metrics with host tags. Without the port tag, these metrics on the same server are writing over each other's data.

**Comment by nickman** [comment]
I can take this one if it's not a work in progress.

**Comment by johann8384** [comment]
I have not started anything on it, feel free to handle it!

**Comment by sgarg7** [comment]
No it's not. Thank you.

**Comment by nickman** [comment]
Started.
