### ISSUE TITLE
Metasync takes up increasing amount of memory

### ISSUE THREAD

**Issue by sgarg7** [OpenTSDB/opentsdb#753]
Metasync ran for 10 hours for us before it ended up taking all of the RAM and getting killed. Has anyone else experienced this?

**Comment by johann8384** [comment]
I haven't seen that yet. Can you explain a little more about environment, how you got to this point and perhaps any potentially relevant logs?

You may also want to ask on the mailing list, it is a Google group. I don't know that too many people watch the issue tracker.
