### ISSUE TITLE
Where can I download OpenTSDB 2.3 version

### ISSUE THREAD

**Issue by dilipdevaraj-sfdc** [OpenTSDB/opentsdb#762]
I am looking to try OpenTSDB with BigTable backend on Google Compute Platform. Has anyone tried that ? 
Looking at http://opentsdb.net/docs/build/html/user_guide/backends/ I see OpenTSDB 2.3 supports BigTable. Where can I download OpenTSDB 2.3  ?
I only see last release of 2.2 in http://opentsdb.net/ and https://github.com/OpenTSDB/opentsdb/releases

**Comment by johann8384** [comment]
2.3 hasn't been released yet. It is very close: https://github.com/OpenTSDB/opentsdb/milestones/v2.3.0

You can clone the "next" branch and build 2.3.0 from there. 

https://github.com/OpenTSDB/opentsdb/tree/next
