### ISSUE TITLE
typo in 2.2 document

### ISSUE THREAD

**Issue by chengweiv5** [OpenTSDB/opentsdb#767]
I think there is a typo in [the quick start](http://opentsdb.net/docs/build/html/user_guide/quickstart.html).

> New tags, on the other hand, are automatically registered whenever they're used for the first time. Right now OpenTSDB only allows you to have up to 224 = 16,777,216 different metrics, 16,777,216 different tag names and 16,777,216 different tag values. 

**224** above should be **2^24** or something means 24 times of power of 2?

**Comment by chengweiv5** [comment]
Another one in quick start guide

> The first column is a timestamp, the second the average latency for that 30 second window, 

**the second** should be **the second is**

**Comment by chengweiv5** [comment]
Another one in [writing data](http://opentsdb.net/docs/build/html/user_guide/writing.html)

> have the time series sys.cpu.user host=webserver01,cpu=0 with data written every second for 1 day, that would result in 24 rows of data. However if we have 8 possible CPU cores for that host, now we have 192 rows of data.

**every second for 1 day** above should be **every hour for 1 day** I think.

**Comment by chengweiv5** [comment]
Hi there, if the document is open sourced, I'd like submit some PR rather than issue, :smile:

**Comment by utkarshcmu** [comment]
@chengweiv5  Check this out - https://github.com/OpenTSDB/opentsdb.net

**Comment by chengweiv5** [comment]
@utkarshcmu thanks, I'll submit PR there.

**Comment by chengweiv5** [comment]
close this, see PR https://github.com/OpenTSDB/opentsdb.net/pull/84 https://github.com/OpenTSDB/opentsdb.net/pull/85
