### ISSUE TITLE
query Filters literal_or problem

### ISSUE THREAD

**Issue by youzhagui2006** [OpenTSDB/opentsdb#770]
query json:
{
    "start": "2016/04/12 04:16:00",
    "end": "2016/04/12 16:16:00",
    "queries": [
        {
            "aggregator": "avg",
            "downsample": "1h-avg",
            "filters": [
                {
                    "filter": "1000009727000|1000009727018|1000009727028|10000097270404",
                    "groupBy": false,
                    "tagk": "neId",
                    "type": "literal_or"
                }
            ],
            "metric": "150214"
        }
    ]
}
meet problem 
“No such name for 'tagv' 10000097270404”
others tagv exist 

how to solve this problem

**Comment by johann8384** [comment]
This is better handled on the mailing list: https://groups.google.com/forum/#!forum/opentsdb

The problem is that you have not created the tagv "10000097270404" and you do not have auto_create turned on.

http://opentsdb.net/docs/build/html/user_guide/configuration.html
