### ISSUE TITLE
opentsdb used more than 2000% cpu

### ISSUE THREAD

**Issue by yuyuntao** [OpenTSDB/opentsdb#777]
cpu in atop:
143125 2009% java -enableassertions -enablesystemassertions -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/var/log/tiger/tsdb_write_gc_1.log -classpath bin/..

**Comment by alburthoffman** [comment]
how is that possible? 2009%?

**Comment by johann8384** [comment]
On a Xeon E7-2870 you've got 10 cores, 20 threads. A dual CPU box would have 40 threads so in theory, 4000% CPU is available.

I'm not sure why this is an OpenTSDB Issue, perhaps if you have a question we can start a dialog on the mailing list? https://groups.google.com/forum/#!forum/opentsdb

You can also find some of us on Freenode in #OpenTSDB most of the time there is someone there.

If you are running into a problem, please feel free to re-open. Thank you!
