### ISSUE TITLE
Why was support for creating metadata from the /api/uid/tsmeta endpoint removed in 2.2?

### ISSUE THREAD

**Issue by sgarg7** [OpenTSDB/opentsdb#778]
This is a question. From the docs at http://opentsdb.net/docs/build/html/api_http/uid/tsmeta.html, the ability to create new tsmeta objects via the api was removed in OpenTSDB 2.2.
Now the only way to create metadata objects is to rely on metasync, which needs to scan the whole database. Having this endpoint would have been a convenience. What were the reasons for making this change? Isn't it a breaking change for the API?

**Comment by manolama** [comment]
You're right it is a breaking change and I probably shouldn't have made it. I think the thought was that we shouldn't have a meta object for a series that doesn't exist. I'll double check and restore it for 2.2.1.

**Comment by sgarg7** [comment]
That would be great. Thank you for the reply.

**Comment by manolama** [comment]
Restored in d951c8b9d7fb36df4bbf70356cc0cfd59e7a77b8

**Comment by sgarg7** [comment]
@manolama By the way, I wanted to make sure that the issue is not only about the creation of tsmeta objects without existing UIDs or series, but the creation of *any* tsmeta objects from the endpoint, including for existing series.

**Comment by sgarg7** [comment]
@manolama I also wanted to know if you will keep this feature in future versions. It is a useful feature for us because it reduces our dependence on metasync which takes a long time since it has to scan the whole database.

**Comment by manolama** [comment]
Ah, I don't think it will create the entry if one or more of the UIDs have not been assigned. That's something to test (if you have a sec to try it I'd appreciate it). But yeah, I think it would be fine to keep it around long-term. Just need to update the documentation now.
