### ISSUE TITLE
build opentsdb failed on mac os x

### ISSUE THREAD

**Issue by bluedesire** [OpenTSDB/opentsdb#789]
I follow the installation guide http://opentsdb.net/docs/build/html/installation.html#id1 . After I clone the source code from git, and run build.sh on mac os x Yosemite. 
The build shell reports jar checksum error.
get following output from console:

+ test -f configure
+ ./bootstrap
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build-aux
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:19: installing 'build-aux/install-sh'
configure.ac:19: installing 'build-aux/missing'
third_party/validation-api/include.mk:24: warning: variable 'VALIDATION_API_SOURCES' is defined but no program or
third_party/validation-api/include.mk:24: library has 'VALIDATION_API' as canonical name (possible typo)
Makefile.am:748:   'third_party/include.mk' included from here
third_party/include.mk:36:   'third_party/validation-api/include.mk' included from here
autoreconf: Leaving directory `.'
+ test -d build
+ mkdir build
+ cd build
+ test -f Makefile
+ ../configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for md5sum... no
checking for md5... /sbin/md5
checking for java... /usr/bin/java
checking for javac... /usr/bin/javac
checking for jar... /usr/bin/jar
checking for true... /usr/bin/true
checking for javadoc... /usr/bin/javadoc
checking for wget... no
checking for curl... /usr/bin/curl
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating opentsdb.spec
config.status: creating build-aux/fetchdep.sh
+ MAKE=make
++ uname -s
+ '[' Darwin = FreeBSD ']'
+ exec make
set dummy "http://central.maven.org/maven2/org/hbase/asynchbase/1.7.1" "third_party/hbase/asynchbase-1.7.1.jar"; shift; ./build-aux/fetchdep.sh "$@"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

error: invalid checksum for third_party/hbase/asynchbase-1.7.1.jar

error: expected: f236854721eac6d40b6710ec7d59f4a8

error:    found: d41d8cd98f00b204e9800998ecf8427e

make: *** [third_party/hbase/asynchbase-1.7.1.jar] Error 1

Anyone knows how to resolve the problem? Thanks!

**Comment by johann8384** [comment]
Here is the script I used at one point for installing the components on OSX.

https://github.com/OpenTSDB/opentsdb/blob/next/tools/osx_full_stack_install.sh

**Comment by johann8384** [comment]
It looks like the asynchbase you downloaded did not download properly.

I get the expected hash:
```
$ wget http://central.maven.org/maven2/org/hbase/asynchbase/1.7.1/asynchbase-1.7.1.jar
$ cat asynchbase-1.7.1.jar | md5sum
f236854721eac6d40b6710ec7d59f4a8
```

Perhaps remove the jar from your third_party folder and try again?
