### ISSUE TITLE
Suport gexp in UI

### ISSUE THREAD

**Issue by WangFenjin** [OpenTSDB/opentsdb#790]
Hi team,

As 2.3 RC1 released, I'm wondering if we had support on [gexp](http://opentsdb.net/docs/build/html/api_http/query/gexp.html) in OpenTSDB 2.3 UI? 

Thanks.

**Comment by johann8384** [comment]
No, there is no UI support for it. You can use the Grafana  datasource Turn
uses probably. It should be at github.com/turn/grafana, I will try to
remember to get a more specific url when I am at a computer.

**Comment by utkarshcmu** [comment]
I think this is the one which supports Expressions - https://github.com/turn/grafana/tree/v2.0.x_OpenTSDBM

**Comment by johann8384** [comment]
Looks right!

**Comment by WangFenjin** [comment]
Thanks!

I will resolve this issue.
