### ISSUE TITLE
2.3.0RC1 Query where all filters have groupBy parameter set to false fail without a response,

### ISSUE THREAD

**Issue by katameru** [OpenTSDB/opentsdb#794]
Excerpt from logs:
http://pastebin.com/1mz7HtwG

**Comment by utkarshcmu** [comment]
+1

**Comment by amalshah** [comment]
+1

**Comment by vitorboschi** [comment]
I can reproduce this problem with a query as simple as 
`m=sum:1h-sum-none:os.cpu{}{host=*}`
If I remove the first {} pair, it works fine. This worked in 2.2

**Comment by utkarshcmu** [comment]
This issue can be closed now. Opentsdb/next branch is not throwing this problem anymore. Thanks @manolama for resolving this issue.

**Comment by JimHagan** [comment]
@utkarshcmu @sdomalap Can you indicate in this diff where the fix actually is? https://github.com/OpenTSDB/opentsdb/compare/v2.3.0RC1...next

**Comment by JimHagan** [comment]
@utkarshcmu @sdomalap We can confirm this is working as well.  This can be closed.

This is the exact fix: 1409b550ae7f7fcf9c6cbe7e0dbf59c7363618ad

**Comment by bobrik** [comment]
Any news on the next RC with this fix?

**Comment by johann8384** [comment]
I think we're going to have RC2 cut in the next day or so, I'm working on the CHANGELOG
