### ISSUE TITLE
[Development] Improve the OpenTSDB Build System

### ISSUE THREAD

**Issue by utkarshcmu** [OpenTSDB/opentsdb#797]
Hello maintainers, 

I would love to contribute to OpenTSDB but setting up development environment is too complex. Is there a simpler way of setting up a local OpenTSDB environment and developing on top of it. 

This would be great for the community and we can have rapid development on the project.

**Comment by johann8384** [comment]
I recently had to help a few new OpenTSDB administrators get online and I made this script for them, it sets up OpenTSDB+HBase+TCollector in a folder on an OSX machine.

https://github.com/OpenTSDB/opentsdb/blob/next/tools/osx_full_stack_install.sh

**Comment by johann8384** [comment]
There are definitely improvements that could be made to get "a basic system" up and running locally and easily.

**Comment by utkarshcmu** [comment]
@johann8384 Thanks for pointing me to the osx script. Will give it a try ASAP. 👍

**Comment by nickman** [comment]
Tried and rejected
IMHO, the build should/could be:

1. Clone repo
2. cd opentsdb
3. mvn clean install

Debug:
4. mvn eclipse:eclipse (or idea or...)
5. Debug TSDMain with appropriate arguments

....plus 2 or 3 tweaks for releases, the Build file and other miscellany.

Works on Windows and Osx.

I get by with some scripts to create symbolic links and what-not but it
sure is a hindrance to new developers.

**Comment by johann8384** [comment]
I completely agree with you. The script wasn't meant to be a solution to this ticket, just something to help folks along as solving this ticket won't happen overnight.

**Comment by johann8384** [comment]
I renamed this Issue, basically the main feedback I've gotten from *everyone* I've worked with on OpenTSDB, and I agree completely, is that this build.sh + generated Makefile + Generated POM is awful and that we're silly for allowing it to continue as long as it has.

**Comment by nickman** [comment]
+10000000

**Comment by utkarshcmu** [comment]
If this feature request can be completed asap, more development can happen in OpenTSDB. I would love to add features to OpenTSDB. :)

**Comment by johann8384** [comment]
This is on the top of my pet project list, but I could use some help with it. Would anyone be interested in a distributed hackathon to come together for a couple of hours and try and knock this one out? I have support from @manolama to replace the current build with pure maven, and I am a comitter so we have all the authority needed to put it in.

**Comment by johann8384** [comment]
The current build system is weird, but not that hard to use, so I mean, you could develop anyway. It does not work well on windows, that is true.

**Comment by utkarshcmu** [comment]
I'll try to setup the dev environment asap (may be this weekend). If I can do some changes in the maven setup or something, I will try!
Thanks. :)

**Comment by johann8384** [comment]
I am happy to jump on a video call or something if needed to assist.

**Comment by utkarshcmu** [comment]
Sure, I will email you on this Thursday and we can agree on some time this weekend to get this done. Thanks. 👍

**Comment by nickman** [comment]
Very exciting....

**Comment by nickman** [comment]
You bet.

**Comment by utkarshcmu** [comment]
@nickman Yeah a PR would be great before we start any refactoring of the code. 👍

**Comment by manolama** [comment]
Heya folks,

So I'd like to get this into 3.0. The plan right now (please comment) is to break up TSDB into multiple libraries that can be mixed and matched similar to the Netty or GRPC projects depending on how folks want to use TSDB. A kind of rough layout would include:

- Core - A generalized time series library with interfaces/data objects for transmission as well as the various mutations (aggregations, expressions, etc) that can be performed on that data.
- Storage Base - Base storage classes such as interfaces and code shared between different storage drivers (such as the UID classes, data validation, etc). Also various exceptions.
- Storage <Driver> - Drivers for various backend stores. The HBase code would move here.
- Server base - Common classes for RPCs and hosting a TSD
- Server <Implementation> - Various implementations such as the HTTP server, GRPC server, etc.

I started the `3.0.0` branch so you can make PRs against it. Try to keep the existing /src and /test dirs as they are for a while so we can merge in the remaining PRs, 2.3 and 2.4 code along with the new 3.0 code from Y! and then we can start splitting.

Sound good? Thanks!

**Comment by utkarshcmu** [comment]
I am fine with this architecture and committing to 3.0 branch but I am looking forward to this kind of deployment of OpenTSDB:

1. Clone OpenTSDB project
2. Run Download Dependency script (Obviously one has to configure and start dependencies)
3. Maven Build
4. Configure local opentsdb.conf (Or its already populated with defaults)
5. Start TSDB command

Ideally, I would like the TSDB server to start locally in just 4/5 steps.... :)

**Comment by nickman** [comment]
Hows this ?  (at https://github.com/nickman/opentsdb/tree/put)


   1. clone / cd
   2. ./build.sh fat-jar-pom.xml
   3. mvn -f fat-jar-pom.xml -Dgpg.skip -DskipTests
   -Dmaven.javadoc.skip=true install
   4. *java -jar ./target/opentsdb-fatjar-2.4.0-SNAPSHOT-fat.jar*

*2016-10-29 12:36:34,573 INFO  [main] Main: Starting.*
*2016-10-29 12:36:34,576 INFO  [main] Main: net.opentsdb.tools BuildData
built at revision 9e45373 (MODIFIED)*
*2016-10-29 12:36:34,577 INFO  [main] Main: Built on 2016/10/29 16:23:39
+0000 by nwhitehead@Helios:/home/nwhitehead/hprojects/opentsdb*
*.........*

*2016-10-29 12:36:36,303 INFO  [main] Main: Ready to serve on /0.0.0.0:4242
<http://0.0.0.0:4242>*


Fat Jar contains all UI resources, so other than the [runtime] dependency
on gnuplot (and HBase/Zookeeper obviously) the executable jar runs
standalone.

This code is in the *put* branch, but is broken on account of some changes
since the original push request was submitted. Pull Request #899
<https://github.com/OpenTSDB/opentsdb/pull/889> fixes these issues.


On Sat, Oct 29, 2016 at 1:37 AM, Utkarsh Bhatnagar <notifications@github.com

**Comment by johann8384** [comment]
Fixed in 3.0
