### ISSUE TITLE
Inconsistency in docs on number of tags required for each metric

### ISSUE THREAD

**Issue by a-buck** [OpenTSDB/opentsdb#805]
Hello

Not sure if this is the correct place to report this trivial documentation issue but couldn't find a project for the docs.

On [this page](http://opentsdb.net/docs/build/html/user_guide/query/timeseries.html) the docs state in the first paragraph:
```
 Each time series consists of a metric plus zero or more tags associated with this metric 
```

I believe it should say 'plus one or more tags....'

**Comment by utkarshcmu** [comment]
https://github.com/OpenTSDB/opentsdb.net

**Comment by a-buck** [comment]
thanks will stick in a PR and close this issue.
