### ISSUE TITLE
How to upload .csv files in opentsdb?

### ISSUE THREAD

**Issue by SaaRaj** [OpenTSDB/opentsdb#809]
Hello 
I am new opentsdb and I had senor data in .csv format to be uploaded to opentsdb and wanted to perform some visualizations but there was no mention of how to upload the .csv data to opentsdb ?
It would be great help if someone could guide me into this issue procedure wise.

Thank you
Appreciate your help!

**Comment by johann8384** [comment]
OpenTSDB doesn't really include a built in way to just bulk load CSV files. It would not be a hard manner to iterate over the CSV with Bash, Powershell, Python, Ruby, etc and perform the inserts into OpenTSDB.
