### ISSUE TITLE
Can't find net.opentsdb.query.expression.parser in OpenTSDB 2.3.0RC1

### ISSUE THREAD

**Issue by WenhouLu** [OpenTSDB/opentsdb#811]
I found that in some classes, such as net.opentsdb.query.expression.Expression, two classes were imported:

import net.opentsdb.query.expression.parser.ParseException;
import net.opentsdb.query.expression.parser.SyntaxChecker;

But those two classes do not exist in that package.

Could you please help? Thank you.

**Comment by WenhouLu** [comment]
Solved. Found it in /build/src/net/opentsdb/query/expression/parser after running build.sh. It's quite tricky..um..For those who are using Eclipse trying to compile and run the entire project under Windows, you can first build it under Linux and then move those missing .java files to the right directory in Windows.

**Comment by nch14** [comment]
But when you do this, in eclipse, still some errors can be found, such as Token can not be resolved to a type. ParseException.java misses its import. Is there any issues for this? Or how you solve this?
