### ISSUE TITLE
How can i put the string value to the open TSDB?

### ISSUE THREAD

**Issue by Shashidhar014** [OpenTSDB/opentsdb#815]
Data specification in below link mentioned that, a numeric value to store at the given timestamp for the time series is an integer or a floating point value.

http://opentsdb.net/docs/build/html/user_guide/writing.html 

But by using api/put the value might be string,integer or float.

http://opentsdb.net/docs/build/html/api_http/put.html

Getting bad request exception, while putting string values.

How can i put the string value to the open TSDB?

**Comment by johann8384** [comment]
The value at a particular datapoint cannot be a string, it must be a float or integer, or a string that can be converted to such.

So "0.000" is OK, but "0.000p" is not.
