### ISSUE TITLE
Aggregator none in 2.3.0-RC1 has loss

### ISSUE THREAD

**Issue by chaodewen** [OpenTSDB/opentsdb#819]
I want to query row data in OpenTSDB. So I tried 2.3.0-RC1 and query with aggregator "none".
Part of my statics has been imported successfully with statements like "future.au1606 1456848000005 261.1 column=last_price".
When inserted 2 day's statics in 2016/03/01 and 2016/03/02, I can see them in the web.
![image](https://cloud.githubusercontent.com/assets/9898816/16423136/68a0f4f4-3d8d-11e6-89f0-e2e4bd0f8244.png)
**The number 108306 is right comparing to inserted.** But when I used HTTP API in my Java program.
![image](https://cloud.githubusercontent.com/assets/9898816/16423501/d824299e-3d8e-11e6-80e9-bef0aa12dac2.png)
**I found size of "dps" in the returned Json was only 61660.** It should be 108306 as above.
Please give me some suggestion to find out the solution.
By the way, it's really an important function of querying raw data in OpenTSDB.
@manolama , I'll really appreciate it, if you can help me.

**Comment by chaodewen** [comment]
Any one wants statics can send email to vaal.just@qq.com. I'll reply as soon as I can.

**Comment by chaodewen** [comment]
@manolama ，finally I found that there was a parameter "msResolution" can set output time precision as millisecond. The default output precision is second. That's why my statics lost some.
When I read the instruction about query in [http://opentsdb.net/docs/build/html/api_http/query/index.html#example-content-request](url), I found the parameter is "msResolution".
But there is another page shows the parameter is ms. That's the true one. My proper url is "http://192.168.1.163:4242/api/query?ms=true&start=1456761600000&end=1467176015966&m=none:future.au1606%7Bcolumn%3Dlast_price%7D".
![image](https://cloud.githubusercontent.com/assets/9898816/16441197/07dbbffa-3dfb-11e6-947f-830fdb32775f.png)
It's really hard to know the meaning for the web. And I hope others seeking for help about this bug can get some useful things from my words.

**Comment by johann8384** [comment]
Would you be interested in sending in a PR for the documentation improvement?

I suspect msResolution makes more sense, but if ms existed in 2.2 then we'll probably have to keep it, maybe add msResolution also and make the docs consistent to that.

**Comment by chaodewen** [comment]
I've sent a PR.😃😃😃
[https://github.com/OpenTSDB/opentsdb.net/pull/91](url)
