### ISSUE TITLE
Error using endpoint /api/query/exp

### ISSUE THREAD

**Issue by rafaelgiordano12** [OpenTSDB/opentsdb#820]
Hello @manolama,
I am facing some problems on implementing the [/api/query/exp](http://opentsdb.net/docs/build/html/api_http/query/exp.html) endpoint over HTTP protocol. Specifically, the query I have sent in the request (as shown below) causes an exception during execution. This problem is similar to the one requested in the issue #817.

```
{
    "time": {"start": "1d-ago", "aggregator": "sum"},
    "filters": {"id": "f1", "tags": []},
    "metrics": [
        {
            "filter": "f1",
            "metric": "test.a",
            "fillPolicy": {"policy": "scalar", "value": 0},
            "id": "a"
        },
        {
            "filter": "f1",
            "metric": "test.b",
            "fillPolicy": {"policy": "scalar", "value": 0},
            "id": "b"
        }
    ],
    "expressions": [
        {"expr": "a + b", "id": "ex1"},
        {"expr": "4*a + 3*b", "id": "ex2"}
    ]
}
```

The problem occurred in the OTSDB version 2.3.0-RC1. The error is always the same for any query I test using this endpoint:

>  {"error":{"code":500,"message":"Incoming data was null or empty","trace":"java.lang.IllegalArgumentException: Incoming data was null or empty\n\tat net.opentsdb.utils.JSON.parseToObject(JSON.java:103) ~[tsdb-2.3.0-RC1.jar:306603c]\n\tat net.opentsdb.tsd.QueryRpc.handleExpressionQuery(QueryRpc.java:318) ~[tsdb-2.3.0-RC1.jar:306603c]\n\tat net.opentsdb.tsd.QueryRpc.execute(QueryRpc.java:108) ~[tsdb-2.3.0-RC1.jar:306603c]\n\tat net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.3.0-RC1.jar:306603c]\n\tat net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.3.0-RC1.jar:306603c]...

Thank you in advance for your time and contribution.

**Comment by katameru** [comment]
Make sure you're actually sending the query. I saw the same error when i was trying to post an empty query by acciddent.

**Comment by rafaelgiordano12** [comment]
Hello @katameru  ,

I realized that i was trying to send data via GET method and without sending the content type. Thank you for time.
