### ISSUE TITLE
OpenTSDB Memory Leaks

### ISSUE THREAD

**Issue by shubhamagarwal003** [OpenTSDB/opentsdb#829]
We have three write instances of OpenTSDB running on VMs behind a F5 load-balancer. Our client is pushing data in OpenTSDB through telnet interface. We are also pushing data through scollector running on over 70 hosts. The VM has 8 cores and the memory allocated to OpenTSDB process is 16GB, very often we see OpenTSDB going through OutOfMemoryException and restart automatically. The logs states many connection reset between the client and OpenTSDB. Further netstat shows many connection in SYN_RECV state. Can someone help in debugging what the actual issue could be?

**Comment by johann8384** [comment]
Can you send a few details for me? 

1) What is your OpenTSDB Build Info? (/api/version)
2) What is your OpenTSDB configuration? (/api/config)

**Comment by johann8384** [comment]
A similar case on the mailing list found that setting the mode (tsd.mode) to "ro" for query nodes resolved their issue. This at least confirms that the memory leak is probably a real thing and related to code which is excluded in "ro" mode.

**Comment by mikecook** [comment]
There is an undocumented (until my PR is accepted https://github.com/OpenTSDB/opentsdb.net/pull/90 ) "wo" option that may help you troubleshoot the leak.

**Comment by olegfedoseev** [comment]
Maybe the same problem as in #542

**Comment by johann8384** [comment]
Moving to next release, waiting for info from @shubhamagarwal003

**Comment by shubhamagarwal003** [comment]
Many apologies for not able to follow up. We were using the version 2.2 build (next branch). I don't have access to the opentsdb now but I'll contact my colleague to provide you the config.

**Comment by johann8384** [comment]
Ok, we haven't cut 2.3.0 yet so I will move this back over when I get to a computer, the milestone selection isn't working on my phone.

**Comment by manolama** [comment]
@shubhamagarwal003 One of the primary causes of writers OOMing is due to HBase region splits or migration. Check your TSD stats for NSREs and check the HBase logs for splits and moves. Also try setting ``hbase.nsre.high_watermark`` to a small number like ``100``.

**Comment by nickman** [comment]
Is there a reliable way to be notified of an impending region split ? If
they're short-ish, perhaps writes could be disk buffered for the duration.

**Comment by shubhamagarwal003** [comment]
@manolama I did notice there are high NSREs. This probably occurred since there was a rolling restart of the HBase cluster, leading to a lot of regions being moved. I would set hbase.nsre.high_watermark to small value and see. Thanks

**Comment by manolama** [comment]
Closing this one for now. Ping us if you see it again. We'll likely lower that watermark in 2.4 by default.
