### ISSUE TITLE
The descriptions of query.downsample() are inconsistent between interface implement

### ISSUE THREAD

**Issue by nilday** [OpenTSDB/opentsdb#841]
In the file Query.java , the argument "interval" of method "void downsample(long interval,Aggregator downsampler)"  is describe as Number of **seconds** wnated between each data points.
But in the file of TsdbQuery.java which is the implement of Query , the same argument is describe as **milliseconds**.
This causes confusion, when I try to pass time in  second to the method but actually get milliseconds.
It's just a little description bug.

**Comment by johann8384** [comment]
Feel free to submit a PR for this, I'll merge it in. Otherwise, I'll get to it when I do a round of cleanups in the ISSUE list.
