### ISSUE TITLE
The /api/query/exp endpoint should allow for more precise configuration of join policies.

### ISSUE THREAD

**Issue by katameru** [OpenTSDB/opentsdb#843]
Currently the way output operations are executed is a) slightly confusing and b) not very flexible. For example, we currently can't compute an expression such as this:
a = http.requests{method=GET}
b = http.requests{method=*}
a/b.
Since the expression 'a' has a common tag 'method' across all data points it will be included into the tag set. In the output we will have two time series that aren't actually useful.

**Comment by manolama** [comment]
What would you expect the output to look like? A cross product? We can add another operator, right now it's just Union and Intersect as you found out. Thanks!

**Comment by katameru** [comment]
I would want the output to be a single time series that represents the ratio of GET requests to all requests.

If I understand join operators correctly (`union` is an outer join, `intersect` is an inner join), a new cross product operator (cartesian join?) wouldn't be helpful.

Instead, we could have a way to control which tags go into the tag set. In my example if we could indicate that we want to ignore the tagk `method` when joining, both time series would have the same tag set, and the result of the evaluation would give the expected result.

I can see this being problematic if ignoring a tagk would make two different time series from the same metric have the same tag set.

**Comment by gnydick** [comment]
I just want to be able to pick which tag keys map to each other. I have many different sources of data and they don't all publish the same exact tag keys, for example, one system outputs `container_name` and another just outputs `container`

**Comment by manolama** [comment]
Hi folks, this has been addressed in 3.0 now: http://opentsdb.net/docs/3x/build/html/user_guide/querynodes/join.html

**Comment by gnydick** [comment]
A lot of good that does in 3.0 when that's not what ANYONE is using.  Frankly, that's some bull-honkey to tell people to wait to use a MASSIVELY different version of the codebase.
