### ISSUE TITLE
Scalling out OpenTSDB and the UID Limit

### ISSUE THREAD

**Issue by YonoloX** [OpenTSDB/opentsdb#847]
Hello,

Does scalling out OpenTSDB leads to an increase of the UID limit?
For example, does having three instances of OpenTSB on the same HBase cluster means that it is possible to store 3*16 M uids? Or the number of uids is the same regardless of the OpenTSDB instances number ?

Thanks in advance.

**Comment by YonoloX** [comment]
I suppose no, because all the OpenTSDB instances will share the same data and metadata on Hbase, for instance the tsdb-uid table that contains the uids.

**Comment by johann8384** [comment]
It's the same across all instances. The UID limit is something you can adjust, if you do so from the start. I typically run my clusters with a UID width of 4, rather than the default 3.
