### ISSUE TITLE
how to stop tsdb?

### ISSUE THREAD

**Issue by lygn128** [OpenTSDB/opentsdb#849]
how to stop tsdb?    only kill -9 ? thank you very much;

**Comment by utkarshcmu** [comment]
```sudo service opentsdb stop``` should work if you have installed the RPM package. Which OS are you working on and how did you install Opentsdb?

**Comment by lygn128** [comment]
i build from the src，run with  nohup ./tsdb tsd &                    .  thank you

**Comment by utkarshcmu** [comment]
so, if you are running using nohup... then the only way to kill tsdb is "kill -9".

if u install RPM then u should have "sudo service opentsdb start|stop" commands for opentsdb.

**Comment by johann8384** [comment]
There is also the "diediedie" command, but I usually have that disabled, since I don't want just anyone killing off my OpenTSDB nodes.

**Comment by gregbown** [comment]
Maybe the question should be an ask. . . an example for systemd  service is provided which contains:
```
ExecStart=/usr/local/share/opentsdb/bin/tsdb tsd --config /usr/local/share/opentsdb/etc/opentsdb/opentsdb.conf --port=4242
```
However there is no corresponding ExecStop= . . . 
Please provide a way to stop opentsdb as a service,
or maybe some direction how best to do this gracefully, Thank you
