### ISSUE TITLE
Is there a way to enable_chunked on tsdb startup via param?

### ISSUE THREAD

**Issue by longtimeago** [OpenTSDB/opentsdb#852]
I see many params don't have CLI analogues in CLI.
Is that true or the doc is simply outdated?

**Comment by johann8384** [comment]
Not all configuration parameters were given CLI options. This was intentional, but a CLI option could be added for just about anything.

**Comment by johann8384** [comment]
This would be the definitive list of CLI options: https://github.com/OpenTSDB/opentsdb/blob/next/src/tools/CliOptions.java#L119
