### ISSUE TITLE
how to get EXACT downsampled result?

### ISSUE THREAD

**Issue by just2d** [OpenTSDB/opentsdb#853]
version: 2.2.0
my timezone: UTC +08:00

I want to query the total count every 8 hours from 2016-08-22 00:00:00 to  2016-08-23 00:00:00.
[http://localhost:4242/api/query?start=1471795200&end=1471881600&m=zimsum:8h-zimsum-zero:key_f0f577c0](http://localhost:4242/api/query?start=1471795200&end=1471881600&m=zimsum:8h-zimsum-zero:key_f0f577c0)

The expected result should be 3 points:
2016-08-22 08:00:00 {the accumulated count from 2016-08-22 00:00:00 to 2016-08-22 08:00:00 }
2016-08-22 16:00:00 {the accumulated count from 2016-08-22 08:00:00 to 2016-08-22 16:00:00 }
2016-08-23 00:00:00 {the accumulated count from 2016-08-22 16:00:00 to 2016-08-23 00:00:00 }

but I got 4 points:
2016-08-22 00:00:00 {count1} 
2016-08-22 08:00:00 {count2} 
2016-08-22 16:00:00 {count3} 
2016-08-23 00:00:00 {count4}
what's the meaning of these four points?

and one more:
[http://localhost:4242/api/query?start=1471795200&end=1471968000&m=zimsum:24h-zimsum-zero:key_f0f577c0](http://localhost:4242/api/query?start=1471795200&end=1471968000&m=zimsum:24h-zimsum-zero:key_f0f577c0)
from 2016-08-22 00:00:00 to  2016-08-24 00:00:00 every 24 hours, there should be 2 points:
2016-08-23 00:00:00  {the count from 2016-08-22 00:00:00 to 2016-08-23 00:00:00}
2016-08-24 00:00:00  {the count from 2016-08-23 00:00:00 to 2016-08-24 00:00:00}

but I got:
2016-08-22 08:00:00 {what's the count meaning?}
2016-08-23 08:00:00 {what's the count meaning?}

Can anyone help to explain the logic how OpenTSDB downsample points exactly? how can I get the expected results?

**Comment by johann8384** [comment]
This is because in order to do interpolation, it has to scan a little before the start of the query. Most users just discard the extra points.

**Comment by johann8384** [comment]
http://opentsdb.net/faq.html
> Why does OpenTSDB return more data than I asked for in my query?
> 
> All queries specify a start time and an end time (if the end time isn't specified, it is assumed to be "now"). OpenTSDB's goal is to plot a sensible graph covering that time span. However it needs to retrieve data before and after the times you actually specified, in order to know how to properly compute the values near the "edges" of the graph. Because having extra values past the times actually requested is required to draw accurate graphs, OpenTSDB also returns the extra data based on the assumption that if you want to plot your own graphs or make your own processing, you will also need the extra data to get the correct behavior near the edges.
> The amount of extra data that OpenTSDB attempts to retrieve is proportional to the time span covered by your query. The 2.0 HTTP API will only return data within the requested time span.

**Comment by just2d** [comment]
@johann8384 thanks,I got your point about the first question. There may be some more points returned to do interpolation.

But for the second question:
[http://localhost:4242/api/query?start=1471795200&end=1471968000&m=zimsum:24h-zimsum-zero:key_f0f577c0](http://localhost:4242/api/query?start=1471795200&end=1471968000&m=zimsum:24h-zimsum-zero:key_f0f577c0)
from 2016-08-22 00:00:00 to 2016-08-24 00:00:00 every 24 hours, there should be 2 points:

2016-08-23 **00**:00:00 {the count from 2016-08-22 00:00:00 to 2016-08-23 00:00:00}
2016-08-24 **00**:00:00 {the count from 2016-08-23 00:00:00 to 2016-08-24 00:00:00}

but I got:
2016-08-22 **08**:00:00 {what's the count meaning?}
2016-08-23 **08**:00:00 {what's the count meaning?}

and the total count was accumulated to the start timestamp, right?
`2016-08-23 08:00:00 66666`
Was the count 66666 the zimsum count from 2016-08-22 08:00:00 to 2016-08-23 08:00:00, or from 2016-08-23 08:00:00 to 2016-08-24 08:00:00? It's the last one, right?

**Comment by tim-yin** [comment]
@johann8384 
What conditions trigger for insert extra points？
BTW: We also used opentsdb 2.2 version , the interval set  1s,  the aggregators function set SUM  Original datapoint Accuracy to millisecond    We got a wrong statistical result。
Thanks in advance for your help.
