### ISSUE TITLE
Bad Request on /api/query: No such aggregation function: none

### ISSUE THREAD

**Issue by longtimeago** [OpenTSDB/opentsdb#860]
According to the doc, http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html
there is a special type of aggregator named as `none`
But when I make a query with such aggregator type I get following:
```
Bad Request on /api/query: No such aggregation function: none
```
We are using v.2.2.0 but the same is with current code base:
https://github.com/OpenTSDB/opentsdb/blob/e2efe9a4875f8cddd3404e9c6b64f5aab4b72c0a/src/core/Aggregators.java#L137-L146
There is no such aggregator in the list

**Comment by manolama** [comment]
I think *none* is only in the "next" branch right now so it will come out with 2.3.0. I'll tag that in the docs, sorry for the confusion!
