### ISSUE TITLE
annotation write ago  error

### ISSUE THREAD

**Issue by youzhagui2006** [OpenTSDB/opentsdb#865]
i via 
api/annotation/bulk 
write data twice ，found error messgae

"code": 500
"message": "com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:"
"trace": "java.lang.RuntimeException: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception: at net.opentsdb.tsd.AnnotationRpc.executeBulkUpdate(AnnotationRpc.java:240) ~[tsdb-2.2.0.jar:na] at net.opentsdb.tsd.AnnotationRpc.executeBulk(AnnotationRpc.java:145) ~[tsdb-2.2.0.jar:na] at net.opentsdb.tsd.AnnotationRpc.execute(AnnotationRpc.java:54) ~[tsdb-2.2.0.jar:na] at net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.2.0.jar:na] at net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.2.0.jar:na] at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na] at org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na] at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na] at 

data：

[
    {
        "tsuid": "00110E000001002765000002002764",
        "endTime": "1473210056001",
        "startTime": "1473210056000",
        "notes": "[{\"CPU_COST\": \"\", \"ne_id\": \"1000024713238\", \"SQL_ID\": \"8swypbbr0m372\", \"P_STOP\": \"\", \"OPERATION\": \"SELECT STATEMENT\", \"BYTES\": \"\", \"ROWS_COUNT\": \"\", \"TIME\": \"\", \"TEMP_SPACE\": \"\", \"HASH_ID\": \"893970548\", \"NAME\": \"\", \"DEPTH\": \"0\", \"CARDINALITY\": \"\", \"P_START\": \"\", \"ID\": \"0\"}, {\"CPU_COST\": \"37096\", \"ne_id\": \"1000024713238\", \"SQL_ID\": \"8swypbbr0m372\", \"P_STOP\": \"\", \"OPERATION\": \"TABLE ACCESS\", \"BYTES\": \"546\", \"ROWS_COUNT\": \"93\", \"TIME\": \"1\", \"TEMP_SPACE\": \"\", \"HASH_ID\": \"893970548\", \"NAME\": \"ACCESS$\", \"DEPTH\": \"1\", \"CARDINALITY\": \"21\", \"P_START\": \"\", \"ID\": \"1\"}, {\"CPU_COST\": \"18443\", \"ne_id\": \"1000024713238\", \"SQL_ID\": \"8swypbbr0m372\", \"P_STOP\": \"\", \"OPERATION\": \"INDEX\", \"BYTES\": \"\", \"ROWS_COUNT\": \"124\", \"TIME\": \"1\", \"TEMP_SPACE\": \"\", \"HASH_ID\": \"893970548\", \"NAME\": \"I_ACCESS1\", \"DEPTH\": \"2\", \"CARDINALITY\": \"21\", \"P_START\": \"\", \"ID\": \"2\"}]",
                "custom": {
            "WAIT_TIME_PER": "79.66000",
            "PARSE_CALLS": "251.00000",
            "SQL_FULLTEXT": "select order#,columns,types from access$ where d_obj#=:1",
            "EXECUTIONS": "251.00000",
            "SQL_TEXT": "select order#,columns,types from access$ where d_obj#=:1",
            "DISK_READS": "25.00000",
            "ELAPSED_TIME": "438365.00000",
            "HASH_VALUE": "893970548",
            "WAIT_TIME": "2.00000",
            "USER_IO_WAIT_TIME": "368751.00000",
            "PER_TIME": "1739",
            "SQL_ID": "8swypbbr0m372",
            "SORTS": 1,
            "CPU_TIME": "89156.00000",
            "config_name": "select order#,columns,types from access$ where d_obj#=:1",
            "BUFFER_GETS": "2716.00000",
            "top_type": "DISK_READS"
        }
    }
]

**Comment by manolama** [comment]
Hi, any way you could paste the rest of the exception? There should be a "Caused By" line somewhere. Thanks!

**Comment by manolama** [comment]
As far as I can tell this one may have been bad JSON in the "notes" field. If you remove that and try posting:
```
[{
	"tsuid": "00110E000001002765000002002764",
	"endTime": "1473210056001",
	"startTime": "1473210056000",
	"notes": "badjson there",
	"custom": {
		"WAIT_TIME_PER": "79.66000",
		"PARSE_CALLS": "251.00000",
		"SQL_FULLTEXT": "select order#,columns,types from access$ where d_obj#=:1",
		"EXECUTIONS": "251.00000",
		"SQL_TEXT": "select order#,columns,types from access$ where d_obj#=:1",
		"DISK_READS": "25.00000",
		"ELAPSED_TIME": "438365.00000",
		"HASH_VALUE": "893970548",
		"WAIT_TIME": "2.00000",
		"USER_IO_WAIT_TIME": "368751.00000",
		"PER_TIME": "1739",
		"SQL_ID": "8swypbbr0m372",
		"SORTS": 1,
		"CPU_TIME": "89156.00000",
		"config_name": "select order#,columns,types from access$ where d_obj#=:1",
		"BUFFER_GETS": "2716.00000",
		"top_type": "DISK_READS"
	}
}]
```
it seems to work alright. Re-open if you get some more details in the logs please.
