### ISSUE TITLE
Allowing passing a custom timezone in queries

### ISSUE THREAD

**Issue by tsuna** [OpenTSDB/opentsdb#87]
The TSD always uses the system's timezone settings when parsing human readable dates.  It also honors the `TZ` environment variable.  This is fine as long as TSD's users live in a single timezone.

This goal of this bug is to add an extra (optional) parameter `tz` to specify which timezone to use to parse the dates.  If no timezone is specified, then the TSD's timezone should be used.

**Comment by biswaKL** [comment]
Not working for me, Lieelt help please:

http://opentsdbHOST:4242/api/query?tz=IST&start=1660588200&end=1660742566&m=last:15m-avg:Ambient2.AT{Station_id=site_1423}

**Comment by deamerfire** [comment]
你的邮件我已收到，会及时回复你的，谢谢啦啦。。。。吴琼
