### ISSUE TITLE
Have you add the option to disable timestamp validation?

### ISSUE THREAD

**Issue by leell** [OpenTSDB/opentsdb#877]
Hello!
Have you added the option to disable timestamp validation you mentioned in [#572](https://github.com/OpenTSDB/opentsdb/issues/572)?
I didn't see anything related yet.

**Comment by manolama** [comment]
Not yet, let's see if I can get something simple done.

**Comment by manolama** [comment]
Merged in 71f35ca4a4cc4763110ac10d8e9ff265e7d6a750 with 2.4 snapshot (since it's a new feature). Please try it out and let us know how it looks.
