### ISSUE TITLE
"Failed to save the TSMeta to storage" while updating OpenTSDB METADATA

### ISSUE THREAD

**Issue by dpellegrino** [OpenTSDB/opentsdb#880]
Hi,
I have been facing an issue during metadata update and specifically when I try to update a metadata object with more custom fields.
In my scenario I should create a metadata for tsuid through HTTP API POST /api/uid/tsmeta/ and then periodically update it.
The first time, I can create the metadata properly using the following http post call:
http://host:port/api/uid/tsmeta?m=test{tk=tv}&method_override=post&create=true) 
{
    "displayName": "display name1",
    "description": "description name1",
    "custom": {
        "customname1": "test1",
        "customname2": "test2",
        "customname3": "test3",
        "customname4": "test4",
        "customname5": "test5",
        "customname6": "test6",
        "customname7": "test7",
        "customname8": "test8",
        "customname9": "test9",
        "customname10": "test10"    }
}

The metadata object previously created can be retrieved through the metadata HTTP API GET command without any problem.

When I try to update it using the same http post as above (without create=true and changing for example the name of a custom field) I receive an HTTP error 500 with the following description:
code": 500,
"message": "Failed to save the TSMeta to storage",
"details": "This may be caused by another process modifying storage data",
"trace": "net.opentsdb.tsd.BadRequestException: Failed to save the TSMeta to storage\n\tat net.opentsdb.tsd.UniqueIdRpc$2SyncCB.call(UniqueIdRpc.java:330) ~[tsdb-2.2.1.jar:]\n\tat net.opentsdb.tsd.UniqueIdRpc$2SyncCB.call(UniqueIdRpc.java:325) ~[tsdb-2.2.1.jar:]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.access$300(Deferred.java:430) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.access$300(Deferred.java:430) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.doCall(Deferred.java:1278) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257) ~[async-1.4.0.jar:na]\n\tat com.stumbleupon.async.Deferred.callback(Deferred.java:1005) ~[async-1.4.0.jar:na]\n\tat org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712) ~[asynchbase-1.7.2.jar:na]\n\tat org.hbase.async.RegionClient.decode(RegionClient.java:1533) ~[asynchbase-1.7.2.jar:na]\n\tat org.hbase.async.RegionClient.decode(RegionClient.java:88) ~[asynchbase-1.7.2.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]\n\tat org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223) ~[asynchbase-1.7.2.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.9.4.Final.jar:na]\n\tat org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121) ~[asynchbase-1.7.2.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]\n\tat java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]\n"

I'm using the last OpenTSDB release 2.2.1 with HBASE release 1.1.2.2.5.0.0-1245.

I have also tried to execute the CLI tsdb commands like metapurge, metasync or fsck and nothing has changed. 

Any help? Suggestions?

Thank you in advance.

Regards,
Dario Pellegrino

**Comment by manolama** [comment]
Ahh, thank you for finding this. I *think* I know what the issue is. It's likely due to serialization of the custom tags hash map. The order may change depending on JVM, host, alignment of the planets, etc so that the compare-and-set call to HBase fails. For testing, could you try doing the same thing but not store any custom tags? Just make sure that goes through, then try storing a single custom tag. Those should work then if you try adding more custom tags it should fail again. The solution would be to make sure the tags are sorted at serialization so the CAS can behave deterministically.

**Comment by dpellegrino** [comment]
Thanks for your reply. 
I have done the test and I confirm you that:
1) without custom tags the API works properly;
2) adding a single custom tag the API works properly;
3) adding until 9 custom tags the API works properly;
4) after adding 10 custom tags the API fails.
It is not clear to me what you mean with _"The solution would be to make sure the tags are sorted at serialization so the CAS can behave deterministically"_. Is there something that I can do to solve the issue or should I have just to wait until someone fix the bug? Is there a sort of work-around to bypass this issue?
Regards,
Dario
