### ISSUE TITLE
Unify starting timestamp ?

### ISSUE THREAD

**Issue by benrubson** [OpenTSDB/opentsdb#881]
Hello,

Let's assume 2 series with the following values :

```
cpu.idle
- 10:30:00 : 100
- 10:29:29 : 100
- 10:28:58 : 100
- 10:28:27 : 60
- 10:27:56 : 60

cpu.user
- 10:28:58 : 0
- 10:28:27 : 40
- 10:27:56 : 40
```

As you can see, cpu.user does not have the 2 last timestamps, as they have 0 value they were not pushed to OpenTSDB (deduplication).

When we request these 2 series, starting at 10:29:50 with a 30 seconds downsample (to match data sampling), OpenTSDB will return the following :

```
cpu.idle
- 10:30:00 : 100
- 10:29:30 : 100
- 10:29:00 : 100
- 10:28:30 : 60
- 10:28:00 : 60

cpu.user
- 10:28:58 : 0
- 10:28:28 : 40
- 10:27:58 : 40
```

Unfortunately, we can't stack these series, as the timestamps do not match.

I think we would expect the following (take the first available timestamp across the requested series as the starting timestamp) :

```
cpu.idle
- 10:30:00 : 100
- 10:29:30 : 100
- 10:29:00 : 100
- 10:28:30 : 60
- 10:28:00 : 60

cpu.user
- 10:29:00 : 0
- 10:28:30 : 40
- 10:28:00 : 40
```

Or (take the query timestamp as the starting timestamp) :

```
cpu.idle
- 10:29:50 : 100
- 10:29:20 : 100
- 10:28:50 : 100
- 10:28:20 : 60
- 10:27:50 : 60

cpu.user
- 10:28:50 : 0
- 10:28:20 : 40
- 10:27:50 : 40
```

Do you think OpenTSDB could be modified to match this behaviour ?

Thank you very much 👍 

Ben

**Comment by benrubson** [comment]
This request is in some sort related to the `deduplicate` feature of [Tcollector](https://github.com/OpenTSDB/tcollector).
Deduplication is really interesting (save space & resources), however as shown above OpenTSDB may break stacking of such deduplicated series, depending on their timestamps.

**Comment by manolama** [comment]
Hi @benrubson Which version of TSDB are you using? If you move to 2.2 it should snap the timestamps to 30 second offsets from the top of the minute. Prior to that the times were based off the start of the first data point.

**Comment by benrubson** [comment]
Hi @manolama, really good news, I'm still using 2.1, I'll then give 2.2 a try and will post the result.
_In the meantime, I close this issue._
Thank you very much 👍

**Comment by benrubson** [comment]
@manolama, according to [this](http://opentsdb.net/docs/build/html/user_guide/query/index.html), timestamps are normalized as of 2.1 ?

**Comment by benrubson** [comment]
Mmmm @manolama, according to [this](http://opentsdb.net/docs/build/html/user_guide/query/index.html), timestamps are normalized as of 2.1 ?
So I think I should not see this issue with 2.1 ?
Thank you for your help !
