### ISSUE TITLE
Opentsdb-2.3.0-RC2 Build Error

### ISSUE THREAD

**Issue by Raghu-Gurrala** [OpenTSDB/opentsdb#883]
[opentsdb.txt](https://github.com/OpenTSDB/opentsdb/files/525559/opentsdb.txt)
Hi All,

I 'm facing issues installing opentsdb 2.3 
When I try to build using ./build.sh 
I see the following error.

 ../src/utils/Pair.java ../src/utils/PluginLoader.java ../src/utils/Threads.java ../src/tools/BuildData.java ./src/net/opentsdb/query/expression/parser/*.java
javac: file not found: ./src/net/opentsdb/query/expression/parser/*.java
Usage: javac <options> <source files>
use -help for a list of possible options
make[1]: *** [.javac-stamp] Error 2
make[1]: Leaving directory `/data0/opt/opentsdb-2.3.0-RC2/build'
make: *** [install] Error 2

Auto make version 1.11.1-4
https://github.com/OpenTSDB/opentsdb/releases/tag/v2.3.0RC2

Thanks,
Raghu

**Comment by manolama** [comment]
Sorry for the trouble. Are you pulling from Git or using the tarball in the Github release?

**Comment by Raghu-Gurrala** [comment]
I just downloading the file (opentsdb-2.3.0-RC2.tar.gz) from the link above and then trying to build it.

**Comment by Raghu-Gurrala** [comment]
sorry closed it by mistake

I just downloading the file (opentsdb-2.3.0-RC2.tar.gz) from the link above and then trying to build it.

**Comment by Raghu-Gurrala** [comment]
Cloned from git and build did work 

Cloned a branch "next" as it has the new version.
If cloned without branch option old version is downloaded. 

 git clone -b next git://github.com/OpenTSDB/opentsdb.git

**Comment by nickman** [comment]
Cone to think of it, I had the same issue. Clone from git OK, tgz not.
