### ISSUE TITLE
Document the semantics of different branches

### ISSUE THREAD

**Issue by mbrukman** [OpenTSDB/opentsdb#936]
Document the distinction between these and any other relevant branches:

* `master`
* `next`
* `put`
* `maintenance`
* etc.

For example, which branch should new PRs be based on: `next` or `put`? What's `master`? Are there other relevant branches one should keep in mind?

**Comment by manolama** [comment]
Good catch. Documented it in: http://opentsdb.net/docs/build/html/development/index.html#git-repository
Thanks!
