### ISSUE TITLE
Histogram as a Data Point Support

### ISSUE THREAD

**Issue by othoppai** [OpenTSDB/opentsdb#938]
Today, an entire histogram cannot be pushed or queries as a single data point in openTSDB. Adding that capability is going to be immensely helpful for storing latency histograms in openTSDB. The APIs should allow for inserting an entire histogram with "n" buckets as a single data point and queries should treat these histograms as one unit as well for aggregation. Would be great to have the query return the raw bucket numbers as well as percentiles. The number of buckets for the histogram should ideally be unlimited, but as a first step, it would be great to have basic histogram support that would say support 100 buckets or so.

Opening this issue after I had a conversation with ManoLamancha and Chris Larsen. Much thanks in advance to them since this work is already in progress from them to add this support in openTSDB.

[Omprakaash] What is the best way to store histograms in openTSDB. Since a given metric value's maximum is 8 bytes, there is no way I can store an entire histogram in one row. What I am thinking of is to store individual buckets as one metric - so 100 metrics If I want to maintain 100 buckets per histogram.

[ManoLamancha] We implemented histogram support at Yahoo and will be bubbling that up within the next couple of weeks. This will allow you to compute true percentiles across multiple series. It works by encoding the histo and storing it in columns similar to a data point. Then at query time you can sum the various histos across time or groups and extract either the raw histo or percentiles from it.

[Omprakaash] Does this allow pushing an entire histogram as one data point. Also does a query return an entire histogram. How many buckets can this histogram support ?

[Chris] Yes, an entire histogram is stored per timestamp as if it was a data point. At query time, you specify the "sum" aggregator, optionally the "sum" downsampler and either ask for a list of one or more percentiles or ask for the raw histogram buckets.
The bucket size is dependent on the implementation (we'll probably put out our simple bucket imp) so it can be unlimited.

**Comment by othoppai** [comment]
Hi, any update on this ? Do we now have APIs to add a metric that represents an entire histogram as a data point ?

**Comment by manolama** [comment]
Hi @othoppai Yes, the histogram code is in 2.4 (and RC2 is out now). http://opentsdb.net/docs/build/html/api_http/histogram.html

**Comment by manolama** [comment]
I'll close this since it's out. For bugs (and there are *always* bugs) file a new ticket please.

**Comment by othoppai** [comment]
Thanks manolama, can you please point me to the source code files where the histogram support was added? I am specifically looking for the programmatic API that the TSD client can use to push the histogram down to the TSDB backend.
