### ISSUE TITLE
Biggest timestamp allowed

### ISSUE THREAD

**Issue by aemitos** [OpenTSDB/opentsdb#945]
Hi, this is more a question. I don't know if it is a proper place to ask it, so I'm doing here. Sorry if it is not the place.
What is the biggest timestamp? 
In date I could find 2106/01/01.
Is there some limitation related to my hardware? Is there a current limitation?
Any hint to go beyond this limitation?
Thanks in advance
Congratulations to everyone involved in the development.
Best Regards

**Comment by johann8384** [comment]
I suspect the limit would be based on this code:

https://github.com/OpenTSDB/opentsdb/blob/master/src/utils/DateTime.java#L74

If nothing else, it would be 9999999999 (GMT: Sat, 20 Nov 2286 17:46:39 GMT) because anything more than 10 digits long is considered to be a MS timestamp.

**Comment by johann8384** [comment]
Asking here is fine, but there is also a Google group if you'd like to use that. https://groups.google.com/forum/#!forum/opentsdb

**Comment by aemitos** [comment]
ok, thank you very much!!
