### ISSUE TITLE
Publish a list of production users / case studies

### ISSUE THREAD

**Issue by mbrukman** [OpenTSDB/opentsdb#946]
Potential users evaluating adoption of new technology are typically curious as to who else is using the product (particularly in production), what their use cases / scale are, and what their experience has been.

To make users more comfortable adopting OpenTSDB, it would benefit from having a page listing who is already using it in production, even if it's just the company logo (assuming they're OK with both a public disclosure plus their logo being used) and even better, if they could provide either a short description of how they're using it or a more in-depth case study (the length of a typical blog post).

Here are some examples of how other projects do this:

* Apache Cassandra: http://cassandra.apache.org/ and https://en.wikipedia.org/wiki/Apache_Cassandra#Prominent_users
* Apache HBase: http://hbase.apache.org/poweredbyhbase.html
* KairosDB: http://kairosdb.github.io/ (see bottom of page)
* MongoDB: https://www.mongodb.com/community/deployments
* Vertx: http://vertx.io/whos_using/

**Comment by manolama** [comment]
Hiya, we do have this wiki:

https://github.com/OpenTSDB/opentsdb/wiki/Companies-using-OpenTSDB-in-production

**Comment by mbrukman** [comment]
That's a great list! I think this would have much more impact if these company names / logos were on the website: http://opentsdb.net like it's done for the other projects I listed. What do you think?

**Comment by IDerr** [comment]
I agree with @mbrukman . It'll give a lot more visibility to the projet.

**Comment by IDerr** [comment]
@manolama I think we should transfer this to the website issue.

**Comment by IDerr** [comment]
Hi @mbrukman, 
I have transfered this issue on the website repo, could you please close this one ?

Thanks

**Comment by mbrukman** [comment]
Sounds good, thanks!
