### ISSUE TITLE
[main] Config: No configuration found, will use defaults

### ISSUE THREAD

**Issue by stagger43** [OpenTSDB/opentsdb#950]
I need help pointing OpenTSDB to the correct config file.

I start OpenTSDB "$ sudo ./build/tsdb tsd --port=4242 --staticroot=build/staticroot/ --cachedir=/tmp/tsd/"

I can see no config file is being used.
[main] Config: No configuration found, will use defaults

I can see http://localhost:4242/api/config   

My goal is to change "tsd.search.enable":"false"" to "true" so it is searchable 

Our programmers are getting an error "searching not enabled"

in  /opentsdb/src/opentsdb.conf   I added tsd.search.enable = true  

I think I am not pointing to a config file 

I looked at /openstdb/builds/tsdb and found configdir=' '

I changed it to configdir='/opentsdb/src'  that didnt help.

Thanks in advance for any help

**Comment by johann8384** [comment]
I think you need a search plugin: http://opentsdb.net/docs/build/html/user_guide/plugins.html#search

By default it will look in the following places for config files: 

`    // search locally first
    file_locations.add("opentsdb.conf");

    // add default locations based on OS
    if (System.getProperty("os.name").toUpperCase().contains("WINDOWS")) {
      file_locations.add("C:\\Program Files\\opentsdb\\opentsdb.conf");
      file_locations.add("C:\\Program Files (x86)\\opentsdb\\opentsdb.conf");
    } else {
      file_locations.add("/etc/opentsdb.conf");
      file_locations.add("/etc/opentsdb/opentsdb.conf");
      file_locations.add("/opt/opentsdb/opentsdb.conf");
    }
`

**Comment by stagger43** [comment]
@johann8384  thx for the reply I will take a look asap 

thx!!!

**Comment by manolama** [comment]
Closing for now, thanks!
