### ISSUE TITLE
Data merge after filter Tags

### ISSUE THREAD

**Issue by neo-hu** [OpenTSDB/opentsdb#951]
Data merge after filter Tags

**Comment by neo-hu** [comment]
all

`[{"metric":"test1","tags":{"a":"fo1"},"aggregateTags":[],"dps":{"1489826790":2}},{"metric":"test1","tags":{"a":"fo2"},"aggregateTags":[],"dps":{"1489826790":48}},{"metric":"test1","tags":{"a":"fo3"},"aggregateTags":[],"dps":{"1489826790":33}}]`

for example  
`/api/query?start=2017/03/18-00:00:00&end=2017/03/18-16:48:19&m=sum:test1{a=fo1|fo2}` 

result

`[{"metric":"test1","tags":{"a":"fo1"},"aggregateTags":[],"dps":{"1489826790":2}},{"metric":"test1","tags":{"a":"fo2"},"aggregateTags":[],"dps":{"1489826790":48}}]`

expect： 48+2
`{"metric":"test1","tags":{},"aggregateTags":["a"],"dps":{"1489826790":` 50}}]

**Comment by manolama** [comment]
Ah you have to use TSDB 2.2 or later then you can query via:

``/api/query?start=2017/03/18-00:00:00&end=2017/03/18-16:48:19&m=sum:test1{}{a=fo1|fo2}``

Note the empty set of curly braces. The first set means "filter and group by these tags" where as the second set means "filter but don't group by the tags" so the second set will be aggregated into one result.
