### ISSUE TITLE
tsd.storage.flush_interval not actually used

### ISSUE THREAD

**Issue by alienth** [OpenTSDB/opentsdb#952]
There are references in the [documentation](http://opentsdb.net/docs/build/html/user_guide/configuration.html) and also in the [config code](https://github.com/OpenTSDB/opentsdb/blob/cac608ad7bfaf6315fd2319a8af37da307abdeb9/src/utils/Config.java#L518) to a `tsd.storage.flush_interval` config setting. However, it appears no code actually uses that setting.

**Comment by alienth** [comment]
Looks like the reference to this setting was removed with 9dce414.

**Comment by manolama** [comment]
Good catch. It's been supplanted by ``hbase.rpcs.buffered_flush_interval`` to mimic HBase's settings :).
