### ISSUE TITLE
Problems while installing Open TSDB on the Mapr Cluster. 

### ISSUE THREAD

**Issue by sandeep51989** [OpenTSDB/opentsdb#957]
When running the build.sh i am getting the following error. The main reason is with the command exc make. The rest are statments are fine. 

sh build.sh 
+ test -f configure
+ test -d build
+ cd build
+ test -f Makefile
+ exec make
set dummy "http://opentsdb.googlecode.com/files" "third_party/slf4j/log4j-over-slf4j-1.7.2.jar"; shift; ./build-aux/fetchdep.sh "$@"
--2017-03-22 13:39:48--  http://opentsdb.googlecode.com/files/log4j-over-slf4j-1.7.2.jar
Resolving opentsdb.googlecode.com... 64.233.169.82, 2607:f8b0:4003:c08::52
Connecting to opentsdb.googlecode.com|64.233.169.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-22 13:39:48 ERROR 404: Not Found.

**Comment by manolama** [comment]
Which version of OpenTSDB were you trying? Pulling from googlecode must be really old so try 2.2 or later please.
