### ISSUE TITLE
java not found error occurred when install using rpm

### ISSUE THREAD

**Issue by ninjadq** [OpenTSDB/opentsdb#963]
I install opentsdb via rpm
`yum install opentsdb-2.3.0.rpm`

but when I start service using 
`service opentsdb start`
opentsdb stopped immediately and `/usr/bin/tsdb: line 118: exec: java: not found` on opentsdb.err file

I'm using centos6.6 and root user

Anyone know how to slove this?

**Comment by johann8384** [comment]
Install Java :)

sudo yum install java or similar.

**Comment by ninjadq** [comment]
@johann8384 thank you for your reply,  I've solved this by adding JAVA_HOME Environment variable. I installed Java manually but not set the JAVA_HOME   😱
