### ISSUE TITLE
opentsdb Support Chinese？？？

### ISSUE THREAD

**Issue by wmpp** [OpenTSDB/opentsdb#967]
Modify the character set to UTF-8.Chinese can be stored.but metric tagk and tagv's enumeration value can only be up to 127.anyone can help me？？？
![image](https://cloud.githubusercontent.com/assets/27722236/25183403/117063a4-254a-11e7-97a7-d5e24e24a2d6.png)

**Comment by manolama** [comment]
There could be a bug somewhere if the UTF encoding isn't used for the tags. I'll see if I can comb through and find it.

**Comment by manolama** [comment]
Try out 38c6f6708cf94d07ca491da8f02fb8776e11b069 and re-open if it still fails please. Thanks!

**Comment by manolama** [comment]
Had to revert in 07f96d9341a5563c80cea37a6ce2be6786e1282f. Will need to dig deeper into this.
