### ISSUE TITLE
how send the data in Opentsdb 

### ISSUE THREAD

**Issue by yani01** [OpenTSDB/opentsdb#975]
Hello
You can please help me
I would like to have some data retrieved and send them to Opentsdb
In fact I use Librenms which retrieve data and sends it in influxdb and rrd
And I want to change to store them in Opentsdb

Knowing that I am completely beginner with opentsdb
Thank you for your help

**Comment by johann8384** [comment]
Well, LIbreNMS doesn't support OpenTSDB directly, I was toying with adding an input to OpenTSDB 3.0 that would accept the InfluxDB line protocol, this would work, but I haven't done that yet. 

In the meantime, I created a [PR with LibreNMS](https://github.com/librenms/librenms/pull/6501)

**Comment by yani01** [comment]
hi @johann8384 
Great 
it's what I am looking for
So for now the problem is the correspondence of the protocol line of influxdb and opentsdb  ??
may i use your programe to make some test please  ??

thank you

**Comment by johann8384** [comment]
Uh, well the problem is the LibreNMS doesn't know how to talk to OpenTSDB, so we either have to make OpenTSDB look like InfluxDB, or make LibreNMS know how to talk to OpenTSDB. I chose the latter for the time being.

You may use my program, as soon as I have a chance to make a few changes it will be merged into LibreNMS.

**Comment by yani01** [comment]
I will try to look how  librenms and opentsdb will can communicate, I see that you use fwrite as for graphite if I understand correctly you try to send the data on the flux create with fsoucket ???? And it does not work it ???

**Comment by yani01** [comment]
hi @johann8384  
I wanted to know if it is possible for the .gitignore to add * .iml
 .idea / and it is in the conf conf file of opentsdb.
 Because I tried manually to send data using a simple test file and simple given to the pif, it works but when I use this in librenms but I do not find the metrci in grafana and if I make a tcpdump I see nothing passing
??????

thank you

**Comment by yani01** [comment]
hi @johann8384 

It's good I can send the metric in opentsdb but I have to add a reconnection whenever we call opentsdb_update.,
But the last problem is that it does not happen to read the table of hostname 
When i do a tcpdump this is what it gives me 

">..v....8.;..tP.9..Q..put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 1328587 Array
put ipSystemStats 1493995503 663953 Array
put ipSystemStats 1493995503 2 Array
put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 0 Array
put ipSystemStats 1493995503 10186049671 Array

D.......BmC...P.=b....put: illegal argument: invalid tag: Array
 
have you an idée for read the table And arrange for each value his hostname
thank you in advance
