### ISSUE TITLE
Aggregations with alternating tags creates "ghost lines", falsifying results

### ISSUE THREAD

**Issue by RMoulet** [OpenTSDB/opentsdb#977]
Hello. I have started to familiarize myself with openTSDB.

In order to learn to use the API, I inserted the following file:

python.myservice.latency.avg 1288900000 42 reqtype=foo extra=f
python.myservice.latency.avg 1288900015 100 reqtype=foo extra=t
python.myservice.latency.avg 1288900030 40 reqtype=foo extra=f
python.myservice.latency.avg 1288900045 200 reqtype=foo extra=t

However, when I use the query API (http://localhost:4242/api/query?start=1288900000&end=1288900060&$OP), I get the following results for these values of OP:

m=**count**%3Apython.myservice.latency.avg
Result: 
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":1,**"1288900015":2**,**"1288900030":2**,"1288900045":1}}]
Should be: 
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":1,**"1288900015":1**,**"1288900030":1**,"1288900045":1}}]

m=**sum**%3Apython.myservice.latency.avg
Result:
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":42,**"1288900015":141**,**"1288900030":190**,"1288900045":200}}]
Should be:
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":42,**"1288900015":100**,**"1288900030":40**,"1288900045":200}}]

m=sum%3Apython.myservice.latency.avg{**extra**=*}
Result:
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo","extra":"f"},"aggregateTags":[],"dps":**{"1288900000":42,"1288900030":40}**},{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo","extra":"t"},"aggregateTags":[],"dps":**{"1288900015":100,"1288900045":200}**}]
This is the right result.

m=sum%3Apython.myservice.latency.avg{**reqtype**=*}
Result:
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":42,**"1288900015":141,"1288900030":190**,"1288900045":200}}]
Should be:
[{"metric":"python.myservice.latency.avg","tags":{"reqtype":"foo"},"aggregateTags":["extra"],"dps":{"1288900000":42,**"1288900015":100,"1288900030":40**,"1288900045":200}}]
This is the same result as m=sum%3Apython.myservice.latency.avg

So the issue here is that the results are those you would expect from having these lines:
python.myservice.latency.avg 1288900000 42 reqtype=foo extra=f
_python.myservice.latency.avg 1288900015 41 reqtype=foo_
python.myservice.latency.avg 1288900015 100 reqtype=foo extra=t
_python.myservice.latency.avg 1288900030 150 reqtype=foo_
python.myservice.latency.avg 1288900030 40 reqtype=foo extra=f
python.myservice.latency.avg 1288900045 200 reqtype=foo extra=t

Note that 41 = mean(40,42) and 150 = mean(100,200).

After trying to find the cause, these "ghost lines" appear when the following criteria are met, considering lines A,B and C:
- timestampA  <  timestampB  <  timestampC
- tagA = value1, tagB = value2, tagC = value1

After testing (I took care of deleting the lines between each test with tsdb scan --delete), the problem persists even if:
- there is only one tag (extra), in which case the ghost line seems to be "_python.myservice.latency.avg 1288900015 41_" with no tag,
- the values of the tags don't alternate in a 1/1 pattern - if extra is t-f-f-t (instead of t-f-t-f in example above) the result of sum are {"1288900000":42,"1288900015":194,"1288900030":187,"1288900045":200} (so +94 and +147, respectively, no idea where those numbers come from).
- you delete the two "extra=f" tags

So did I miss something about defining tags, or is there a reason or explanation for these results?
Any help would be greatly appreciated, I haven't managed to find the answer on my own.

**Comment by RMoulet** [comment]
Udpate: just reread the documentation, I believe the problem may be explained by this phrase.

> OpenTSDB aggregates data by default and requires an aggregation operator for every query. Each aggregator has to handle missing or data points at different time stamps for multiple series. This is performed via interpolation and can lead to unexpected results at query time if users are unaware of what TSDB is doing.

**Comment by manolama** [comment]
Right you found it in the docs :) By default we do aggregate everything and it drove some users crazy so we introduced the ``none`` aggregator that will give you ever time series matching your query.
