### ISSUE TITLE
Query stats not written when channel is closed. 

### ISSUE THREAD

**Issue by jsbali** [OpenTSDB/opentsdb#979]
Query stats don't get written in case of closed channel exception as stats.markSendFailed is never called.

**Comment by jsbali** [comment]
Going through the code the fix is pretty simple (suggestions are welcome).
Fix can be in
https://github.com/OpenTSDB/opentsdb/blob/master/src/tsd/AbstractHttpQuery.java#L413 before doing a quick return call stats.markSendFailed
Also if the channel closes after that we can do that in SendSuccess onComplete and check for isSuccess and then call apt method.

**Comment by johann8384** [comment]
PR welcome :)

**Comment by manolama** [comment]
Merged, thanks!
