### ISSUE TITLE
Unable to get "all" downsampling to work

### ISSUE THREAD

**Issue by kennethleider** [OpenTSDB/opentsdb#980]
I think the problem is on line 644 of QueryRpc.java.  If I am reading this correctly the HTTP api is not recognizing it because it's not an integer.

I am currently just using a downsampling interval of "1w" which is much greater than my query window to get a similar result.  Do you think there will be any unexpected results from this workaround?

**Comment by kennethleider** [comment]
I found a better work around.  Using your POST interface.

**Comment by manolama** [comment]
Hmm, was the ``all`` failing? If you issue a query like ``http://localhost:4242/api/query?start=1492610400&end=1492691642&m=sum:0all-sum:sys.cpu.user`` it should work and downsample all of the values.

Using ``1w`` may have some side-effects as it will normalize the timestamps to 1 week boundaries and may thus emit or include some values you'd want to have.

**Comment by manolama** [comment]
Ah found the documentation issue and fixed it. This should be good.
