### ISSUE TITLE
Documentation - Writing Data - Query Speed  - Math seems off/miss-leading.

### ISSUE THREAD

**Issue by w00te** [OpenTSDB/opentsdb#984]
In the below section form the documentation at http://opentsdb.net/docs/build/html/user_guide/writing/index.html, I think the math is off/confusing.

- 1 time-series
- 1-row-per-hour = 24 rows a day (it says 86,400 which is actually 1 row per second, not hour).
- 24 * 8 cores = 192 rows a day
- x 20,000 servers = 3,840,000 which does match your 3.8 million at the end.

> Cardinality also affects query speed a great deal, so consider the queries you will be performing frequently and optimize your naming schema for those. OpenTSDB creates a new row per time series per hour. If we have the time series sys.cpu.user host=webserver01,cpu=0 with data written every second for 1 day, that would result in 86400 rows of data. However if we have 8 possible CPU cores for that host, now we have 691200 rows of data. This looks good because we can get easily a sum or average of CPU usage across all cores by issuing a query like start=1d-ago&m=avg:sys.cpu.user{host=webserver01}.
> 
> However what if we have 20,000 hosts, each with 8 cores? Now we will have 3.8 million rows per day due to a high cardinality of host values. Queries for the average core usage on host webserver01 will be slower as it must pick out 691200 rows out of 3.8 million.

**Comment by manolama** [comment]
Ah good catch, I'll fix it up. Thanks.

**Comment by manolama** [comment]
Fixed in b5f30ece11de1d894fd8dd0517d4bd9423ce6d5f. Thanks.
