### ISSUE TITLE
opentsdb2.2   query annotation  problem

### ISSUE THREAD

**Issue by youzhagui2006** [OpenTSDB/opentsdb#994]
/api/query
# query parma ：
{
    "start": "2017/05/09 04:02:00",
    "end": "2017/05/09 04:03:00",
    "noAnnotations": "false",
    "queries": [
        {
            "aggregator": "avg",            
            "filters": [
                {
                    "filter": "1000026727741",
                    "groupBy": false,
                    "tagk": "neId",
                    "type": "literal_or"
                }
            ],
            "metric": "400001324"
        }
    ]
}
query one minute data, but return one hour data. why solve this problem? thanks!
# return data:
[
    {
        "metric": "",
        "tags": {},
        "aggregateTags": [],
        "annotations": [
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "0",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "389",
                    "ID": "389",
                    "INFO": "SHOW FULL PROCESSLIST",
                    "COMMAND": "Query",
                    "THEHOST": "192.168.17.233:54832",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781001,
                "startTime": 1494273781000
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "10631",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "390",
                    "ID": "390",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54831",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781002,
                "startTime": 1494273781001
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "693",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "391",
                    "ID": "391",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43457",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781003,
                "startTime": 1494273781002
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "74",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "392",
                    "ID": "392",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43458",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781004,
                "startTime": 1494273781003
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "14",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "393",
                    "ID": "393",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43460",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781005,
                "startTime": 1494273781004
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "7",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "439",
                    "ID": "439",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:48144",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781006,
                "startTime": 1494273781005
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "6014",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "440",
                    "ID": "440",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:39920",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781007,
                "startTime": 1494273781006
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "74",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "441",
                    "ID": "441",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43336",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781008,
                "startTime": 1494273781007
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "1342",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "451",
                    "ID": "451",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:40318",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781009,
                "startTime": 1494273781008
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "22",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "453",
                    "ID": "453",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:44415",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781010,
                "startTime": 1494273781009
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "3",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "452",
                    "ID": "452",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:59639",
                    "collect_time": "20170509040301"
                },
                "endTime": 1494273781011,
                "startTime": 1494273781010
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "650",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "389",
                    "ID": "389",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54832",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681001,
                "startTime": 1494274681000
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "650",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "390",
                    "ID": "390",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54831",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681002,
                "startTime": 1494274681001
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "2",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "391",
                    "ID": "391",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43457",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681003,
                "startTime": 1494274681002
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "13",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "392",
                    "ID": "392",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43458",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681004,
                "startTime": 1494274681003
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "372",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "393",
                    "ID": "393",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43460",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681005,
                "startTime": 1494274681004
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "14",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "439",
                    "ID": "439",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:48144",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681006,
                "startTime": 1494274681005
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "6914",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "440",
                    "ID": "440",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:39920",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681007,
                "startTime": 1494274681006
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "7",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "441",
                    "ID": "441",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43336",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681008,
                "startTime": 1494274681007
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "12",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "451",
                    "ID": "451",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:40318",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681009,
                "startTime": 1494274681008
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "82",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "453",
                    "ID": "453",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:44415",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681010,
                "startTime": 1494274681009
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "82",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "452",
                    "ID": "452",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:59639",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681011,
                "startTime": 1494274681010
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "0",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "454",
                    "ID": "454",
                    "INFO": "SHOW FULL PROCESSLIST",
                    "COMMAND": "Query",
                    "THEHOST": "192.168.17.233:45868",
                    "collect_time": "20170509041801"
                },
                "endTime": 1494274681012,
                "startTime": 1494274681011
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "1550",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "389",
                    "ID": "389",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54832",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581001,
                "startTime": 1494275581000
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "1550",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "390",
                    "ID": "390",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54831",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581002,
                "startTime": 1494275581001
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "94",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "391",
                    "ID": "391",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43457",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581003,
                "startTime": 1494275581002
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "14",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "392",
                    "ID": "392",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43458",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581004,
                "startTime": 1494275581003
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "94",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "393",
                    "ID": "393",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43460",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581005,
                "startTime": 1494275581004
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "7",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "439",
                    "ID": "439",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:48144",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581006,
                "startTime": 1494275581005
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "7814",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "440",
                    "ID": "440",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:39920",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581007,
                "startTime": 1494275581006
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "74",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "441",
                    "ID": "441",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43336",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581008,
                "startTime": 1494275581007
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "3",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "451",
                    "ID": "451",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:40318",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581009,
                "startTime": 1494275581008
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "22",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "453",
                    "ID": "453",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:44415",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581010,
                "startTime": 1494275581009
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "982",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "452",
                    "ID": "452",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:59639",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581011,
                "startTime": 1494275581010
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "0",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "454",
                    "ID": "454",
                    "INFO": "SHOW FULL PROCESSLIST",
                    "COMMAND": "Query",
                    "THEHOST": "192.168.17.233:45868",
                    "collect_time": "20170509043301"
                },
                "endTime": 1494275581012,
                "startTime": 1494275581011
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "2450",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "389",
                    "ID": "389",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54832",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481001,
                "startTime": 1494276481000
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "2450",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "390",
                    "ID": "390",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.233:54831",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481002,
                "startTime": 1494276481001
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "994",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "391",
                    "ID": "391",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43457",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481003,
                "startTime": 1494276481002
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "14",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "392",
                    "ID": "392",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43458",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481004,
                "startTime": 1494276481003
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "53",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "393",
                    "ID": "393",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43460",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481005,
                "startTime": 1494276481004
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "14",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "439",
                    "ID": "439",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:48144",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481006,
                "startTime": 1494276481005
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "8714",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "440",
                    "ID": "440",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:39920",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481007,
                "startTime": 1494276481006
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "7",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "441",
                    "ID": "441",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:43336",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481008,
                "startTime": 1494276481007
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "82",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "451",
                    "ID": "451",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:40318",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481009,
                "startTime": 1494276481008
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "442",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "453",
                    "ID": "453",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:44415",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481010,
                "startTime": 1494276481009
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "12",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "452",
                    "ID": "452",
                    "INFO": "",
                    "COMMAND": "Sleep",
                    "THEHOST": "192.168.17.243:59639",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481011,
                "startTime": 1494276481010
            },
            {
                "tsuid": "00004300000200001B00000300001B",
                "description": "",
                "notes": "",
                "custom": {
                    "TIME": "0",
                    "STATE": "",
                    "classname": "core.mysql.Database",
                    "ne_id": "1000026727741",
                    "DB": "mysql",
                    "THEUSER": "root",
                    "config_name": "454",
                    "ID": "454",
                    "INFO": "SHOW FULL PROCESSLIST",
                    "COMMAND": "Query",
                    "THEHOST": "192.168.17.233:45868",
                    "collect_time": "20170509044801"
                },
                "endTime": 1494276481012,
                "startTime": 1494276481011
            }
        ],
        "dps": {}
    }
]

**Comment by manolama** [comment]
Oooh that's a fun on. The timestamp filter is only on the numeric values, not annotations at this time. Should be an easy fix.
