### ISSUE TITLE
why tsdb query return the data out of the time range?

### ISSUE THREAD

**Issue by skygragon** [OpenTSDB/opentsdb#997]
Am I missing something here?

```
$ tsdb query 1m-ago sum active.request.number_value
active.request.number_value 1497334053000 1688 {}
active.request.number_value 1497335214000 1745 {}
active.request.number_value 1497335819000 1340 {}
active.request.number_value 1497336397000 460 {}
active.request.number_value 1497337019000 378 {}

$ date +%s
1497337163
```

**Comment by manolama** [comment]
It's been documented in a few places that the old CLI and V1 query API return data outside the query bound due to the layout in HBase and use in creating "clean" edges around plot boundaries. To avoid the extraneous data, use the V2 HTTP API please.

**Comment by skygragon** [comment]
Glad to know that, thanks!
